### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by remikarlsen** [4ian/GDevelop#1016]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at l.determineFontProperties (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/0.027ea85d.chunk.js:1:1409390)
    at l.updateText (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/0.027ea85d.chunk.js:1:1406190)
    at l.get (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/0.027ea85d.chunk.js:1:1404575)
    at s.update (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.1e8a4f32.chunk.js:1:133131)
    at InitialInstanceJSFunctor.instancesRenderer.invoke (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.1e8a4f32.chunk.js:1:138118)
    at Array.<anonymous> (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/libGD.js:20:18365)
    at _emscripten_asm_const_iii (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/libGD.js:20:28235)
    at Array.DK (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/libGD.js:33:6613)
    at Array.CK (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/libGD.js:33:6571)
    at maa (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/libGD.js:31:69532)
    at Nx (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/libGD.js:25:1102)
    at InitialInstancesContainer.IterateOverInstancesWithZOrdering.InitialInstancesContainer.IterateOverInstancesWithZOrdering [as iterateOverInstancesWithZOrdering] (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/libGD.js:7672:3)
    at e.value (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.1e8a4f32.chunk.js:1:138787)
    at e.value (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.1e8a4f32.chunk.js:1:305669)
    at t.e._renderScene (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.1e8a4f32.chunk.js:1:323196)
    at t.value (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.1e8a4f32.chunk.js:1:329959)
    at ki (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/53.f92ae050.chunk.js:1:317778)
    at Qi (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/53.f92ae050.chunk.js:1:327367)
    at eo (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/53.f92ae050.chunk.js:1:331110)
    at Ro (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/53.f92ae050.chunk.js:1:345170)
    at Po (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/53.f92ae050.chunk.js:1:345516)
    at ha (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/53.f92ae050.chunk.js:1:350188)
    at la (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/53.f92ae050.chunk.js:1:349842)
    at Do (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/53.f92ae050.chunk.js:1:348354)
    at Object.enqueueSetState (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/53.f92ae050.chunk.js:1:317188)
    at l.g.setState (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/53.f92ae050.chunk.js:1:266468)
    at Object.onMeasure (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.1e8a4f32.chunk.js:1:222489)
    at file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/0.027ea85d.chunk.js:1:1344864
    at Array.some (<anonymous>)
    at t.n.measure (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/0.027ea85d.chunk.js:1:1344801)
    at ResizeObserver.<anonymous> (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/0.027ea85d.chunk.js:1:1345589)
```

## Component stack (don't write anything here)
```

    in t
    in div
    in n
    in div
    in t
    in l
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in t
    in t
    in div
    in t
    in t
    in t
    in Unknown
    in div
    in div
    in t
    in div
    in div
    in t
    in t
    in t
    in div
    in t
    in t
    in t
    in t
    in t
    in t
    in t
    in t
    in n
    in t
    in t
    in t
    in DragDropContext(t)
    in t
    in t
```

**Comment by Bouh** [comment]
Same as #1196
