### ISSUE TITLE
Crash when trying to extract an event into a function

### ISSUE THREAD

**Issue by Wend1go** [4ian/GDevelop#1028]
The IDE crashes when I try to convert an event into a function.

Version:
In development version from master (19.04.2019 / 12:00)

## Error stack (don't write anything here)
```
TypeError: d.getReferencedObjectOrGroupNames is not a function
    at l (file:///home/matthias/Programme/GD_MyFork/GDevelop/newIDE/electron-app/dist/linux-unpacked/resources/app.asar/www/static/js/1.c50aa4d6.chunk.js:1:593643)
    at t.value (file:///home/matthias/Programme/GD_MyFork/GDevelop/newIDE/electron-app/dist/linux-unpacked/resources/app.asar/www/static/js/1.c50aa4d6.chunk.js:1:125711)
    at pa (file:///home/matthias/Programme/GD_MyFork/GDevelop/newIDE/electron-app/dist/linux-unpacked/resources/app.asar/www/static/js/53.2d54d1d6.chunk.js:1:251025)
    at ha (file:///home/matthias/Programme/GD_MyFork/GDevelop/newIDE/electron-app/dist/linux-unpacked/resources/app.asar/www/static/js/53.2d54d1d6.chunk.js:1:246640)
    at la (file:///home/matthias/Programme/GD_MyFork/GDevelop/newIDE/electron-app/dist/linux-unpacked/resources/app.asar/www/static/js/53.2d54d1d6.chunk.js:1:246256)
    at Do (file:///home/matthias/Programme/GD_MyFork/GDevelop/newIDE/electron-app/dist/linux-unpacked/resources/app.asar/www/static/js/53.2d54d1d6.chunk.js:1:244768)
    at Object.enqueueSetState (file:///home/matthias/Programme/GD_MyFork/GDevelop/newIDE/electron-app/dist/linux-unpacked/resources/app.asar/www/static/js/53.2d54d1d6.chunk.js:1:213602)
    at t.v.setState (file:///home/matthias/Programme/GD_MyFork/GDevelop/newIDE/electron-app/dist/linux-unpacked/resources/app.asar/www/static/js/53.2d54d1d6.chunk.js:1:162882)
    at t.n.extractEventsToFunction (file:///home/matthias/Programme/GD_MyFork/GDevelop/newIDE/electron-app/dist/linux-unpacked/resources/app.asar/www/static/js/1.c50aa4d6.chunk.js:1:538355)
    at click (file:///home/matthias/Programme/GD_MyFork/GDevelop/newIDE/electron-app/dist/linux-unpacked/resources/app.asar/www/static/js/1.c50aa4d6.chunk.js:1:544775)
    at CallbacksRegistry.apply (/home/matthias/Programme/GD_MyFork/GDevelop/newIDE/electron-app/dist/linux-unpacked/resources/electron.asar/common/api/callbacks-registry.js:47:25)
    at EventEmitter.ipcRenderer.on (/home/matthias/Programme/GD_MyFork/GDevelop/newIDE/electron-app/dist/linux-unpacked/resources/electron.asar/renderer/api/remote.js:285:21)
    at EventEmitter.emit (events.js:182:13)
```

## Component stack (don't write anything here)
```

    in t
    in div
    in t
    in n
    in t
    in t
    in n
    in t
    in Unknown
    in div
    in div
    in t
    in div
    in div
    in t
    in t
    in t
    in div
    in t
    in t
    in t
    in t
    in t
    in t
    in t
    in t
    in n
    in t
    in t
    in t
    in DragDropContext(t)
    in t
    in t
```
## How to reproduce:
1) cd newIDE/electron-app
2) npm run build
3) Start the IDE and open an example (in my case the "pairs" game)
4) Right click on any event (for example at the beginning of the scene -> show layer fade)
5) Choose "Extract events into a function"
6) The above error is shown.

**Comment by 4ian** [comment]
libGD.js is outdated :)
Remove `newIDE/app/public/libGD.js` and relaunch `npm start` (or `npm run build`). This will download latest version.

**Comment by Wend1go** [comment]
Thanks, now it is working as it should.
The "Extract events to a function" will be a real time saver for existing projects. Works really well. :+1: 
But the sentence sounds a little strange. How about "Convert events into a function"?
Any ETA for the next version?

**Comment by 4ian** [comment]
True that extract is a bit weird maybe. I'll change this.
Also note that this kind of issue with outdated libGD.js will soon be gone forever, when I'll integrate GDevelop.js in this repo and will make automatic build of libGD.js after each commit (that will be downloaded if you don't have it locally)

**Comment by 4ian** [comment]
ETA is next few days unless major issue.

**Comment by Wend1go** [comment]
That would be great, closing this now since it is not really a bug.

**Comment by 4ian** [comment]
FYI, libGD.js builds are now automatic (done in ~25 minutes after a change on master), so such problems should almost not happen anymore: https://github.com/4ian/GDevelop/issues/1012#issuecomment-485899342
