### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by KatherineRR** [4ian/GDevelop#1062]
=> Removed a scene
## Error stack (don't write anything here)
```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at Function.e.measureFont (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.66d6cfdd.chunk.js:1:751449)
    at Function.e.measureText (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.66d6cfdd.chunk.js:1:748504)
    at t.updateText (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.66d6cfdd.chunk.js:1:1475214)
    at t.get (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.66d6cfdd.chunk.js:1:1479580)
    at i.getDefaultWidth (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.a597b73d.chunk.js:1:123541)
    at e.getInstanceWidth (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.a597b73d.chunk.js:1:159922)
    at e.value (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.a597b73d.chunk.js:1:161738)
    at InitialInstanceJSFunctor.instancesRenderer.invoke (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.a597b73d.chunk.js:1:161465)
    at Array.<anonymous> (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js:20:19250)
    at _emscripten_asm_const_iii (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js:20:28235)
    at Array.RJ (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js:27:13236)
    at Array.QJ (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js:27:13194)
    at v8 (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js:25:103912)
    at ax (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js:24:146559)
    at InitialInstancesContainer.IterateOverInstancesWithZOrdering.InitialInstancesContainer.IterateOverInstancesWithZOrdering [as iterateOverInstancesWithZOrdering] (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js:7727:3)
    at e.value (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.a597b73d.chunk.js:1:162192)
    at e.value (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.a597b73d.chunk.js:1:327824)
    at t.e._renderScene (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.a597b73d.chunk.js:1:346132)
    at t.e.restartSceneRendering (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.a597b73d.chunk.js:1:346535)
    at t.value (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.a597b73d.chunk.js:1:353659)
    at ki (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/54.435723ea.chunk.js:1:325246)
    at Qi (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/54.435723ea.chunk.js:1:334835)
    at eo (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/54.435723ea.chunk.js:1:338578)
    at Ro (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/54.435723ea.chunk.js:1:352638)
    at Po (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/54.435723ea.chunk.js:1:352984)
    at ha (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/54.435723ea.chunk.js:1:357656)
    at la (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/54.435723ea.chunk.js:1:357310)
    at va (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/54.435723ea.chunk.js:1:363551)
    at kn (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/54.435723ea.chunk.js:1:308638)
    at HTMLDocument.i (file:///C:/Users/Katherine%20Rodriguez/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/54.435723ea.chunk.js:1:820910)
```

## Component stack (don't write anything here)
```

    in t
    in div
    in n
    in div
    in t
    in l
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in t
    in t
    in div
    in t
    in t
    in n
    in t
    in Unknown
    in div
    in div
    in t
    in div
    in div
    in t
    in t
    in t
    in div
    in t
    in t
    in t
    in t
    in t
    in t
    in t
    in t
    in n
    in t
    in t
    in t
    in DragDropContext(t)
    in t
    in t
```

**Comment by 4ian** [comment]
@KatherineRR Are you able to reproduce this crash consistently?

**Comment by Bouh** [comment]
Same as #1196

**Comment by 4ian** [comment]
Closing to avoid duplicates then :)
