### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by franklinarauj** [4ian/GDevelop#1090]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: Cannot read property 'toString' of undefined
    at BehaviorSharedDataJsImplementation.sharedData.getProperties (D:\Users\estagiario40986\AppData\Local\Programs\gdevelop\resources\GDJS\Runtime\Extensions\Physics2Behavior\JsExtension.js:320:58)
    at Array.<anonymous> (file:///D:/Users/estagiario40986/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js:20:27401)
    at _emscripten_asm_const_iii (file:///D:/Users/estagiario40986/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js:20:28235)
    at Array.bM (file:///D:/Users/estagiario40986/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js:27:53477)
    at Kc (file:///D:/Users/estagiario40986/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js:24:3856)
    at BehaviorsSharedData.GetProperties.BehaviorsSharedData.GetProperties [as getProperties] (file:///D:/Users/estagiario40986/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js:344:22)
    at file:///D:/Users/estagiario40986/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.a597b73d.chunk.js:1:236682
    at Array.map (<anonymous>)
    at t.value (file:///D:/Users/estagiario40986/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.a597b73d.chunk.js:1:236629)
    at Yi (file:///D:/Users/estagiario40986/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/54.435723ea.chunk.js:1:336103)
    at Qi (file:///D:/Users/estagiario40986/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/54.435723ea.chunk.js:1:335944)
    at eo (file:///D:/Users/estagiario40986/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/54.435723ea.chunk.js:1:338578)
    at Ro (file:///D:/Users/estagiario40986/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/54.435723ea.chunk.js:1:352638)
    at Po (file:///D:/Users/estagiario40986/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/54.435723ea.chunk.js:1:352984)
    at ha (file:///D:/Users/estagiario40986/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/54.435723ea.chunk.js:1:357656)
    at la (file:///D:/Users/estagiario40986/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/54.435723ea.chunk.js:1:357310)
    at va (file:///D:/Users/estagiario40986/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/54.435723ea.chunk.js:1:363551)
    at kn (file:///D:/Users/estagiario40986/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/54.435723ea.chunk.js:1:308638)
    at HTMLDocument.i (file:///D:/Users/estagiario40986/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/54.435723ea.chunk.js:1:820910)
```

## Component stack (don't write anything here)
```

    in t
    in div
    in t
    in t
    in n
    in t
    in Unknown
    in div
    in div
    in t
    in div
    in div
    in t
    in t
    in t
    in div
    in t
    in t
    in t
    in t
    in t
    in t
    in t
    in t
    in n
    in t
    in t
    in t
    in DragDropContext(t)
    in t
    in t
```

**Comment by 4ian** [comment]
Can you send/upload here a zip containing the game that is having this crash?
