### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by amidos2006** [4ian/GDevelop#1291]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: Cannot read property 'value' of undefined
    at file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.a6be2aba.chunk.js:1:514462
    at q (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.76b6b3db.chunk.js:1:135837)
    at e (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.76b6b3db.chunk.js:1:135085)
    at e (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.76b6b3db.chunk.js:1:135208)
    at D (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.76b6b3db.chunk.js:1:135534)
    at U (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.76b6b3db.chunk.js:1:136177)
    at Object.map (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.76b6b3db.chunk.js:1:136332)
    at t.value (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.a6be2aba.chunk.js:1:514406)
    at Bo (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.76b6b3db.chunk.js:1:202405)
    at Do (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.76b6b3db.chunk.js:1:202181)
    at jo (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.76b6b3db.chunk.js:1:206312)
    at Za (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.76b6b3db.chunk.js:1:233519)
    at es (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.76b6b3db.chunk.js:1:234269)
    at Ms (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.76b6b3db.chunk.js:1:239915)
    at Ds (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.76b6b3db.chunk.js:1:239295)
    at js (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.76b6b3db.chunk.js:1:240389)
    at Me (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.76b6b3db.chunk.js:1:148784)
    at Nn (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.76b6b3db.chunk.js:1:169410)
    at HTMLDocument.i (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.76b6b3db.chunk.js:1:684009)
```

## Component stack (don't write anything here)
```

    in t
    in t
    in div
    in i
    in div
    in o
    in div
    in div
    in o
    in div
    in i
    in t
    in t
    in div
    in ForwardRef
    in div
    in i
    in t
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in b
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in t
    in a
    in t
    in div
    in t
    in t
    in Unknown
    in div
    in t
    in div
    in t
    in t
    in t
    in t
    in t
    in t
    in Unknown
    in t
    in t
    in t
    in t
    in DragDropContext(t)
    in t
    in u
```

**Comment by 4ian** [comment]
Unfortunately not much to discover in the error :/ Closing for now
