### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by j-c-levin** [4ian/GDevelop#1319]
Problem: Attempting to add a behaviour parameter to a custom action in a behaviour results in an error

To reproduce
1. create a custom action for a behaviour
1. add an object to the parameters
1. add a behaviour (to previous object)

How I work around it: I manually add in the behaviour type in the `game.json` file and this seems to allow it to work

Setup (the `hero` type at the bottom is because I manually added that in the json file, otherwise this page would have crashed)
![image](https://user-images.githubusercontent.com/9204074/70862966-e47a3580-1f3a-11ea-98e4-a6726e7cf591.png)

## Error stack (don't write anything here)
```
TypeError: Cannot read property 'value' of undefined
    at file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.4012f1db.chunk.js:1:373919
    at M (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:133668)
    at e (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:132916)
    at e (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:133039)
    at D (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:133365)
    at U (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:134008)
    at Object.map (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:134163)
    at t.value (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.4012f1db.chunk.js:1:373863)
    at Ao (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:199631)
    at Io (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:199424)
    at Lo (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:203281)
    at Wa (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:227410)
    at Ga (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:227794)
    at As (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:234691)
    at Ns (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:234071)
    at Os (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:235165)
    at Be (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:146606)
    at Nn (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:167230)
    at HTMLDocument.i (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:671227)
```

## Component stack (don't write anything here)
```

    in t
    in t
    in div
    in i
    in div
    in o
    in div
    in div
    in o
    in div
    in i
    in t
    in t
    in div
    in ForwardRef
    in div
    in i
    in t
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in b
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in t
    in a
    in t
    in div
    in t
    in t
    in Unknown
    in div
    in t
    in div
    in t
    in t
    in t
    in t
    in t
    in t
    in Unknown
    in t
    in t
    in t
    in t
    in DragDropContext(t)
    in t
    in a
```

**Comment by Bouh** [comment]
Already fix here :) 
https://github.com/4ian/GDevelop/issues/1276#issuecomment-560732922

**Comment by 4ian** [comment]
Closing as there is a work around in the other thread :)

**Comment by 4ian** [comment]
Thanks for the clear error report though! :) Will release a new version with fixes soon I hope.
