### ISSUE TITLE
Crash while working on a new custom Function/Extension !!FOUND THE PROBLEM!!

### ISSUE THREAD

**Issue by WolfPhoton** [4ian/GDevelop#1349]
EDIT: **FOUND THE PROBLEM** ... It happens when you select behavior as type of parameter with object type as any object or other than sprite. Now please fix this...... :)
Was **creating a parameter of type behavior**. Suddenly error occurred.

## Error stack (don't write anything here)
```
TypeError: Cannot read property 'value' of undefined
    at file:///C:/Users/Dell/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.4012f1db.chunk.js:1:373919
    at M (file:///C:/Users/Dell/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:133668)
    at e (file:///C:/Users/Dell/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:132916)
    at e (file:///C:/Users/Dell/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:133039)
    at D (file:///C:/Users/Dell/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:133365)
    at U (file:///C:/Users/Dell/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:134008)
    at Object.map (file:///C:/Users/Dell/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:134163)
    at t.value (file:///C:/Users/Dell/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.4012f1db.chunk.js:1:373863)
    at Ao (file:///C:/Users/Dell/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:199631)
    at Io (file:///C:/Users/Dell/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:199424)
    at Lo (file:///C:/Users/Dell/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:203281)
    at Wa (file:///C:/Users/Dell/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:227410)
    at Ga (file:///C:/Users/Dell/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:227794)
    at As (file:///C:/Users/Dell/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:234691)
    at Ns (file:///C:/Users/Dell/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:234071)
    at Ds (file:///C:/Users/Dell/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:235446)
    at Tn (file:///C:/Users/Dell/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:166972)
    at HTMLDocument.i (file:///C:/Users/Dell/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/56.52712f1e.chunk.js:1:671227)
```

## Component stack (don't write anything here)
```

    in t
    in t
    in div
    in i
    in div
    in o
    in div
    in div
    in o
    in div
    in i
    in t
    in t
    in div
    in ForwardRef
    in div
    in i
    in t
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in b
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in t
    in a
    in t
    in div
    in t
    in t
    in Unknown
    in div
    in t
    in div
    in t
    in t
    in t
    in t
    in t
    in t
    in Unknown
    in t
    in t
    in t
    in t
    in DragDropContext(t)
    in t
    in a
```

**Comment by blurymind** [comment]
Can you share the custom function/extension? Its kind of hard to tell what's going on to lead to this.
It will really help us if you share a minimal example project. Just zip it and drag and drop it into the comment box, git will let you attach it

**Comment by 4ian** [comment]
Already fixed for next version: https://github.com/4ian/GDevelop/issues/1304
