### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by vamsi-byjus** [4ian/GDevelop#1609]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: gd.Project.validateObjectName is not a function
    at validateEventsFunctionName (webpack-internal:///./src/EventsSheet/EventsFunctionExtractor/index.js:119:21)
    at EventsFunctionExtractorDialog.render (webpack-internal:///./src/EventsSheet/EventsFunctionExtractor/EventsFunctionExtractorDialog.js:372:84)
    at finishClassComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:15320:35)
    at updateClassComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:15275:28)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:16265:20)
    at performUnitOfWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20285:16)
    at workLoop (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20326:28)
    at renderRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20406:11)
    at performWorkOnRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21363:11)
    at performWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21273:11)
    at performSyncWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21247:7)
    at requestWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21102:9)
    at scheduleWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20915:9)
    at Object.enqueueSetState (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11596:9)
    at EventsSheet.Component.setState (webpack-internal:///./node_modules/react/cjs/react.development.js:336:20)
    at EventsSheet._this.extractEventsToFunction (webpack-internal:///./src/EventsSheet/index.js:565:13)
    at click (webpack-internal:///./src/EventsSheet/index.js:1081:37)
    at CallbacksRegistry.apply (/Users/vamsi/html5/explore-extensions/GDevelop/newIDE/electron-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js:47:25)
    at EventEmitter.ipcRenderer.on (/Users/vamsi/html5/explore-extensions/GDevelop/newIDE/electron-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:285:21)
    at EventEmitter.emit (events.js:182:13)
```

## Component stack (don't write anything here)
```

    in EventsFunctionExtractorDialog (at EventsSheet/index.js:1280)
    in div (at EventsSheet/index.js:1006)
    in EventsSearcher (at EventsSheet/index.js:990)
    in ResponsiveWindowMeasurer (at EventsSheet/index.js:986)
    in ScreenTypeMeasurer (at EventsSheet/index.js:984)
    in EventsSheet (at EventsEditor.js:40)
    in EventsEditor (at MainFrame/index.js:975)
    in ErrorBoundary (at ErrorBoundary.js:83)
    in ErrorBoundary (at MainFrame/index.js:1810)
    in div (at ClosableTabs.js:64)
    in TabContentContainer (at MainFrame/index.js:1809)
    in div (at MainFrame/index.js:1708)
    in MainFrame (at LocalApp.js:104)
    in ElectronMainMenu (at LocalApp.js:103)
    in ProjectStorageProviders (at LocalApp.js:92)
    in EventsFunctionsExtensionsProvider (at Providers.js:63)
    in I18n (at Providers.js:61)
    in UserProfileProvider (at Providers.js:60)
    in ThemeProvider (at Providers.js:59)
    in I18nProvider (at GDI18nProvider.js:90)
    in GDI18nProvider (at Providers.js:57)
    in PreferencesProvider (at Providers.js:52)
    in DragAndDropContextProvider (created by DragDropContext(DragAndDropContextProvider))
    in DragDropContext(DragAndDropContextProvider) (at Providers.js:51)
    in Providers (at LocalApp.js:84)
    in Bootstrapper (at src/index.js:83)
```

**Comment by 4ian** [comment]
Is this on the web-app or on a local development version?

**Comment by Bouh** [comment]
`at EventEmitter.ipcRenderer.on (/Users/vamsi/html5/explore-extensions/GDevelop/newIDE/electron-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:285:21)`

Electron.

But `gd.Project.validateObjectName` isn't in the codebase anymore. [Because replaced by this.](https://github.com/4ian/GDevelop/pull/1560/files).

Maybe we should improve bug report, we have often issue with missing informations like build version and which OS.

**Comment by 4ian** [comment]
I think this is caused by an out of date libGD.js.

> Maybe we should improve bug report, we have often issue with missing informations like build version and which OS.

Right, should not be too hard to get these and include these in the generated message?

**Comment by Bouh** [comment]
I've found why this crash !
Found by accident when i tried to find how crash the app for see the informations just added in my branch like OS and version of GD for write it in bug report. lol. 

[Here a video ](https://streamable.com/wnasf) of why `gd.Project.validateName is not a function`  !
