### ISSUE TITLE
Crash while using an editor with abuse of CTRL+Z

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1617]
I've changed a value in eventsheet, and maybe abuse with CTRL+Z, the web-app crash. 
For resume the bug, when i stay on CTRL+Z, and i click after more 5second in the eventsheet, crash happend.

Only in web-app, tested on my branch. (You can see below the new bug report not yet merged =) )
This bug living also on editor.gdevelop-app.com

[Here a video clip with the inputs pressed.](https://streamable.com/60s7io)
Here the full log more details.
[crash-abuse.log](https://github.com/4ian/GDevelop/files/4429515/crash-abuse.log)

## Error stack (don't write anything here)
```
Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at invariant (http://localhost:3000/static/js/4.chunk.js:20721:19)
    at scheduleWork (http://localhost:3000/static/js/4.chunk.js:41585:9)
    at dispatchAction (http://localhost:3000/static/js/4.chunk.js:34783:9)
    at http://localhost:3000/static/js/0.chunk.js:23177:5
    at http://localhost:3000/static/js/0.chunk.js:23201:5
    at commitHookEffectList (http://localhost:3000/static/js/4.chunk.js:38723:30)
    at commitLifeCycles (http://localhost:3000/static/js/4.chunk.js:38759:13)
    at commitAllLifeCycles (http://localhost:3000/static/js/4.chunk.js:40338:11)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/4.chunk.js:20811:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/4.chunk.js:20860:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/4.chunk.js:20914:35)
    at commitRoot (http://localhost:3000/static/js/4.chunk.js:40562:11)
    at http://localhost:3000/static/js/4.chunk.js:42110:9
    at Object.unstable_runWithPriority (http://localhost:3000/static/js/4.chunk.js:50179:16)
    at completeRoot (http://localhost:3000/static/js/4.chunk.js:42109:17)
    at performWorkOnRoot (http://localhost:3000/static/js/4.chunk.js:42032:13)
    at performWork (http://localhost:3000/static/js/4.chunk.js:41937:11)
    at flushInteractiveUpdates$1 (http://localhost:3000/static/js/4.chunk.js:42204:9)
    at batchedUpdates (http://localhost:3000/static/js/4.chunk.js:22924:11)
    at dispatchEvent (http://localhost:3000/static/js/4.chunk.js:25774:9)
    at http://localhost:3000/static/js/4.chunk.js:42190:18
    at Object.unstable_runWithPriority (http://localhost:3000/static/js/4.chunk.js:50179:16)
    at interactiveUpdates$1 (http://localhost:3000/static/js/4.chunk.js:42189:26)
    at interactiveUpdates (http://localhost:3000/static/js/4.chunk.js:22932:14)
    at dispatchInteractiveEvent (http://localhost:3000/static/js/4.chunk.js:25750:7)
```

## Component stack (don't write anything here)
```

    in ForwardRef(TextareaAutosize) (created by ForwardRef(InputBase))
    in div (created by ForwardRef(InputBase))
    in ForwardRef(InputBase) (created by WithStyles(ForwardRef(InputBase)))
    in WithStyles(ForwardRef(InputBase)) (created by ForwardRef(Input))
    in ForwardRef(Input) (created by WithStyles(ForwardRef(Input)))
    in WithStyles(ForwardRef(Input)) (created by ForwardRef(TextField))
    in div (created by ForwardRef(FormControl))
    in ForwardRef(FormControl) (created by WithStyles(ForwardRef(FormControl)))
    in WithStyles(ForwardRef(FormControl)) (created by ForwardRef(TextField))
    in ForwardRef(TextField) (created by WithStyles(ForwardRef(TextField)))
    in WithStyles(ForwardRef(TextField)) (at TextField.js:188)
    in I18n (at TextField.js:186)
    in TextField (at SemiControlledTextField.js:87)
    in SemiControlledTextField (at GenericExpressionField/index.js:330)
    in div (at GenericExpressionField/index.js:324)
    in div (at GenericExpressionField/index.js:323)
    in div (at Layout.js:64)
    in TextFieldWithButtonLayout (at GenericExpressionField/index.js:320)
    in ExpressionField (at ExpressionField.js:18)
    in ExpressionField (at InlineParameterEditor.js:119)
    in div (at Grid.js:10)
    in Line (at InlinePopover.js:40)
    in div (at Grid.js:30)
    in Column (at InlinePopover.js:39)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (at Background.js:28)
    in Background (at InlinePopover.js:38)
    in div (created by ForwardRef(Popper))
    in ForwardRef(Portal) (created by ForwardRef(Popper))
    in ForwardRef(Popper) (at InlinePopover.js:32)
    in ForwardRef(ClickAwayListener) (at InlinePopover.js:31)
    in InlinePopover (at InlineParameterEditor.js:114)
    in InlineParameterEditor (at EventsSheet/index.js:1104)
    in div (at EventsSheet/index.js:1017)
    in EventsSearcher (at EventsSheet/index.js:1001)
    in ResponsiveWindowMeasurer (at EventsSheet/index.js:997)
    in ScreenTypeMeasurer (at EventsSheet/index.js:995)
    in EventsSheet (at EventsEditor.js:44)
    in EventsEditor (at MainFrame/index.js:1020)
    in ErrorBoundary (at ErrorBoundary.js:94)
    in ErrorBoundary (at MainFrame/index.js:1902)
    in div (at ClosableTabs.js:64)
    in TabContentContainer (at MainFrame/index.js:1901)
    in div (at MainFrame/index.js:1799)
    in MainFrame (at BrowserApp.js:65)
    in ProjectStorageProviders (at BrowserApp.js:46)
    in EventsFunctionsExtensionsProvider (at Providers.js:67)
    in I18n (at Providers.js:65)
    in UserProfileProvider (at Providers.js:62)
    in ThemeProvider (at Providers.js:61)
    in I18nProvider (at GDI18nProvider.js:90)
    in GDI18nProvider (at Providers.js:59)
    in PreferencesProvider (at Providers.js:54)
    in UnsavedChangesContextProvider (at Providers.js:53)
    in DragAndDropContextProvider (created by DragDropContext(DragAndDropContextProvider))
    in DragDropContext(DragAndDropContextProvider) (at Providers.js:52)
    in Providers (at BrowserApp.js:38)
    in Bootstrapper (at src/index.js:81)
```

## Other details
* GDevelop5.0.0-beta89 based on GDevelop.js 4.0.98-0-release
* Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

This new details rocks !

**Comment by 4ian** [comment]
Similar issue it seems here: #1651
