### ISSUE TITLE
Crash while using the editor

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#1651]
I'm trying beta 90 and the editor keeps crashing. 
If I click on the first field of that line:
![image](https://user-images.githubusercontent.com/25978830/79165452-73ad3200-7de3-11ea-9bd2-a066a4ecf012.png)
It always crashes.
And with that line:
![image](https://user-images.githubusercontent.com/25978830/79166313-2af67880-7de5-11ea-9bf2-c1f54f1d7e87.png)
See how it's at the end of the line, and bottom of box, in edit mode:
![image](https://user-images.githubusercontent.com/25978830/79166188-ed91eb00-7de4-11ea-8d8b-7d53f8cf1d21.png)
If I write another 'l' in there, it crashes.

## Error stack (don't write anything here)
```
Invariant Violation: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at a (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:37498)
    at u (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:37768)
    at qa (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:132769)
    at to (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:93461)
    at file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.234712d0.chunk.js:2:1756600
    at file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.234712d0.chunk.js:2:1756929
    at oa (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:112817)
    at Ra (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:119691)
    at ja (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:122688)
    at file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:135788
    at Object.t.unstable_runWithPriority (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:146555)
    at Su (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:135722)
    at Tu (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:135498)
    at Eu (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:134843)
    at Nu (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:136222)
    at Nn (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:67909)
    at HTMLDocument.i (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:350019)
```

## Component stack (don't write anything here)
```

    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in t
    in c
    in i
    in div
    in div
    in div
    in c
    in _
    in i
    in div
    in s
    in div
    in i
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in u
    in r
    in div
    in l
    in a
    in o
    in F
    in l
    in t
    in Unknown
    in div
    in m
    in div
    in Z
    in i
    in X
    in t
    in L
    in Unknown
    in t
    in c
    in z
    in i
    in u
    in DragDropContext(u)
    in Z
    in m
```

## Other details
* IDE version: 5.0.0-beta90-a47acbb82a3c19ed8508f40be293e4eec2cb2139
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.17763,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta90 Chrome/80.0.3987.163 Electron/8.2.1 Safari/537.36,

**Comment by 4ian** [comment]
Any chance you are able to reproduce this on an example?

**Comment by 4ian** [comment]
This seems related to #1617 (same React error)

**Comment by Bouh** [comment]
> Any chance you are able to reproduce this on an example?

Yes always for me!
Open platformer open a input numeric expression feild, long press i, and wait crash.
This happend only on numeric expression feild with a expression inside.

And for be more precise, this crash is on desktop too.
w10.

**Comment by 4ian** [comment]
I can reproduce! Thanks, very useful. Might be related to some timeouts when handling autocompletions, this is strange but I'll try to fix that and then I'll release beta 91. :)

**Comment by 4ian** [comment]
This is a material-ui issue fixed in 19743
We should upgrade to material-ui 4.9.5 or more recent :)
