### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by chowardev** [4ian/GDevelop#1678]
=> Crushed when I was trying to do an event.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: n[q[((q[(Tf >> 2)] + 12) >> 2)]] is not a function
    at jj (https://editor.gdevelop-app.com/libGD.js:21:69997)
    at BaseEvent.IsExecutable.BaseEvent.IsExecutable [as isExecutable] (https://editor.gdevelop-app.com/libGD.js:75:1030144)
    at https://editor.gdevelop-app.com/static/js/1.5f18434f.chunk.js:1:534276
    at Array.some (<anonymous>)
    at F._selectionCanToggleDisabled (https://editor.gdevelop-app.com/static/js/1.5f18434f.chunk.js:1:534266)
    at Object.buildMenuTemplate (https://editor.gdevelop-app.com/static/js/1.5f18434f.chunk.js:1:548030)
    at O.render (https://editor.gdevelop-app.com/static/js/1.5f18434f.chunk.js:1:489306)
    at To (https://editor.gdevelop-app.com/static/js/59.06a7dabd.chunk.js:2:100477)
    at ko (https://editor.gdevelop-app.com/static/js/59.06a7dabd.chunk.js:2:100270)
    at Co (https://editor.gdevelop-app.com/static/js/59.06a7dabd.chunk.js:2:104131)
    at Ua (https://editor.gdevelop-app.com/static/js/59.06a7dabd.chunk.js:2:128043)
    at Fa (https://editor.gdevelop-app.com/static/js/59.06a7dabd.chunk.js:2:128427)
    at Tu (https://editor.gdevelop-app.com/static/js/59.06a7dabd.chunk.js:2:135463)
    at Eu (https://editor.gdevelop-app.com/static/js/59.06a7dabd.chunk.js:2:134843)
    at Nu (https://editor.gdevelop-app.com/static/js/59.06a7dabd.chunk.js:2:136222)
    at Nn (https://editor.gdevelop-app.com/static/js/59.06a7dabd.chunk.js:2:67909)
    at HTMLDocument.i (https://editor.gdevelop-app.com/static/js/59.06a7dabd.chunk.js:2:350019)
```

## Component stack (don't write anything here)
```

    in O
    in div
    in l
    in a
    in o
    in F
    in l
    in t
    in Unknown
    in div
    in m
    in div
    in Z
    in i
    in X
    in t
    in L
    in Unknown
    in t
    in c
    in z
    in i
    in u
    in DragDropContext(u)
    in Z
    in m
```

## Other details
* IDE version: 5.0.0-beta90-c4ba35729682a2c8564ee5b31c105a8d71f57bfa
* Arch: Unknown architecture (web-app),
* Platform Name: Linux x86_64,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (X11; CrOS x86_64 12871.76.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.103 Safari/537.36,

**Comment by 4ian** [comment]
Interesting, do you remember the exact action you were doing?
I've updated the web-app (you might have to clear your cache to run it), let me know if you have detailed steps to do reproduce it.

**Comment by chowardev** [comment]
Hello,

Well, I was going through the 2D platform tutorial.  I had just gotten to
the part where I was supposed to tell the engine that if two coins were
overlapping not to count them as one. First I clicked the round button with
the plus in the middle, then I clicked (for each object). After that, I
click on (Click to choose for which object....) but nothing popped up. So
then I clicked the undone button and it crashed.

**Comment by Bouh** [comment]
I can reproduce it :)
- Open the platformer example, add any event. select it, press directly undo, see the error.

**Comment by 4ian** [comment]
I've tried but I don't have this issue. Can you confirm that you can reproduce it again?

**Comment by Bouh** [comment]
Yes always
https://streamable.com/fyc0dq

**Comment by 4ian** [comment]
Fixed! Thanks both for reporting the issue :) 
It was a web-app specific issue but I also fixed a potential crash if using the toolbar in the events sheet after doing an undo/redo (because the selected events were not reset).
I'll update the web-app with this.
