### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by MGHOZLAN** [4ian/GDevelop#1679]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: (0 , e.children) is not a function
    at https://editor.gdevelop-app.com/static/js/0.20575d19.chunk.js:2:466439
    at Wi (https://editor.gdevelop-app.com/static/js/59.8473c3be.chunk.js:2:90461)
    at Co (https://editor.gdevelop-app.com/static/js/59.8473c3be.chunk.js:2:102772)
    at Ua (https://editor.gdevelop-app.com/static/js/59.8473c3be.chunk.js:2:128043)
    at Fa (https://editor.gdevelop-app.com/static/js/59.8473c3be.chunk.js:2:128427)
    at Tu (https://editor.gdevelop-app.com/static/js/59.8473c3be.chunk.js:2:135463)
    at Eu (https://editor.gdevelop-app.com/static/js/59.8473c3be.chunk.js:2:134843)
    at gu (https://editor.gdevelop-app.com/static/js/59.8473c3be.chunk.js:2:133864)
    at qa (https://editor.gdevelop-app.com/static/js/59.8473c3be.chunk.js:2:132733)
    at Object.enqueueSetState (https://editor.gdevelop-app.com/static/js/59.8473c3be.chunk.js:2:82125)
    at Z.E.setState (https://editor.gdevelop-app.com/static/js/59.8473c3be.chunk.js:2:32410)
    at Z.openLayout (https://editor.gdevelop-app.com/static/js/1.ab0caea4.chunk.js:1:581069)
    at Z.openSceneOrProjectManager (https://editor.gdevelop-app.com/static/js/1.ab0caea4.chunk.js:1:589192)
    at https://editor.gdevelop-app.com/static/js/1.ab0caea4.chunk.js:1:597392
```

## Component stack (don't write anything here)
```

    in Unknown
    in Measure
    in E
    in o
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in m
    in a
    in div
    in Z
    in l
    in t
    in Unknown
    in div
    in m
    in div
    in Z
    in i
    in X
    in t
    in L
    in Unknown
    in t
    in c
    in z
    in i
    in u
    in DragDropContext(u)
    in Z
    in m
```

## Other details
* IDE version: 5.0.0-beta92-c000a735bb45d4f5db8007b27954172e6e5f1095
* Arch: Unknown architecture (web-app),
* Platform Name: Win32,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36,

**Comment by 4ian** [comment]
Thanks for reporting! I've wrongly deployed the latest update. This is now fixed, should be ok after clearing your cache, closing all the GDevelop tabs and restart it :)
