### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by UlisesFreitas** [4ian/GDevelop#1709]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
Error: No suitable position found to insert.
    at qt (file:///C:/Users/ulise/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.27513ed6.chunk.js:2:1609937)
    at file:///C:/Users/ulise/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.27513ed6.chunk.js:2:1615664
    at e.value (file:///C:/Users/ulise/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.27513ed6.chunk.js:2:1617735)
    at e.canDrop (file:///C:/Users/ulise/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.27513ed6.chunk.js:2:1109563)
    at e.canDropOnTarget (file:///C:/Users/ulise/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.27513ed6.chunk.js:2:1091235)
    at e.canDrop (file:///C:/Users/ulise/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.27513ed6.chunk.js:2:529389)
    at file:///C:/Users/ulise/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.27513ed6.chunk.js:2:1619171
    at c.getCurrentState (file:///C:/Users/ulise/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.27513ed6.chunk.js:2:519751)
    at file:///C:/Users/ulise/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.27513ed6.chunk.js:2:520121
    at Co (file:///C:/Users/ulise/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:106366)
    at Ua (file:///C:/Users/ulise/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:128043)
    at Fa (file:///C:/Users/ulise/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:128427)
    at Tu (file:///C:/Users/ulise/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:135463)
    at Eu (file:///C:/Users/ulise/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:134843)
    at gu (file:///C:/Users/ulise/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:133864)
    at qa (file:///C:/Users/ulise/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:132733)
    at Object.enqueueSetState (file:///C:/Users/ulise/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:82125)
    at t.E.setState (file:///C:/Users/ulise/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:32410)
    at t.value (file:///C:/Users/ulise/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.27513ed6.chunk.js:2:1624351)
    at Object.hover (file:///C:/Users/ulise/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.27513ed6.chunk.js:2:1618913)
    at e.hover (file:///C:/Users/ulise/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.27513ed6.chunk.js:2:1109653)
    at file:///C:/Users/ulise/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.27513ed6.chunk.js:2:1086309
    at e.<anonymous> (file:///C:/Users/ulise/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.27513ed6.chunk.js:2:1086321)
    at Object.keys.reduce.r.<computed> [as hover] (file:///C:/Users/ulise/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.27513ed6.chunk.js:2:1074879)
    at handleTopDragEnter (file:///C:/Users/ulise/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.27513ed6.chunk.js:2:1117650)
    at i (file:///C:/Users/ulise/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:350019)
```

## Component stack (don't write anything here)
```

    in DropTarget(t)
    in div
    in div
    in t
    in t
    in Scrolling(t)
    in div
    in t
    in div
    in t
    in ln
    in Unknown
    in O
    in div
    in w
    in div
    in l
    in a
    in o
    in F
    in l
    in t
    in Unknown
    in div
    in m
    in div
    in Z
    in i
    in X
    in t
    in L
    in Unknown
    in t
    in c
    in z
    in i
    in u
    in DragDropContext(u)
    in Z
    in m
```

## Other details
* IDE version: 5.0.0-beta92-124079c50f667d51f39866fbeee55ddbaa2db78f
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.17763,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta92 Chrome/80.0.3987.163 Electron/8.2.1 Safari/537.36,

**Comment by 4ian** [comment]
Would you have a list of steps to reproduce this bug?
