### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by miguelsouzaribeiro** [4ian/GDevelop#1781]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: n[q[((q[(a >> 2)] + 4) >> 2)]] is not a function
    at ra (file:///opt/gdevelop-5.0.0-beta92/resources/app.asar/www/libGD.js:21:2513)
    at SerializerElement.__destroy__.SerializerElement.__destroy__ (file:///opt/gdevelop-5.0.0-beta92/resources/app.asar/www/libGD.js:75:930741)
    at Object.destroy (file:///opt/gdevelop-5.0.0-beta92/resources/app.asar/www/libGD.js:75:711267)
    at SerializerElement.proto.delete (file:///opt/gdevelop-5.0.0-beta92/resources/app.asar/www/libGD.js:75:1241642)
    at o (file:///opt/gdevelop-5.0.0-beta92/resources/app.asar/www/static/js/1.dcfb7ca5.chunk.js:1:15081)
    at l.render (file:///opt/gdevelop-5.0.0-beta92/resources/app.asar/www/static/js/1.dcfb7ca5.chunk.js:1:698560)
    at To (file:///opt/gdevelop-5.0.0-beta92/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:100477)
    at ko (file:///opt/gdevelop-5.0.0-beta92/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:100270)
    at Co (file:///opt/gdevelop-5.0.0-beta92/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:104131)
    at Ua (file:///opt/gdevelop-5.0.0-beta92/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:128043)
    at Fa (file:///opt/gdevelop-5.0.0-beta92/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:128427)
    at Tu (file:///opt/gdevelop-5.0.0-beta92/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:135463)
    at Eu (file:///opt/gdevelop-5.0.0-beta92/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:134843)
    at Nu (file:///opt/gdevelop-5.0.0-beta92/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:136222)
    at Nn (file:///opt/gdevelop-5.0.0-beta92/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:67909)
    at HTMLDocument.i (file:///opt/gdevelop-5.0.0-beta92/resources/app.asar/www/static/js/59.06a7dabd.chunk.js:2:350019)
```

## Component stack (don't write anything here)
```

    in l
    in t
    in Unknown
    in div
    in m
    in div
    in Z
    in i
    in X
    in t
    in L
    in Unknown
    in t
    in c
    in z
    in i
    in u
    in DragDropContext(u)
    in Z
    in m
```

## Other details
* IDE version: 5.0.0-beta92-124079c50f667d51f39866fbeee55ddbaa2db78f
* Arch: x64,
* Platform Name: linux,
* System Version: 4.19.0-9-amd64,
* User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta92 Chrome/80.0.3987.163 Electron/8.2.1 Safari/537.36,

**Comment by Bouh** [comment]
@miguelsouzaribeiro did you remember what you doing when this crash has arrived ?
Without more details we will close this issue.

**Comment by Silver-Streak** [comment]
Closing this as no response for more detail after over 6 months.
