### ISSUE TITLE
Crash while using an editor in Resource editor.

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#1792]
Crash the resource editor when i select an resource in the list. 
Use **Remove unused images**.
The resource is deleted, and because the focus was on it, the resource editor crash.

[Crash in video](https://streamable.com/dwwghx)

Error stack (don't write anything here)
```
TypeError: n[q[((q[(w >> 2)] + 16) >> 2)]] is not a function
    at Ga (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.0-beta95-7ca5ef6e6ce4c47d1bc386e3239aae00e97aa05a:25:4336)
    at Resource.GetName.Resource.GetName [as getName] (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.0-beta95-7ca5ef6e6ce4c47d1bc386e3239aae00e97aa05a:75:719532)
    at T._renderPreview (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.bf36c65c.chunk.js:1:848997)
    at T.render (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.bf36c65c.chunk.js:1:849149)
    at To (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:100478)
    at ko (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:100271)
    at Co (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:104132)
    at Ua (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:128044)
    at Fa (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:128428)
    at Tu (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:135464)
    at Eu (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:134844)
    at gu (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:133865)
    at qa (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:132734)
    at to (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:93462)
    at file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.bf36c65c.chunk.js:1:312056
    at new Promise (<anonymous>)
    at file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.bf36c65c.chunk.js:1:312028
    at Gt (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.bf36c65c.chunk.js:1:552625)
    at file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.bf36c65c.chunk.js:1:550249
```

## Component stack (don't write anything here)
```

    in T
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in g
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in b
    in div
    in W
    in G
    in t
    in Unknown
    in div
    in m
    in div
    in Unknown
    in r
    in X
    in t
    in L
    in Unknown
    in t
    in c
    in z
    in r
    in u
    in DragDropContext(u)
    in Z
    in b
```

## Other details
* IDE version: 5.0.0-beta95-7ca5ef6e6ce4c47d1bc386e3239aae00e97aa05a
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.18363,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta95 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by 4ian** [comment]
Good spot! I'll make a fix :)

**Comment by 4ian** [comment]
Fixed for next version! :)
