### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Acox1411** [4ian/GDevelop#1887]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
Error: Failed to execute 'createPattern' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at t._renderCanvas (file:///C:/Users/acox24/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.caa2dc8e.chunk.js:2:1256370)
    at t.renderCanvas (file:///C:/Users/acox24/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.caa2dc8e.chunk.js:2:197503)
    at t.renderCanvas (file:///C:/Users/acox24/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.caa2dc8e.chunk.js:2:197580)
    at t.renderCanvas (file:///C:/Users/acox24/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.caa2dc8e.chunk.js:2:197580)
    at t.renderCanvas (file:///C:/Users/acox24/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.caa2dc8e.chunk.js:2:197580)
    at t.renderCanvas (file:///C:/Users/acox24/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.caa2dc8e.chunk.js:2:197580)
    at t.renderCanvas (file:///C:/Users/acox24/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.caa2dc8e.chunk.js:2:197580)
    at t.render (file:///C:/Users/acox24/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.caa2dc8e.chunk.js:2:201041)
    at L._renderScene (file:///C:/Users/acox24/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.bf36c65c.chunk.js:1:761298)
    at L._initializeCanvasAndRenderer (file:///C:/Users/acox24/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.bf36c65c.chunk.js:1:764890)
    at L.componentDidMount (file:///C:/Users/acox24/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.bf36c65c.chunk.js:1:761705)
    at Ra (file:///C:/Users/acox24/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:119766)
    at ja (file:///C:/Users/acox24/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:122689)
    at file:///C:/Users/acox24/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:135789
    at Object.t.unstable_runWithPriority (file:///C:/Users/acox24/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:146556)
    at Su (file:///C:/Users/acox24/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:135723)
    at Tu (file:///C:/Users/acox24/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:135499)
    at Eu (file:///C:/Users/acox24/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:134844)
    at Nu (file:///C:/Users/acox24/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:136223)
    at Nn (file:///C:/Users/acox24/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:67910)
    at HTMLDocument.i (file:///C:/Users/acox24/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.34953d72.chunk.js:2:350020)
```

## Component stack (don't write anything here)
```

    in L
    in div
    in div
    in Unknown
    in Measure
    in r
    in o
    in m
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in b
    in a
    in div
    in H
    in r
    in t
    in Unknown
    in div
    in m
    in div
    in Unknown
    in r
    in X
    in t
    in L
    in Unknown
    in t
    in c
    in z
    in r
    in u
    in DragDropContext(u)
    in Z
    in b
```

## Other details
* IDE version: 5.0.0-beta95-7ca5ef6e6ce4c47d1bc386e3239aae00e97aa05a
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.18363,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta95 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by Bouh** [comment]
Hi thank you for this report, can you help us and explain what you did before the crash ?
In the meanwhile the error show an message about an image of 0px wide.
Can you open the ressource tabs in the project manager and check is all your image are correctly shown ?

Thank you!
