### ISSUE TITLE
Crash while using an editor, (Auto report. Was editing an animation at the time)

### ISSUE THREAD

**Issue by NomadicVoxel** [4ian/GDevelop#1900]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: n[q[((q[(w >> 2)] + 16) >> 2)]] is not a function
    at Ca (file:///C:/Users/nomad_bl4pf4k/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.0-beta97-e8a1af0ef1d81d3689fe139bcb8a06dd3447e239:21:4321)
    at Resource.GetName.Resource.GetName [as getName] (file:///C:/Users/nomad_bl4pf4k/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.0-beta97-e8a1af0ef1d81d3689fe139bcb8a06dd3447e239:75:719834)
    at C (file:///C:/Users/nomad_bl4pf4k/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.11f14b12.chunk.js:1:306706)
    at v._renderItemRow (file:///C:/Users/nomad_bl4pf4k/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.11f14b12.chunk.js:1:518526)
    at file:///C:/Users/nomad_bl4pf4k/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.11f14b12.chunk.js:1:519756
    at file:///C:/Users/nomad_bl4pf4k/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.11f14b12.chunk.js:1:610610
    at Wi (file:///C:/Users/nomad_bl4pf4k/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.6a30eaaa.chunk.js:2:90462)
    at Co (file:///C:/Users/nomad_bl4pf4k/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.6a30eaaa.chunk.js:2:102773)
    at Ua (file:///C:/Users/nomad_bl4pf4k/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.6a30eaaa.chunk.js:2:128044)
    at Fa (file:///C:/Users/nomad_bl4pf4k/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.6a30eaaa.chunk.js:2:128428)
    at Tu (file:///C:/Users/nomad_bl4pf4k/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.6a30eaaa.chunk.js:2:135464)
    at Eu (file:///C:/Users/nomad_bl4pf4k/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.6a30eaaa.chunk.js:2:134844)
    at Iu (file:///C:/Users/nomad_bl4pf4k/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.6a30eaaa.chunk.js:2:135940)
    at Ue (file:///C:/Users/nomad_bl4pf4k/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.6a30eaaa.chunk.js:2:47510)
    at On (file:///C:/Users/nomad_bl4pf4k/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.6a30eaaa.chunk.js:2:68168)
    at HTMLDocument.i (file:///C:/Users/nomad_bl4pf4k/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.6a30eaaa.chunk.js:2:350020)
```

## Component stack (don't write anything here)
```

    in Unknown
    in DropTarget(Component)
    in DragSource(DropTarget(Component))
    in Unknown
    in div
    in div
    in div
    in t
    in t
    in o
    in a
    in v
    in div
    in t
    in div
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in x
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in b
    in div
    in x
    in r
    in t
    in Unknown
    in div
    in m
    in div
    in Unknown
    in r
    in i
    in X
    in t
    in L
    in Unknown
    in t
    in c
    in z
    in r
    in u
    in DragDropContext(u)
    in Q
    in b
```

## Other details
* IDE version: 5.0.0-beta97-e8a1af0ef1d81d3689fe139bcb8a06dd3447e239
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19041,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta97 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by Silver-Streak** [comment]
Are you still getting this crash?
If so, can you list out the steps to reproduce the crash?

(This issue will be closed out if no response within 30 days)

**Comment by Silver-Streak** [comment]
Closed due to no steps to reproduce the issue and no response.
