### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Naufalgaming2018-dev** [4ian/GDevelop#1941]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

Short Description:
So, when I try to insert an animation into the sprite, at first it is fine. And I want to try to update my animation. So I immediately delete the animation from the Sprite and I try to reopen it with "open Recent" and without saving it first (because I think that's the quickest and my own way for deleting some unused sprites), and it turns out that in the scene Cordinate there was an error (i think it say NaN or something) and all other objects I put it in the scene is gone  (but i can still see the object in the Object Window or something). and when I try to insert some object into the scene, it says error and an automatic report

## Error stack (don't write anything here)
```
SyntaxError: Unexpected token a in JSON at position 7002
    at JSON.parse (<anonymous>)
    at o (file:///D:/8-bit%20Game%20Maker%20Aplication/GDevelop.5-5.0.0-beta97-pixi-v5-win/resources/app.asar/www/static/js/1.ecfca78d.chunk.js:1:18602)
    at i (file:///D:/8-bit%20Game%20Maker%20Aplication/GDevelop.5-5.0.0-beta97-pixi-v5-win/resources/app.asar/www/static/js/1.ecfca78d.chunk.js:1:609905)
    at H._addInstance (file:///D:/8-bit%20Game%20Maker%20Aplication/GDevelop.5-5.0.0-beta97-pixi-v5-win/resources/app.asar/www/static/js/1.ecfca78d.chunk.js:1:649189)
    at H._addInstanceForNewObject (file:///D:/8-bit%20Game%20Maker%20Aplication/GDevelop.5-5.0.0-beta97-pixi-v5-win/resources/app.asar/www/static/js/1.ecfca78d.chunk.js:1:650427)
    at V.<anonymous> (file:///D:/8-bit%20Game%20Maker%20Aplication/GDevelop.5-5.0.0-beta97-pixi-v5-win/resources/app.asar/www/static/js/1.ecfca78d.chunk.js:1:873731)
    at Jo (file:///D:/8-bit%20Game%20Maker%20Aplication/GDevelop.5-5.0.0-beta97-pixi-v5-win/resources/app.asar/www/static/js/59.6a30eaaa.chunk.js:2:110332)
    at $o (file:///D:/8-bit%20Game%20Maker%20Aplication/GDevelop.5-5.0.0-beta97-pixi-v5-win/resources/app.asar/www/static/js/59.6a30eaaa.chunk.js:2:110081)
    at Ra (file:///D:/8-bit%20Game%20Maker%20Aplication/GDevelop.5-5.0.0-beta97-pixi-v5-win/resources/app.asar/www/static/js/59.6a30eaaa.chunk.js:2:119967)
    at ja (file:///D:/8-bit%20Game%20Maker%20Aplication/GDevelop.5-5.0.0-beta97-pixi-v5-win/resources/app.asar/www/static/js/59.6a30eaaa.chunk.js:2:122689)
    at file:///D:/8-bit%20Game%20Maker%20Aplication/GDevelop.5-5.0.0-beta97-pixi-v5-win/resources/app.asar/www/static/js/59.6a30eaaa.chunk.js:2:135789
    at Object.t.unstable_runWithPriority (file:///D:/8-bit%20Game%20Maker%20Aplication/GDevelop.5-5.0.0-beta97-pixi-v5-win/resources/app.asar/www/static/js/59.6a30eaaa.chunk.js:2:146556)
    at Su (file:///D:/8-bit%20Game%20Maker%20Aplication/GDevelop.5-5.0.0-beta97-pixi-v5-win/resources/app.asar/www/static/js/59.6a30eaaa.chunk.js:2:135723)
    at Tu (file:///D:/8-bit%20Game%20Maker%20Aplication/GDevelop.5-5.0.0-beta97-pixi-v5-win/resources/app.asar/www/static/js/59.6a30eaaa.chunk.js:2:135499)
    at Eu (file:///D:/8-bit%20Game%20Maker%20Aplication/GDevelop.5-5.0.0-beta97-pixi-v5-win/resources/app.asar/www/static/js/59.6a30eaaa.chunk.js:2:134844)
    at Nu (file:///D:/8-bit%20Game%20Maker%20Aplication/GDevelop.5-5.0.0-beta97-pixi-v5-win/resources/app.asar/www/static/js/59.6a30eaaa.chunk.js:2:136223)
    at Nn (file:///D:/8-bit%20Game%20Maker%20Aplication/GDevelop.5-5.0.0-beta97-pixi-v5-win/resources/app.asar/www/static/js/59.6a30eaaa.chunk.js:2:67910)
    at HTMLDocument.i (file:///D:/8-bit%20Game%20Maker%20Aplication/GDevelop.5-5.0.0-beta97-pixi-v5-win/resources/app.asar/www/static/js/59.6a30eaaa.chunk.js:2:350020)
```

## Component stack (don't write anything here)
```

    in V
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in g
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in b
    in a
    in div
    in H
    in r
    in t
    in Unknown
    in div
    in m
    in div
    in Unknown
    in r
    in i
    in X
    in t
    in L
    in Unknown
    in t
    in c
    in z
    in r
    in u
    in DragDropContext(u)
    in Q
    in b
```

## Other details
* IDE version: 5.0.0-beta97-pixi-v5-d6c5a541772a7d1a23660ad5524d40deae9228b1
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.18363,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta97-pixi-v5 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by Silver-Streak** [comment]
Are you still getting this crash?
If so, can you list out the steps to reproduce the crash, I tried a reloading from recent a bunch of times, including after deleting a sprite, and I cannot get it to crash.

(This issue will be closed out if no response within 30 days)

**Comment by Silver-Streak** [comment]
Closed due to lack of steps to reproduce and no response.
