### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by kengaing** [4ian/GDevelop#1964]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
SyntaxError: Unexpected token n in JSON at position 172
    at JSON.parse (<anonymous>)
    at r (file:///C:/Users/jc%20secretario/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.a1df63fd.chunk.js:1:22057)
    at o (file:///C:/Users/jc%20secretario/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.a1df63fd.chunk.js:1:723618)
    at new n (file:///C:/Users/jc%20secretario/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.a1df63fd.chunk.js:1:774197)
    at ci (file:///C:/Users/jc%20secretario/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.31b0fbbe.chunk.js:2:78804)
    at ko (file:///C:/Users/jc%20secretario/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.31b0fbbe.chunk.js:2:93601)
    at Co (file:///C:/Users/jc%20secretario/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.31b0fbbe.chunk.js:2:100116)
    at Ua (file:///C:/Users/jc%20secretario/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.31b0fbbe.chunk.js:2:124028)
    at Fa (file:///C:/Users/jc%20secretario/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.31b0fbbe.chunk.js:2:124412)
    at Tu (file:///C:/Users/jc%20secretario/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.31b0fbbe.chunk.js:2:131448)
    at Eu (file:///C:/Users/jc%20secretario/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.31b0fbbe.chunk.js:2:130828)
    at Ou (file:///C:/Users/jc%20secretario/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.31b0fbbe.chunk.js:2:132207)
    at On (file:///C:/Users/jc%20secretario/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.31b0fbbe.chunk.js:2:63894)
    at HTMLDocument.i (file:///C:/Users/jc%20secretario/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.31b0fbbe.chunk.js:2:357943)
```

## Component stack (don't write anything here)
```

    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in s
    in n
    in t
    in n
    in Unknown
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta100-23d64aa676eaf789ce31d5176b23f212f3b8031d
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.18363,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta100 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by 4ian** [comment]
Closing as not enough information to fix this unfortunately.
