### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by HUSSAIN-SUDO17** [4ian/GDevelop#2089]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
Error: Failed to execute 'createPattern' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at t.Ni._renderCanvas (file:///C:/Users/Royal%20Inn%20pc%202/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.c4de31ae.chunk.js:2:400131)
    at t.dt.renderCanvas (file:///C:/Users/Royal%20Inn%20pc%202/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.c4de31ae.chunk.js:2:401832)
    at t.dt.renderCanvas (file:///C:/Users/Royal%20Inn%20pc%202/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.c4de31ae.chunk.js:2:401909)
    at t.dt.renderCanvas (file:///C:/Users/Royal%20Inn%20pc%202/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.c4de31ae.chunk.js:2:401909)
    at t.dt.renderCanvas (file:///C:/Users/Royal%20Inn%20pc%202/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.c4de31ae.chunk.js:2:401909)
    at t.dt.renderCanvas (file:///C:/Users/Royal%20Inn%20pc%202/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.c4de31ae.chunk.js:2:401909)
    at t.dt.renderCanvas (file:///C:/Users/Royal%20Inn%20pc%202/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.c4de31ae.chunk.js:2:401909)
    at t.render (file:///C:/Users/Royal%20Inn%20pc%202/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.c4de31ae.chunk.js:2:382360)
    at n.e._renderScene (file:///C:/Users/Royal%20Inn%20pc%202/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.6e5f532f.chunk.js:1:935916)
    at n.value (file:///C:/Users/Royal%20Inn%20pc%202/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.6e5f532f.chunk.js:1:939722)
    at n.value (file:///C:/Users/Royal%20Inn%20pc%202/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.6e5f532f.chunk.js:1:936287)
    at Ra (file:///C:/Users/Royal%20Inn%20pc%202/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.5e68a084.chunk.js:2:121720)
    at ja (file:///C:/Users/Royal%20Inn%20pc%202/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.5e68a084.chunk.js:2:124643)
    at file:///C:/Users/Royal%20Inn%20pc%202/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.5e68a084.chunk.js:2:137743
    at Object.t.unstable_runWithPriority (file:///C:/Users/Royal%20Inn%20pc%202/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.5e68a084.chunk.js:2:148510)
    at Su (file:///C:/Users/Royal%20Inn%20pc%202/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.5e68a084.chunk.js:2:137677)
    at Tu (file:///C:/Users/Royal%20Inn%20pc%202/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.5e68a084.chunk.js:2:137453)
    at Eu (file:///C:/Users/Royal%20Inn%20pc%202/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.5e68a084.chunk.js:2:136798)
    at gu (file:///C:/Users/Royal%20Inn%20pc%202/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.5e68a084.chunk.js:2:135819)
    at qa (file:///C:/Users/Royal%20Inn%20pc%202/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.5e68a084.chunk.js:2:134688)
    at to (file:///C:/Users/Royal%20Inn%20pc%202/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.5e68a084.chunk.js:2:95416)
    at file:///C:/Users/Royal%20Inn%20pc%202/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.6e5f532f.chunk.js:1:350080
    at new Promise (<anonymous>)
    at file:///C:/Users/Royal%20Inn%20pc%202/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.6e5f532f.chunk.js:1:350043
    at file:///C:/Users/Royal%20Inn%20pc%202/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.6e5f532f.chunk.js:1:680616
    at file:///C:/Users/Royal%20Inn%20pc%202/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.6e5f532f.chunk.js:1:683484
    at file:///C:/Users/Royal%20Inn%20pc%202/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.6e5f532f.chunk.js:1:698968
```

## Component stack (don't write anything here)
```

    in n
    in div
    in div
    in Unknown
    in Measure
    in i
    in r
    in n
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in a
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in h
    in h
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta101-f0392cfede2c8b68b2c9d652001d999eac819299
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19042,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta101 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by Bouh** [comment]
Seem come from Line 102 here in PixiJS :
https://github.com/pixijs/pixi.js/blob/20d38ac10efff90a3f25d9401c2489375a656a75/packages/canvas/canvas-renderer/src/canvasUtils.ts#L83-L107
