### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#2218]
Something went wrong with the object groups. I recently converted object groups that were in several scenes (_obstacles_ and _sols_) to global groups.
![image](https://user-images.githubusercontent.com/25978830/104762388-8edb1280-5764-11eb-928b-5a3ce710018c.png)
(That text is from a function I use).
I right-clicked and chose edit group, and unsurprisingly, the editor crashed.
After reloading GDevelop, it seems fine.
![image](https://user-images.githubusercontent.com/25978830/104762576-e0839d00-5764-11eb-9507-8673fcd0b69d.png)

## Error stack (don't write anything here)
```
TypeError: n[q[((q[(a >> 2)] + 4) >> 2)]] is not a function
    at pa (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.0-beta103-139d0a6cea1463b7cd23a934f6947a129e54bcfa:25:2550)
    at InitialInstanceJSFunctor.__destroy__.InitialInstanceJSFunctor.__destroy__ (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.0-beta103-139d0a6cea1463b7cd23a934f6947a129e54bcfa:75:1241745)
    at Object.destroy (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.0-beta103-139d0a6cea1463b7cd23a934f6947a129e54bcfa:75:754554)
    at InitialInstanceJSFunctor.proto.delete (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.0-beta103-139d0a6cea1463b7cd23a934f6947a129e54bcfa:75:1317567)
    at e.value (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.55966cf4.chunk.js:1:246974)
    at n.value (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.55966cf4.chunk.js:1:996615)
    at aa (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:115185)
    at la (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:116759)
    at Aa (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:120911)
    at ja (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:124474)
    at file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:137743
    at Object.t.unstable_runWithPriority (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:148510)
    at Su (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:137677)
    at Tu (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:137453)
    at Eu (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:136798)
    at gu (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:135819)
    at qa (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:134688)
    at Object.enqueueSetState (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:84080)
    at n.E.setState (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:34365)
    at Object.o.editGroup [as onEditGroup] (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.55966cf4.chunk.js:1:844006)
    at Object.d.a.createElement.onEdit (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.55966cf4.chunk.js:1:1146109)
    at click (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.55966cf4.chunk.js:1:1144301)
    at CallbacksRegistry.apply (electron/js2c/renderer_init.js:2549:29)
    at electron/js2c/renderer_init.js:1469:21
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:1449:7)
    at EventEmitter.emit (events.js:210:5)
    at Object.onMessage (electron/js2c/renderer_init.js:2204:16)
```

## Component stack (don't write anything here)
```

    in n
    in div
    in div
    in Unknown
    in Measure
    in i
    in r
    in n
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in l
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in p
    in p
    in p
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in p
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta103-139d0a6cea1463b7cd23a934f6947a129e54bcfa
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.18363,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta103 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by Bouh** [comment]
More details are welcome, i can't reproduce the crash or the bug with the names in Objects group list.

**Comment by Silver-Streak** [comment]
@PascalLadalle Are you still getting this? I was looking through old posts and can't reproduce this today.

**Comment by PascalLadalle** [comment]
This was a one-time thing.
But I don't often convert object groups to global, I'm still on the same game 😅
