### ISSUE TITLE
Crash while using an editor - clipboard

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop#2222]
I copy-pasted a block of events to the forum, and then I selected it, copied it to the clipboard, and the editor crashes as soon as I right-click where I want to paste it.
The issue does not seem to occur with Github. I suppose the forum is converting the quotes.
Either way, the editor should not crash, whatever the content of the clipboard, right?

Clipboard content:
> {"000kind":"GDEVELOP_EventsAndInstructions_CLIPBOARD_KIND-jsBdHbLy912y8Rc","content":{"eventsList":[{"disabled":false,"folded":false,"type":"BuiltinCommonInstructions::Standard","conditions":[],"actions":[],"events":[{"disabled":false,"folded":false,"type":"BuiltinCommonInstructions::ForEach","object":"b","conditions":[{"type":{"inverted":false,"value":"BuiltinCommonInstructions::Once"},"parameters":[],"subInstructions":[]}],"actions":[],"events":[{"disabled":false,"folded":false,"type":"BuiltinCommonInstructions::Repeat","repeatExpression":"3","conditions":[],"actions":[{"type":{"inverted":false,"value":"Create"},"parameters":["","a","0","0",""],"subInstructions":[]},{"type":{"inverted":false,"value":"MettreAutour"},"parameters":["a","b","60","Variable(angle)"],"subInstructions":[]},{"type":{"inverted":false,"value":"ModVarObjet"},"parameters":["a","initialangle","=","Variable(angle)"],"subInstructions":[]},{"type":{"inverted":false,"value":"ModVarScene"},"parameters":["angle","+","120"],"subInstructions":[]},{"type":{"inverted":false,"value":"LinkedObjects::LinkObjects"},"parameters":["","a","b"],"subInstructions":[]}],"events":[]}]},{"disabled":false,"folded":false,"type":"BuiltinCommonInstructions::ForEach","object":"a","conditions":[],"actions":[],"events":[{"disabled":false,"folded":false,"type":"BuiltinCommonInstructions::Standard","conditions":[{"type":{"inverted":false,"value":"BuiltinCommonInstructions::Once"},"parameters":[],"subInstructions":[]}],"actions":[{"type":{"inverted":false,"value":"ModVarObjet"},"parameters":["a","motionangle","=","a.Variable(initialangle)"],"subInstructions":[]}],"events":[]},{"disabled":false,"folded":false,"type":"BuiltinCommonInstructions::Standard","conditions":[],"actions":[{"type":{"inverted":false,"value":"LinkedObjects::PickObjectsLinkedTo"},"parameters":["","b","a"],"subInstructions":[]},{"type":{"inverted":false,"value":"MettreAutour"},"parameters":["a","b","60","a.Variable(motionangle)"],"subInstructions":[]},{"type":{"inverted":false,"value":"ModVarObjet"},"parameters":["a","motionangle","+","0.3"],"subInstructions":[]}],"events":[]}]}]}],"eventsCount":1,"actionsList":[],"actionsCount":0,"conditionsList":[],"conditionsCount":0}}

## Error stack (don't write anything here)
```
TypeError: Cannot read property 'eventsCount' of null
    at c (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.55966cf4.chunk.js:1:787259)
    at Object.buildMenuTemplate (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.55966cf4.chunk.js:1:694547)
    at n.open (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.55966cf4.chunk.js:1:615029)
    at Object.open (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.55966cf4.chunk.js:1:615395)
    at n.<anonymous> (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.55966cf4.chunk.js:1:682545)
    at Jo (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:112286)
    at $o (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:112035)
    at Ra (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:121921)
    at ja (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:124643)
    at file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:137743
    at Object.t.unstable_runWithPriority (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:148510)
    at Su (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:137677)
    at Tu (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:137453)
    at Eu (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:136798)
    at Nu (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:138177)
    at Nn (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:69864)
    at HTMLDocument.i (file:///C:/Users/Lutin/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:351973)
```

## Component stack (don't write anything here)
```

    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in p
    in p
    in p
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in p
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta103-139d0a6cea1463b7cd23a934f6947a129e54bcfa
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.18363,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta103 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by PascalLadalle** [comment]
Got the lucky number 🍀 😁

**Comment by 4ian** [comment]
> The issue does not seem to occur with Github. I suppose the forum is converting the quotes.

Yeah might be because of that! Could you send me a link in the forum?

I've at least fixed the clipboard handling so that no crash can happen, even if the content "looks correct" but is actually not :) Thanks for reporting.

**Comment by PascalLadalle** [comment]
https://forum.gdevelop-app.com/t/improve-sharing-of-events-bbcode-on-forum/29864/2?u=gruk
