### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Keerat-Singh** [4ian/GDevelop#2247]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: Cannot read property 'eventsCount' of null
    at c (file:///C:/Users/keera/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.55966cf4.chunk.js:1:787259)
    at Object.buildMenuTemplate (file:///C:/Users/keera/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.55966cf4.chunk.js:1:694547)
    at n.open (file:///C:/Users/keera/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.55966cf4.chunk.js:1:615029)
    at Object.open (file:///C:/Users/keera/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.55966cf4.chunk.js:1:615395)
    at n.<anonymous> (file:///C:/Users/keera/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.55966cf4.chunk.js:1:682545)
    at Jo (file:///C:/Users/keera/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:112286)
    at $o (file:///C:/Users/keera/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:112035)
    at Ra (file:///C:/Users/keera/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:121921)
    at ja (file:///C:/Users/keera/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:124643)
    at file:///C:/Users/keera/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:137743
    at Object.t.unstable_runWithPriority (file:///C:/Users/keera/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:148510)
    at Su (file:///C:/Users/keera/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:137677)
    at Tu (file:///C:/Users/keera/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:137453)
    at Eu (file:///C:/Users/keera/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:136798)
    at Nu (file:///C:/Users/keera/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:138177)
    at Nn (file:///C:/Users/keera/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:69864)
    at HTMLDocument.i (file:///C:/Users/keera/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.7445f905.chunk.js:2:351973)
```

## Component stack (don't write anything here)
```

    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in p
    in p
    in p
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in p
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta103-139d0a6cea1463b7cd23a934f6947a129e54bcfa
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19042,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta103 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by 4ian** [comment]
This is due to bad data in the clipboard and should be fixed for next version.
