### ISSUE TITLE
Game Showcase crash the app

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop#2283]
The game engine crash when we go too fast in the game showcase at the loading, the data are not yet loaded and the app crash.

-------------

## Error stack (don't write anything here)
```
TypeError: Cannot use 'in' operator to search for 'message' in 5
    at u (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.833fa38f.chunk.js:2:1026334)
    at Function.x.parse (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.833fa38f.chunk.js:2:1020909)
    at y (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.833fa38f.chunk.js:2:1018476)
    at qi (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.bb9b06a4.chunk.js:2:104039)
    at Co (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.bb9b06a4.chunk.js:2:116350)
    at Ua (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.bb9b06a4.chunk.js:2:141621)
    at Fa (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.bb9b06a4.chunk.js:2:142005)
    at Tu (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.bb9b06a4.chunk.js:2:149041)
    at Eu (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.bb9b06a4.chunk.js:2:148421)
    at gu (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.bb9b06a4.chunk.js:2:147442)
    at Da (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.bb9b06a4.chunk.js:2:134198)
    at La (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.bb9b06a4.chunk.js:2:134275)
    at to (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.bb9b06a4.chunk.js:2:106663)
    at file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.a18a37b0.chunk.js:1:891540
    at u (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.833fa38f.chunk.js:2:965333)
    at Generator._invoke (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.833fa38f.chunk.js:2:965086)
    at Generator.next (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.833fa38f.chunk.js:2:965692)
    at r (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.833fa38f.chunk.js:2:350587)
    at s (file:///C:/Users/RTX-Bouh/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.833fa38f.chunk.js:2:350790)
```

## Component stack (don't write anything here)
```

    in y
    in l
    in span
    in ForwardRef
    in ForwardRef
    in Unknown
    in div
    in i
    in div
    in o
    in div
    in o
    in u
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in div
    in ne
    in div
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in Unknown
    in d
    in div
    in o
    in div
    in i
    in u
    in se
    in div
    in i
    in div
    in ForwardRef
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in E
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in u
    in Unknown
    in n
    in div
    in Unknown
    in n
    in p
    in p
    in p
    in p
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in p
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta105-414e825a58af5b5d709e64a43aa2718489a48475
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19041,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta105 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by 4ian** [comment]
Super weird. Can you somehow reproduce this in development?

**Comment by Bouh** [comment]
In dev branch with lastest commit Feb 7, 2021  0fe4371418cdc8fda8fa566a3583d804910dedf1



[localhost-1612704465029.log](https://github.com/4ian/GDevelop/files/5939061/localhost-1612704465029.log)


https://user-images.githubusercontent.com/1670670/107147897-c480af00-6950-11eb-979b-f874c25d7d10.mp4

**Comment by 4ian** [comment]
It's probably due to a game that was approved and that has wrong data or unsupported, I've removed the latest approved games and we'll see if it's better.

**Comment by 4ian** [comment]
Ok found the issue! :) 
![image](https://user-images.githubusercontent.com/1280130/107155757-1980ed00-6972-11eb-8bc0-d9ed433c30ea.png)

Script is wrongly parsing fields with numbers at the beginning as numbers 😬 Will fix it :)

**Comment by 4ian** [comment]
Fixed, the script should now be resilient against bad data types.
