### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by giorgioooo9** [4ian/GDevelop#2451]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: this._instance.getRawFloatProperty is not a function
    at i.updateSprite (https://editor.gdevelop-app.com/static/js/1.926b1a1d.chunk.js:1:684471)
    at i.updatePIXITexture (https://editor.gdevelop-app.com/static/js/1.926b1a1d.chunk.js:1:685106)
    at new i (https://editor.gdevelop-app.com/static/js/1.926b1a1d.chunk.js:1:683083)
    at Object.createNewInstanceRenderer (https://editor.gdevelop-app.com/static/js/1.926b1a1d.chunk.js:1:43483)
    at e.getRendererOfInstance (https://editor.gdevelop-app.com/static/js/1.926b1a1d.chunk.js:1:828204)
    at InitialInstanceJSFunctor.instancesRenderer.invoke (https://editor.gdevelop-app.com/static/js/1.926b1a1d.chunk.js:1:829486)
    at 8556 (https://editor.gdevelop-app.com/libGD.js?cache-buster=5.0.0-beta101-ae8a26b3f95d26fcfb74317fba89c87d320985b0:9:18843)
    at _emscripten_asm_const_iii (https://editor.gdevelop-app.com/libGD.js?cache-buster=5.0.0-beta101-ae8a26b3f95d26fcfb74317fba89c87d320985b0:9:28312)
    at https://editor.gdevelop-app.com/libGD.wasm:wasm-function[1634]:0x40c0e
    at emscripten_bind_PropertyDescriptor_UnserializeFrom_1 (https://editor.gdevelop-app.com/libGD.wasm:wasm-function[80]:0x1d911)
    at https://editor.gdevelop-app.com/libGD.wasm:wasm-function[2392]:0x749ce
    at emscripten_bind_InitialInstancesContainer_IterateOverInstancesWithZOrdering_2 (https://editor.gdevelop-app.com/libGD.wasm:wasm-function[1107]:0x2fcc2)
    at Module._emscripten_bind_InitialInstancesContainer_IterateOverInstancesWithZOrdering_2 (https://editor.gdevelop-app.com/libGD.js?cache-buster=5.0.0-beta101-ae8a26b3f95d26fcfb74317fba89c87d320985b0:9:583183)
    at InitialInstancesContainer.IterateOverInstancesWithZOrdering.InitialInstancesContainer.IterateOverInstancesWithZOrdering [as iterateOverInstancesWithZOrdering] (https://editor.gdevelop-app.com/libGD.js?cache-buster=5.0.0-beta101-ae8a26b3f95d26fcfb74317fba89c87d320985b0:9:1199041)
    at e.value (https://editor.gdevelop-app.com/static/js/1.926b1a1d.chunk.js:1:830337)
    at e.value (https://editor.gdevelop-app.com/static/js/1.926b1a1d.chunk.js:1:456517)
    at n.e._renderScene (https://editor.gdevelop-app.com/static/js/1.926b1a1d.chunk.js:1:478403)
    at n.value (https://editor.gdevelop-app.com/static/js/1.926b1a1d.chunk.js:1:482390)
    at n.value (https://editor.gdevelop-app.com/static/js/1.926b1a1d.chunk.js:1:478955)
    at Ra (https://editor.gdevelop-app.com/static/js/59.8dc1fccd.chunk.js:2:121720)
    at ja (https://editor.gdevelop-app.com/static/js/59.8dc1fccd.chunk.js:2:124643)
    at https://editor.gdevelop-app.com/static/js/59.8dc1fccd.chunk.js:2:137743
    at Object.t.unstable_runWithPriority (https://editor.gdevelop-app.com/static/js/59.8dc1fccd.chunk.js:2:148510)
    at Su (https://editor.gdevelop-app.com/static/js/59.8dc1fccd.chunk.js:2:137677)
    at Tu (https://editor.gdevelop-app.com/static/js/59.8dc1fccd.chunk.js:2:137453)
    at Eu (https://editor.gdevelop-app.com/static/js/59.8dc1fccd.chunk.js:2:136798)
    at gu (https://editor.gdevelop-app.com/static/js/59.8dc1fccd.chunk.js:2:135819)
    at qa (https://editor.gdevelop-app.com/static/js/59.8dc1fccd.chunk.js:2:134688)
    at to (https://editor.gdevelop-app.com/static/js/59.8dc1fccd.chunk.js:2:95416)
    at https://editor.gdevelop-app.com/static/js/1.926b1a1d.chunk.js:1:947940
    at new Promise (<anonymous>)
    at https://editor.gdevelop-app.com/static/js/1.926b1a1d.chunk.js:1:947903
    at https://editor.gdevelop-app.com/static/js/1.926b1a1d.chunk.js:1:224470
    at https://editor.gdevelop-app.com/static/js/1.926b1a1d.chunk.js:1:227338
    at https://editor.gdevelop-app.com/static/js/1.926b1a1d.chunk.js:1:228451
```

## Component stack (don't write anything here)
```

    in n
    in div
    in div
    in Unknown
    in Measure
    in i
    in r
    in n
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in l
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in h
    in h
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta101-ae8a26b3f95d26fcfb74317fba89c87d320985b0
* Arch: Unknown architecture (web-app),
* Platform Name: Win32,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36,

**Comment by 4ian** [comment]
Should be fixed by closing the tab and re-opening again to let the app auto update itself.
