### ISSUE TITLE
Crash lors de l’utilisation d’un éditeur

### ISSUE THREAD

**Issue by Adriencreateur** [4ian/GDevelop#2452]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at la (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:128659)
    at Aa (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:132534)
    at ja (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:136097)
    at https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:149366
    at Object.t.unstable_runWithPriority (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:160133)
    at Su (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:149300)
    at Tu (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:149076)
    at Eu (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:148421)
    at gu (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:147442)
    at Wa (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:146311)
    at to (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:107039)
    at https://editor.gdevelop-app.com/static/js/1.6bbb4db3.chunk.js:1:641190
```

## Component stack (don't write anything here)
```

    in n
    in p
    in ForwardRef
    in ForwardRef
    in Unknown
    in div
    in i
    in div
    in o
    in div
    in button
    in ForwardRef
    in ForwardRef
    in j
    in div
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in Unknown
    in d
    in div
    in o
    in div
    in i
    in u
    in G
    in div
    in i
    in div
    in ForwardRef
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in E
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in u
    in Unknown
    in t
    in A
    in div
    in n
    in div
    in ForwardRef
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in E
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in u
    in Unknown
    in C
    in n
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in p
    in p
    in p
    in p
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in p
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta106-fa15276ffa2cb57a53b49d6c154148338ff9f068
* Arch: Unknown architecture (web-app),
* Platform Name: Win32,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 Edg/89.0.774.54,

**Comment by 4ian** [comment]
Interesting, are you able to give some steps to reproduce this crash?

**Comment by Silver-Streak** [comment]
Closing due to more info needed and no response from original poster in over 30 days.
