### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by OziasFilipe** [4ian/GDevelop#2493]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
RuntimeError: memory access out of bounds
    at wasm-function[251]:0x1f807
    at Variable.GetType.Variable.GetType [as getType] (file:///C:/Users/PC-User/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.0-beta108-1640ca49d72bfb4c97bc4a6c6fd5f8b4ee5bae18:9:1150836)
    at n.value (file:///C:/Users/PC-User/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.d9c43286.chunk.js:1:776123)
    at file:///C:/Users/PC-User/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.d9c43286.chunk.js:1:778492
    at n (file:///C:/Users/PC-User/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.d9c43286.chunk.js:1:994432)
    at n.value (file:///C:/Users/PC-User/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.d9c43286.chunk.js:1:778423)
    at To (file:///C:/Users/PC-User/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:114055)
    at ko (file:///C:/Users/PC-User/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:113848)
    at Co (file:///C:/Users/PC-User/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:117709)
    at Ua (file:///C:/Users/PC-User/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:141621)
    at Fa (file:///C:/Users/PC-User/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:142005)
    at Tu (file:///C:/Users/PC-User/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:149041)
    at Eu (file:///C:/Users/PC-User/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:148421)
    at Nu (file:///C:/Users/PC-User/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:149800)
    at Nn (file:///C:/Users/PC-User/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:81487)
    at HTMLDocument.i (file:///C:/Users/PC-User/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:363365)
```

## Component stack (don't write anything here)
```

    in n
    in div
    in i
    in div
    in o
    in div
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in n
    in t
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in E
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in u
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in p
    in p
    in p
    in p
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in p
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta108-1640ca49d72bfb4c97bc4a6c6fd5f8b4ee5bae18
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19042,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta108 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by Silver-Streak** [comment]
Are you still getting this crash?
If so, can you list out the steps to reproduce the crash, I tried a reloading from recent a bunch of times, including after deleting a sprite, and I cannot get it to crash.

(This issue will be closed out if no response within 30 days)
