### ISSUE TITLE
Wrong at require Electron 

### ISSUE THREAD

**Issue by arteze** [4ian/GDevelop#2528]
## The compiled game is not running

At compiling game with Node, fails at require Node.

## To Reproduce

- `main.js`

```js
const { app, BrowserWindow, shell, Menu } = require("electron");
```

At require electron, returns path of binary Node.

    '/root/GDevelop projects/8s9m/node_modules/electron/dist/electron'

And not the object with `app` property.

## Other details

- `GDevelop-5-5.0.0-beta108.AppImage --no-sandbox`

**Comment by arthuro555** [comment]
Can you give more details?
- What compilation are you talking about? electron-builder? If yes please include this info in your report.
- Your reproduction steps aren't steps and aren't helping to replicate. Please give us clear instructions to replicate the issue.
- What does `const { app, BrowserWindow, shell, Menu } = require("electron");` mean? Are you quoting code you have put in a JS event? Are you quoting an error from electron? Where exactly does it come from? Is it what you mean by saying "dails at require node"? In that case please don't say something confusing like this, as the code snippet you quoted obviously says require electron and not require node.

**Comment by arteze** [comment]
Sorry I was wrong, it's not compiling, it's running the compiled game for Electron.

At run `main.js`:

```sh
node /initrd/mnt/dev_save/LxPupSc64save-a/root/GDevelop projects/8s9m/main.js
```

I get an error:

```js
app.allowRendererProcessReuse = false;
                              ^

TypeError: Cannot set property 'allowRendererProcessReuse' of undefined
    at Object.<anonymous> (/initrd/mnt/dev_save/LxPupSc64save-a/root/GDevelop projects/8s9m/main.js:56:31)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```

At `main.js:56`:

```js
// Should be set to true, which will be the default value in future Electron
// versions, but then causes an issue on Windows where the `fs` module stops	
// working in the renderer process after a reload.
// See https://github.com/electron/electron/issues/22119
// For now, out of caution, disable this as we rely heavily on `fs` in the 
// renderer process.
app.allowRendererProcessReuse = false;
```

From this error, I can draw a conclusion:

```js
app.allowRendererProcessReuse = false;
                              ^

TypeError: Cannot set property 'allowRendererProcessReuse' of undefined
```

My conclusion is that `app` is `undefined`... So I go to where `app` is defined... `main.js:8`.

```js
/**
 * This is the file handling the startup and lifetime of the game
 * running in Electron Runtime.
 */
// Modules to control application life and create native browser window
const { app, BrowserWindow, shell, Menu } = require("electron");
```

I see that by requiring `electron`, it is defined as a path `'/root/GDevelop projects/8s9m/node_modules/electron/dist/electron'`, and not as an object with the `allowRendererProcessReuse` property.

**Comment by arthuro555** [comment]
What electron version are you on? Did you build it yourself or using the build service?

**Comment by arteze** [comment]
From the txt:

```sh
/initrd/mnt/dev_save/LxPupSc64save-a/root/GDevelop projects/8s9m/node_modules/electron/dist/version
```

Within the file you see the following:
```js
12.0.2
```

Electron installed it via npm... If I remember well it was something like `npm install electron`.

**Comment by arthuro555** [comment]
I just tried to launch a GDevelop game using electron 12 and I didn't experience any such issue. Please provide more exact reproduction steps.

**Comment by arteze** [comment]
The problem is precisely that I cannot require Electron from Node.

I would like to know what is shown when doing `require("electron")` from Node ... I'm sure an **object** should appear and not the **path**, which returns me.

Plus... If I run Electron, with no arguments, it gives me an error.

```sh
"/initrd/mnt/dev_save/LxPupSc64save-a/root/GDevelop projects/8s9m/node_modules/electron/dist/electron"
```

Error:

```sh
Illegal instruction
```

**Comment by 4ian** [comment]
It's not clear what you're trying to achieve. 
Can you start again your explanations from the beginning:
1. I open GDevelop
2. I open this game
3. I click there
4. I export the game by clicking there
5. I open a terminal and do this...

Etc... :) It seems like you've exported using "Windows/macOS/Linux (manual)", but I'm not even sure.
Note that if you're not used to this, you should not do things like `npm install electron` - this will create only more confusion.

**Comment by arteze** [comment]
I am on Puppy Linux, I already exported the game for Linux.

I want to highlight the fact that in Puppy there is no `sudo`, or administrator permissions, that's why I had to open the GDevelop from the _sandbox_.

There is another problem too, that it can't be compiled online because you can't create an account and log in, that's why I exported it for Linux.

When exporting the game it generates a `main.js` and a `package.json`.

A `package.json`:

```json
{
  "name": "mindy_95isometric_95world",
  "main": "main.js",
  "productName": "Mindy_Isometric_World",
  "description": "Mindy_Isometric_World",
  "author": "Mickael HOARAU",
  "version": "1.0.0",
  "scripts": {
    "start": "electron main.js",
    "build": "electron-builder"
  },
  "devDependencies": {
    "electron": "^12.0.4",
    "electron-builder": "22.9.1"
  },
  "build": {
    "appId": "com.example.mindyworld",
    "directories": {
      "buildResources": "buildResources"
    }
  }
}
```

A `main.js`:

```js
#!/bin/node

/**
 * This is the file handling the startup and lifetime of the game
 * running in Electron Runtime.
 */
// Modules to control application life and create native browser window
const { app, BrowserWindow, shell, Menu } = require("electron");

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let mainWindow = null;

function createWindow() {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    width: 1280,
    height: 720,
    useContentSize: true,
    title: "Mindy_Isometric_World",
    backgroundColor: '#000000',
    webPreferences: {
      nodeIntegration: true,
    }
  });

  // Open external link in the OS default browser
  mainWindow.webContents.on("new-window", function(e, url) {
    e.preventDefault();
    shell.openExternal(url);
  });

  // and load the index.html of the app.
  mainWindow.loadFile("app/index.html");

  Menu.setApplicationMenu(null);

  // Open the DevTools.
  // mainWindow.webContents.openDevTools()

  // Emitted when the window is closed.
  mainWindow.on("closed", function() {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null;
  });
}

// Should be set to true, which will be the default value in future Electron
// versions, but then causes an issue on Windows where the `fs` module stops	
// working in the renderer process after a reload.
// See https://github.com/electron/electron/issues/22119
// For now, out of caution, disable this as we rely heavily on `fs` in the 
// renderer process.
app.allowRendererProcessReuse = false;

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", createWindow);

// Quit when all windows are closed.
app.on("window-all-closed", function() {
  app.quit();
});
```

I have installed Electron using _npm_ because it is one of the necessary dependencies that `main.js` requires.

My question is... From the Node terminal, what should I show when doing `require("electron")`?... If I could know that I would be closer to solving the problem...

The problem is that if I do that from the Node terminal, it only returns a path and not the object with the properties, `app`, `BrowserWindow`, `shell`, `Menu` and others that I do not know.

```js
> require("electron")
'/initrd/mnt/dev_save/LxPupSc64save-a/root/GDevelop projects/8s9m/node_modules/electron/dist/electron'
```

**Comment by arthuro555** [comment]
Installing electron is not a step of the build process. Please read the manual instead of trying random stuff to guess how it works:
[![image](https://user-images.githubusercontent.com/19349038/115119769-64d6fd80-9faa-11eb-862c-7ae96514205b.png)  
Link to the wiki page](http://wiki.compilgames.net/doku.php/gdevelop5/publishing/windows-macos-linux-with-electron#publish_your_game_to_windows_macos_and_linux_manually_using_electron_and_electron_builder)

The electron module is only available in electron apps, so it is expected to not work in node terminals. 


> it can't be compiled online because you can't create an account and log in

Can you explain what the issue is exactly? No linux user ever said that it wasn't working for them.

**Comment by arteze** [comment]
I just read the indicated manual, when using yarn I get errors.

```sh
root@puppypc30690:~/Desktop/GDevelop projects/8s9m# yarn build -wlm
yarn run v1.22.10
warning package.json: No license field
$ electron-builder -wlm
  ��� electron-builder  version=22.10.5 os=5.7.2-lxpup64
  ��� loaded configuration  file=package.json ("build" field)
  ��� writing effective config  file=dist/builder-effective-config.yaml
  ��� packaging       platform=darwin arch=x64 electron=12.0.4 appOutDir=dist/mac
  ��� Unpacking electron zip  zipPath=undefined
  ��� skipped macOS application code signing  reason=supported only on macOS
  ��� building        target=macOS zip arch=x64 file=dist/Mindy_Isometric_World-1.0.0-mac.zip
  ��� building        target=DMG arch=x64 file=dist/Mindy_Isometric_World-1.0.0.dmg
  ��� Above command failed, retrying 5 more times
  ��� packaging       platform=linux arch=x64 electron=12.0.4 appOutDir=dist/linux-unpacked
  ��� Unpacking electron zip  zipPath=undefined
  ��� Above command failed, retrying 4 more times
  ��� Above command failed, retrying 3 more times
  ��� Above command failed, retrying 2 more times
  ��� Above command failed, retrying 1 more times
  ��� Above command failed, retrying 0 more times
  ��� building        target=snap arch=x64 file=dist/mindy_95isometric_95world_1.0.0_amd64.snap
  ��� building        target=AppImage arch=x64 file=dist/Mindy_Isometric_World-1.0.0.AppImage
  ��� application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
  ��� packaging       platform=win32 arch=x64 electron=12.0.4 appOutDir=dist/win-unpacked
  ��� Unpacking electron zip  zipPath=undefined
  ��� application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
  ��� downloading     url=https://github.com/electron/electron/releases/download/v12.0.4/electron-v12.0.4-win32-x64.zip size=83 MB parts=2
  ��� downloaded      url=https://github.com/electron/electron/releases/download/v12.0.4/electron-v12.0.4-win32-x64.zip duration=52.637s
  ��� downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z size=5.6 MB parts=1
  ��� downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z duration=5.584s
  ��� wine is required, please see https://electron.build/multi-platform-build#linux  
  ��� Above command failed, retrying 3 more times
  ��� wine is required, please see https://electron.build/multi-platform-build#linux  
  ��� Above command failed, retrying 2 more times
  ��� wine is required, please see https://electron.build/multi-platform-build#linux  
  ��� Above command failed, retrying 1 more times
  ��� wine is required, please see https://electron.build/multi-platform-build#linux  
  ��� Above command failed, retrying 0 more times
  ��� /initrd/mnt/dev_save/LxPupSc64save-a/root/GDevelop projects/8s9m/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
                                                                                                                                                                                Error: /initrd/mnt/dev_save/LxPupSc64save-a/root/GDevelop projects/8s9m/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                                                                                                                                                                                    at ChildProcess.<anonymous> (/initrd/mnt/dev_save/LxPupSc64save-a/root/GDevelop projects/8s9m/node_modules/builder-util/src/util.ts:243:14)
                                                                                                                                                                                    at Object.onceWrapper (node:events:485:26)
                                                                                                                                                                                    at ChildProcess.emit (node:events:378:20)
                                                                                                                                                                                    at maybeClose (node:internal/child_process:1067:16)
                                                                                                                                                                                    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
                                                                                                                                                                                From previous event:
                                                                                                                                                                                    at processImmediate (node:internal/timers:464:21)
                                                                                                                                                                                From previous event:
                                                                                                                                                                                    at WinPackager.signApp (/initrd/mnt/dev_save/LxPupSc64save-a/root/GDevelop projects/8s9m/node_modules/app-builder-lib/src/winPackager.ts:357:27)
                                                                                                                                                                                    at WinPackager.doSignAfterPack (/initrd/mnt/dev_save/LxPupSc64save-a/root/GDevelop projects/8s9m/node_modules/app-builder-lib/src/platformPackager.ts:270:16)
                                                                                                                                                                                    at WinPackager.doPack (/initrd/mnt/dev_save/LxPupSc64save-a/root/GDevelop projects/8s9m/node_modules/app-builder-lib/src/platformPackager.ts:255:7)
                                                                                                                                                                                    at WinPackager.pack (/initrd/mnt/dev_save/LxPupSc64save-a/root/GDevelop projects/8s9m/node_modules/app-builder-lib/src/platformPackager.ts:115:5)
                                                                                                                                                                                    at Packager.doBuild (/initrd/mnt/dev_save/LxPupSc64save-a/root/GDevelop projects/8s9m/node_modules/app-builder-lib/src/packager.ts:434:9)
                                                                                                                                                                                    at executeFinally (/initrd/mnt/dev_save/LxPupSc64save-a/root/GDevelop projects/8s9m/node_modules/builder-util/src/promise.ts:12:14)
                                                                                                                                                                                    at Packager._build (/initrd/mnt/dev_save/LxPupSc64save-a/root/GDevelop projects/8s9m/node_modules/app-builder-lib/src/packager.ts:369:31)
                                                                                                                                                                                    at Packager.build (/initrd/mnt/dev_save/LxPupSc64save-a/root/GDevelop projects/8s9m/node_modules/app-builder-lib/src/packager.ts:333:12)
                                                                                                                                                                                    at executeFinally (/initrd/mnt/dev_save/LxPupSc64save-a/root/GDevelop projects/8s9m/node_modules/builder-util/src/promise.ts:12:14)

  ��� building embedded block map  file=dist/Mindy_Isometric_World-1.0.0-mac.zip
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Summarizing, says it requires wine:

```sh
��� wine is required, please see https://electron.build/multi-platform-build#linux
```

If I compile it with the `l` argument I have no problem... But at the time of executing it, yes.

```sh
root@puppypc30690:~/Desktop/GDevelop projects/8s9m# yarn build -l 
yarn run v1.22.10
warning package.json: No license field
$ electron-builder -l
  ��� electron-builder  version=22.10.5 os=5.7.2-lxpup64
  ��� loaded configuration  file=package.json ("build" field)
  ��� writing effective config  file=dist/builder-effective-config.yaml
  ��� packaging       platform=linux arch=x64 electron=12.0.4 appOutDir=dist/linux-unpacked
  ��� Unpacking electron zip  zipPath=undefined
  ��� building        target=snap arch=x64 file=dist/mindy_95isometric_95world_1.0.0_amd64.snap
  ��� building        target=AppImage arch=x64 file=dist/Mindy_Isometric_World-1.0.0.AppImage
  ��� application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
  ��� application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
Done in 260.30s.
```

Also, when I run the compiled _AppImage_ it comes out that the instruction is illegal.

```sh
root@puppypc30690:/initrd/mnt/dev_save/LxPupSc64save-a/root/GDevelop projects/8s9m# "/root/Desktop/GDevelop projects/8s9m/dist/Mindy_Isometric_World-1.0.0.AppImage"
Illegal instruction
```

Why is it that the instruction is illegal? Is it possible to debug it?

**Comment by arteze** [comment]
I still had to explain about creating an account ... I can't create an account from GDevelop ... Also, I can't search for program updates from GDevelop either.

```js
14:42:24.434 ��� GDevelop Electron app starting...
14:43:19.257 ��� Starting check for updates (with auto-download if any)
14:43:19.447 ��� Checking for update
14:43:19.450 ��� { message: 'Checking for update...', status: 'checking-for-update' }
14:43:23.315 ��� Error: Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2519:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
14:43:23.321 ��� {
  message: 'Error in auto-updater. Error: net::ERR_FAILED',
  status: 'error',
  err: {
    constructor: 'Error',
    stack: 'Error: net::ERR_FAILED\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2519:21)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:210:5)'
  }
}
(node:25163) UnhandledPromiseRejectionWarning: Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2519:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
(node:25163) UnhandledPromiseRejectionWarning: Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2519:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
```

![Screenshot(37)](https://user-images.githubusercontent.com/3245767/115122091-98635900-9fa5-11eb-89aa-333f3bba770b.png)
