### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Kumar85** [4ian/GDevelop#2541]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
RuntimeError: memory access out of bounds
    at wasm-function[251]:0x1f807
    at Variable.GetType.Variable.GetType [as getType] (file:///C:/Users/Phoenix/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.0-beta108-1640ca49d72bfb4c97bc4a6c6fd5f8b4ee5bae18:9:1150836)
    at n.value (file:///C:/Users/Phoenix/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.d9c43286.chunk.js:1:776123)
    at file:///C:/Users/Phoenix/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.d9c43286.chunk.js:1:778492
    at n (file:///C:/Users/Phoenix/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.d9c43286.chunk.js:1:994432)
    at n.value (file:///C:/Users/Phoenix/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.d9c43286.chunk.js:1:778423)
    at To (file:///C:/Users/Phoenix/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:114055)
    at ko (file:///C:/Users/Phoenix/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:113848)
    at Co (file:///C:/Users/Phoenix/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:117709)
    at Ua (file:///C:/Users/Phoenix/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:141621)
    at Fa (file:///C:/Users/Phoenix/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:142005)
    at Tu (file:///C:/Users/Phoenix/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:149041)
    at Eu (file:///C:/Users/Phoenix/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:148421)
    at Nu (file:///C:/Users/Phoenix/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:149800)
    at Nn (file:///C:/Users/Phoenix/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:81487)
    at HTMLDocument.i (file:///C:/Users/Phoenix/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:363365)
```

## Component stack (don't write anything here)
```

    in n
    in div
    in i
    in div
    in o
    in div
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in n
    in t
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in E
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in u
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in p
    in p
    in p
    in p
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in p
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta108-1640ca49d72bfb4c97bc4a6c6fd5f8b4ee5bae18
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19042,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta108 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by Bouh** [comment]
Hello @Kumar85 

To help us to understand this bug, knowing what you tried to do would help us.

**Comment by arthuro555** [comment]
@4ian Any Idea how `Type GetType() const { return type; }` could cause an out of bounds memory access? Do you think it is possibly a reference to a deleted variable that is kept in the react app?

**Comment by arthuro555** [comment]
Btw, the crash happened to me when selecting an object after deleting another one

**Comment by 4ian** [comment]
> Do you think it is possibly a reference to a deleted variable that is kept in the react app?

Yes. This is exactly this (out of bound means here that the memory was freed, and we try to access it)

> the crash happened to me when selecting an object after deleting another one

I think there is a problem where the list of variables of an instance is rendered after an object/instance is deleted.
A way to debug this would be to add logs to see when the component is rendered, and verify if it happens after an object is deleted/selected/instance removed etc...
Usually I log the `ptr` of the emscripten objects. This is a plain number (no risk of crash) and it helps to see if this pointer corresponds to something that was previously logged as deleted.

**Comment by Bouh** [comment]
I can reproduce this bug with a different way.


[GetType-memory out of bound-1618595652575.log](https://github.com/4ian/GDevelop/files/6327344/GetType-memory.out.of.bound-1618595652575.log)


https://user-images.githubusercontent.com/1670670/115070789-afe30900-9ef5-11eb-91f5-093ef843307d.mp4

**Comment by 4ian** [comment]
Ah nice @Bouh, I think you actually reproduced a different bug (using a deleted global object) (let me see if we can force a refresh of the objects list to avoid this discrepancy).
But I think the original bug reported here (`memory access out of bounds    at wasm-function[251]:0x1f807    at Variable.GetType.Variable.GetType [as getType] [...]`) is somewhat related: it must be something that is deleted and the list of variables of this thing that is trying to re-render and boom.

**Comment by 4ian** [comment]
@bouh I've fixed the crash you found in master. I found also that if you delete an object, the instances of it are removed but the selected instances of it are not removed from the selection, so if you try to change anything in the instance properties you'll likely corrupt the memory/crash at some point. Not sure if related but will fix that too.

**Comment by Bouh** [comment]
I didn't think that is a bug from the instances.
Many of the crashes that have been reported contain  `Variable.GetType.Variable.GetType`, and all crash report point to the b108.
There were no such crashes like that before.
I bet on a problem related to the recent implementation of the new types of variable in GD.

**Comment by 4ian** [comment]
We activated wasm instead of asm.js, so it's possible that this crash is happening now because WebAssembly will report any invalid memory access, while asm.js was failing silently.
