### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by AlanaFerreira** [4ian/GDevelop#2552]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: Failed to execute 'getUniformLocation' on 'WebGL2RenderingContext': parameter 1 is not of type 'WebGLProgram'.
    at t.generateShader (file:///C:/Users/35193/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.89857a76.chunk.js:2:94844)
    at t.bind (file:///C:/Users/35193/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.89857a76.chunk.js:2:92782)
    at t._renderDirect (file:///C:/Users/35193/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.89857a76.chunk.js:2:598840)
    at t._render (file:///C:/Users/35193/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.89857a76.chunk.js:2:597563)
    at t.render (file:///C:/Users/35193/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.89857a76.chunk.js:2:378910)
    at t.render (file:///C:/Users/35193/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.89857a76.chunk.js:2:378981)
    at t.render (file:///C:/Users/35193/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.89857a76.chunk.js:2:109801)
    at n.e._renderScene (file:///C:/Users/35193/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.d9c43286.chunk.js:1:1024096)
    at n.value (file:///C:/Users/35193/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.d9c43286.chunk.js:1:1031689)
    at fi (file:///C:/Users/35193/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:96718)
    at ko (file:///C:/Users/35193/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:112739)
    at Co (file:///C:/Users/35193/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:117709)
    at Ua (file:///C:/Users/35193/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:141621)
    at Fa (file:///C:/Users/35193/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:142005)
    at Tu (file:///C:/Users/35193/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:149041)
    at Eu (file:///C:/Users/35193/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:148421)
    at gu (file:///C:/Users/35193/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:147442)
    at Wa (file:///C:/Users/35193/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:146311)
    at Object.enqueueSetState (file:///C:/Users/35193/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:95703)
    at s.E.setState (file:///C:/Users/35193/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:45988)
    at file:///C:/Users/35193/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.89857a76.chunk.js:2:811149
    at i (file:///C:/Users/35193/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:363365)
```

## Component stack (don't write anything here)
```

    in n
    in div
    in div
    in Unknown
    in Measure
    in i
    in a
    in n
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in u
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in p
    in p
    in p
    in p
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in p
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta108-1640ca49d72bfb4c97bc4a6c6fd5f8b4ee5bae18
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19041,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta108 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by Bouh** [comment]
Hello @AlanaFerreira 

Can you help us understand the crash, tell us what you tried to do before the crash can help.
Which panel or button did you tried to open?
It's related to an object? A layer? An effect on a layer?
Something else?

**Comment by Silver-Streak** [comment]
Closing due to more info needed and no response from original poster in over 30 days.
