### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by vattmashu** [4ian/GDevelop#2583]
=> just crash
## Error stack (don't write anything here)
```
RuntimeError: memory access out of bounds
    at wasm-function[4091]:0x189c1e
    at wasm-function[4322]:0x18f760
    at wasm-function[4321]:0x18f6ea
    at wasm-function[2554]:0x81a68
    at wasm-function[2374]:0x73fdb
    at wasm-function[1084]:0x2f48f
    at InitialInstance.GetCustomProperties.InitialInstance.GetCustomProperties [as getCustomProperties] (file:///C:/Users/imary/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.0-beta108-1640ca49d72bfb4c97bc4a6c6fd5f8b4ee5bae18:9:1190149)
    at n.value (file:///C:/Users/imary/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.d9c43286.chunk.js:1:261616)
    at n.value (file:///C:/Users/imary/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.d9c43286.chunk.js:1:262574)
    at To (file:///C:/Users/imary/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:114055)
    at ko (file:///C:/Users/imary/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:113848)
    at Co (file:///C:/Users/imary/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:117709)
    at Ua (file:///C:/Users/imary/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:141621)
    at Fa (file:///C:/Users/imary/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:142005)
    at Tu (file:///C:/Users/imary/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:149041)
    at Eu (file:///C:/Users/imary/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:148421)
    at gu (file:///C:/Users/imary/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:147442)
    at Wa (file:///C:/Users/imary/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:146311)
    at Object.enqueueSetState (file:///C:/Users/imary/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:95703)
    at n.E.setState (file:///C:/Users/imary/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.4720e48a.chunk.js:2:45988)
    at Object.e.triggerUnsavedChanges (file:///C:/Users/imary/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.d9c43286.chunk.js:1:640355)
    at n.e._onObjectModified (file:///C:/Users/imary/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.d9c43286.chunk.js:1:1166953)
    at file:///C:/Users/imary/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.d9c43286.chunk.js:1:1162724
    at Object.o._onDeleteObject [as onDeleteObject] (file:///C:/Users/imary/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.d9c43286.chunk.js:1:876241)
    at n.e._deleteObject (file:///C:/Users/imary/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.d9c43286.chunk.js:1:1162630)
    at click (file:///C:/Users/imary/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.d9c43286.chunk.js:1:1166436)
    at CallbacksRegistry.apply (electron/js2c/renderer_init.js:2549:29)
    at electron/js2c/renderer_init.js:1469:21
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:1449:7)
    at EventEmitter.emit (events.js:210:5)
    at Object.onMessage (electron/js2c/renderer_init.js:2204:16)
```

## Component stack (don't write anything here)
```

    in n
    in t
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in E
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in u
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in p
    in p
    in p
    in p
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in p
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta108-1640ca49d72bfb4c97bc4a6c6fd5f8b4ee5bae18
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19041,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta108 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by Silver-Streak** [comment]
The dev contributor team should be able to dig into this some more, however can you provide details on what you were doing when the crash occurred?

Can you reproduce it, and if so, can you give steps on how to reproduce it?

**Comment by Silver-Streak** [comment]
Closed due to lack of steps to reproduce and no response.
