### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Mtcrvg10** [4ian/GDevelop#2608]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at la (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:128659)
    at Aa (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:132534)
    at ja (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:136097)
    at https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:149366
    at Object.t.unstable_runWithPriority (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:160133)
    at Su (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:149300)
    at Tu (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:149076)
    at Eu (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:148421)
    at Nu (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:149800)
    at Nn (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:81487)
    at HTMLDocument.i (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:363365)
```

## Component stack (don't write anything here)
```

    in n
    in p
    in ForwardRef
    in ForwardRef
    in Unknown
    in div
    in i
    in div
    in o
    in div
    in button
    in ForwardRef
    in ForwardRef
    in C
    in div
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in Unknown
    in d
    in div
    in o
    in div
    in i
    in u
    in G
    in div
    in i
    in div
    in ForwardRef
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in E
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in u
    in Unknown
    in t
    in A
    in div
    in n
    in div
    in ForwardRef
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in E
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in u
    in Unknown
    in j
    in n
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in p
    in p
    in p
    in p
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in p
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta108-1640ca49d72bfb4c97bc4a6c6fd5f8b4ee5bae18
* Arch: Unknown architecture (web-app),
* Platform Name: Win32,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36,

**Comment by Bouh** [comment]
Hi @Mtcrvg10 
Thanks for this bug report, can you explain what you are tried to do?

**Comment by Silver-Streak** [comment]
Are you still getting this crash?
If so, can you list out the steps to reproduce the crash, I tried a reloading from recent a bunch of times, including after deleting a sprite, and I cannot get it to crash.

(This issue will be closed out if no response within 30 days)
