### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by cyssiu** [4ian/GDevelop#2609]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
RuntimeError: memory access out of bounds
    at https://editor.gdevelop-app.com/libGD.wasm?cache-buster=5.0.0-beta108-1640ca49d72bfb4c97bc4a6c6fd5f8b4ee5bae18:wasm-function[2790]:0x922aa
    at emscripten_bind_VariablesContainer_GetAt_1 (https://editor.gdevelop-app.com/libGD.wasm?cache-buster=5.0.0-beta108-1640ca49d72bfb4c97bc4a6c6fd5f8b4ee5bae18:wasm-function[1252]:0x325c2)
    at Module._emscripten_bind_VariablesContainer_GetAt_1 (https://editor.gdevelop-app.com/libGD.js?cache-buster=5.0.0-beta108-1640ca49d72bfb4c97bc4a6c6fd5f8b4ee5bae18:9:665712)
    at VariablesContainer.GetAt.VariablesContainer.GetAt [as getAt] (https://editor.gdevelop-app.com/libGD.js?cache-buster=5.0.0-beta108-1640ca49d72bfb4c97bc4a6c6fd5f8b4ee5bae18:9:1273149)
    at https://editor.gdevelop-app.com/static/js/1.d9c43286.chunk.js:1:778457
    at n (https://editor.gdevelop-app.com/static/js/1.d9c43286.chunk.js:1:994432)
    at n.value (https://editor.gdevelop-app.com/static/js/1.d9c43286.chunk.js:1:778423)
    at To (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:114055)
    at ko (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:113848)
    at Co (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:117709)
    at Ua (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:141621)
    at Fa (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:142005)
    at Tu (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:149041)
    at Eu (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:148421)
    at gu (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:147442)
    at Wa (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:146311)
    at Object.enqueueSetState (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:95703)
    at n.E.setState (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:45988)
    at Object.o._onInstancesAdded [as onInstancesAdded] (https://editor.gdevelop-app.com/static/js/1.d9c43286.chunk.js:1:873885)
    at Object.drop (https://editor.gdevelop-app.com/static/js/1.d9c43286.chunk.js:1:1034003)
    at Object.drop (https://editor.gdevelop-app.com/static/js/1.d9c43286.chunk.js:1:817637)
    at e.drop (https://editor.gdevelop-app.com/static/js/0.89857a76.chunk.js:2:1468263)
    at https://editor.gdevelop-app.com/static/js/0.89857a76.chunk.js:2:1445615
    at https://editor.gdevelop-app.com/static/js/0.89857a76.chunk.js:2:1445808
    at Array.forEach (<anonymous>)
    at e.<anonymous> (https://editor.gdevelop-app.com/static/js/0.89857a76.chunk.js:2:1445541)
    at Object.keys.reduce.r.<computed> [as drop] (https://editor.gdevelop-app.com/static/js/0.89857a76.chunk.js:2:1433360)
    at handleTopDrop (https://editor.gdevelop-app.com/static/js/0.89857a76.chunk.js:2:1477470)
    at i (https://editor.gdevelop-app.com/static/js/59.4720e48a.chunk.js:2:363365)
```

## Component stack (don't write anything here)
```

    in n
    in div
    in i
    in div
    in o
    in div
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in n
    in t
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in E
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in u
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in p
    in p
    in p
    in p
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in p
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta108-1640ca49d72bfb4c97bc4a6c6fd5f8b4ee5bae18
* Arch: Unknown architecture (web-app),
* Platform Name: Win32,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36,

**Comment by Bouh** [comment]
Hi @cyssiu 
Thanks for this bug report, can you explain what you are tried to do?

**Comment by 4ian** [comment]
I'm hoping this kind of bug will be fixed with the next version, I fixed two similar crashes.
