### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by PearComputerInc** [4ian/GDevelop#2711]
=> It Crashed While Using It.

## Error stack (don't write anything here)
```
TypeError: c.getEffectsCount is not a function
    at https://editor.gdevelop-app.com/static/js/1.f94fa22b.chunk.js:1:1100178
    at mapReverseFor (https://editor.gdevelop-app.com/static/js/1.f94fa22b.chunk.js:1:4175)
    at n.value (https://editor.gdevelop-app.com/static/js/1.f94fa22b.chunk.js:1:1099962)
    at To (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:114261)
    at ko (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:114054)
    at Co (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:117915)
    at Ua (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:141827)
    at Fa (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:142211)
    at Tu (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:149247)
    at Eu (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:148627)
    at gu (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:147648)
    at Wa (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:146517)
    at to (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:107245)
    at https://editor.gdevelop-app.com/static/js/1.f94fa22b.chunk.js:1:1042183
    at new Promise (<anonymous>)
    at https://editor.gdevelop-app.com/static/js/1.f94fa22b.chunk.js:1:1042146
    at https://editor.gdevelop-app.com/static/js/1.f94fa22b.chunk.js:1:245173
    at https://editor.gdevelop-app.com/static/js/1.f94fa22b.chunk.js:1:248393
    at https://editor.gdevelop-app.com/static/js/1.f94fa22b.chunk.js:1:249439
```

## Component stack (don't write anything here)
```

    in n
    in sortableList(n)
    in div
    in Unknown
    in Measure
    in i
    in div
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in n
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in r
    in E
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in u
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in p
    in p
    in p
    in p
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in p
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta110-61a969fdb1bc5aac3af1896cc376d91e4e64c2ec
* Arch: Unknown architecture (web-app),
* Platform Name: Linux x86_64,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (X11; CrOS x86_64 13816.82.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.218 Safari/537.36,

**Comment by Silver-Streak** [comment]
Thanks for reporting this. 

Are you still getting this crash?
If so, can you list out the steps to reproduce the crash?

(This issue will be closed out if no response within 30 days)

**Comment by PearComputerInc** [comment]
> Thanks for reporting this.
> 
> Are you still getting this crash?
> If so, can you list out the steps to reproduce the crash?
> 
> (This issue will be closed out if no response within 30 days)

No.

**Comment by Silver-Streak** [comment]
Thank you for the confirmation. Closing issue.
