### ISSUE TITLE
Crash on the examples library

### ISSUE THREAD

**Issue by arthuro555** [4ian/GDevelop#2716]
## Describe the bug
When searching an example, the examples library sometimes crashes.

## To Reproduce
1. Go to the examples library
2. Type as search term `Game`
3. If there is no crash yet, scroll down a bit
4. "An editor has crashed" popup appears

![image](https://user-images.githubusercontent.com/19349038/121049785-517d2d00-c7b8-11eb-97f2-ae98841d53f7.png)

## Error stack
```
Invariant Violation: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at a (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:51282)
    at u (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:51552)
    at Wa (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:146553)
    at Object.enqueueForceUpdate (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:96228)
    at t.E.forceUpdate (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:46281)
    at t.value (https://editor.gdevelop-app.com/static/js/0.b4887639.chunk.js:2:397774)
    at https://editor.gdevelop-app.com/static/js/1.dc90df2e.chunk.js:1:196084
    at https://editor.gdevelop-app.com/static/js/1.dc90df2e.chunk.js:1:601064
    at oa (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:126601)
    at Ra (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:133475)
    at ja (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:136472)
    at https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:149572
    at Object.t.unstable_runWithPriority (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:160339)
    at Su (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:149506)
    at Tu (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:149282)
    at Eu (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:148627)
    at Iu (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:149723)
    at Ue (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:61293)
    at On (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:81951)
    at HTMLDocument.i (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:363571)
```

## Other details
* IDE version: 5.0.0-beta110-350fea08bf5af9e0ff3b06c4d244e8f5a55472a7
* Arch: Unknown architecture (web-app),
* Platform Name: Win32,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36,

**Comment by Bouh** [comment]
If it can help with the research:
I left the build running all day yesterday and didn't have a crash.
I searched all the examples one by one, all 137 of them, I didn't get a crash either.

**Comment by arthuro555** [comment]
That's weird, I get consistently the crash when searching for the keyword `Game` and scrolling a bit on the web app if the crash wasn't instant.


https://user-images.githubusercontent.com/19349038/121053587-ca31b880-c7bb-11eb-99e4-9556fbc6bda2.mp4

**Comment by Bouh** [comment]
I confirm I got crashs too on web-app, nothing on desktop.

**Comment by 4ian** [comment]
Weird, can you try on the local web-app (localhost:3000)? So we have a better stacktrace?

**Comment by arthuro555** [comment]
No, I couldn't replicate it in development after multiple attempts

**Comment by Bouh** [comment]
I close, this works now.
If the problem comes back we will see on a new issue.
