### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by eazton** [4ian/GDevelop#2764]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: this.plugins[t].destroy is not a function
    at t.destroy (file:///C:/Users/ryeas/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.9463f886.chunk.js:2:111849)
    at t.destroy (file:///C:/Users/ryeas/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.9463f886.chunk.js:2:522955)
    at n.value (file:///C:/Users/ryeas/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.f94fa22b.chunk.js:1:530178)
    at aa (file:///C:/Users/ryeas/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.6221ec4c.chunk.js:2:127014)
    at la (file:///C:/Users/ryeas/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.6221ec4c.chunk.js:2:128588)
    at Aa (file:///C:/Users/ryeas/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.6221ec4c.chunk.js:2:132740)
    at ja (file:///C:/Users/ryeas/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.6221ec4c.chunk.js:2:136303)
    at file:///C:/Users/ryeas/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.6221ec4c.chunk.js:2:149572
    at Object.t.unstable_runWithPriority (file:///C:/Users/ryeas/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.6221ec4c.chunk.js:2:160339)
    at Su (file:///C:/Users/ryeas/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.6221ec4c.chunk.js:2:149506)
    at Tu (file:///C:/Users/ryeas/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.6221ec4c.chunk.js:2:149282)
    at Eu (file:///C:/Users/ryeas/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.6221ec4c.chunk.js:2:148627)
    at Nu (file:///C:/Users/ryeas/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.6221ec4c.chunk.js:2:150006)
    at Nn (file:///C:/Users/ryeas/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.6221ec4c.chunk.js:2:81693)
    at HTMLDocument.i (file:///C:/Users/ryeas/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/59.6221ec4c.chunk.js:2:363571)
```

## Component stack (don't write anything here)
```

    in n
    in div
    in div
    in Unknown
    in Measure
    in i
    in r
    in n
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in u
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in p
    in p
    in p
    in p
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in p
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta110-c242e1747bc6d6d44ebbd49c56df28d63ce88413
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19042,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta110 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by Silver-Streak** [comment]
Hello!

Are you still experiencing this issue? Can you provide the steps to reproduce the crash?

I'm going through older/stale issues that have pending actions. I'll close this out if we don't hear back from you by next Friday (8/13/21) or if we receive confirmation that it is no longer occurring.
