### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Vitalii2906** [4ian/GDevelop#2815]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: _.JsPlatform.get(...).getBehavior is not a function
    at https://editor.gdevelop-app.com/static/js/1.dc90df2e.chunk.js:1:937639
    at Array.map (<anonymous>)
    at t.a (https://editor.gdevelop-app.com/static/js/1.dc90df2e.chunk.js:1:937558)
    at qi (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:104245)
    at Co (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:116556)
    at Ua (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:141827)
    at Fa (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:142211)
    at Tu (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:149247)
    at Eu (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:148627)
    at Nu (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:150006)
    at Nn (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:81693)
    at HTMLDocument.i (https://editor.gdevelop-app.com/static/js/59.6221ec4c.chunk.js:2:363571)
```

## Component stack (don't write anything here)
```

    in Unknown
    in div
    in ForwardRef
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in S
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in j
    in n
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in m
    in m
    in m
    in m
    in m
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta110-350fea08bf5af9e0ff3b06c4d244e8f5a55472a7
* Arch: Unknown architecture (web-app),
* Platform Name: Win32,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36,

**Comment by Bouh** [comment]
First time this issue come, it might be due to the recent update of the webapp yesterday.
Just refresh the page, the version you used was outdated.

Note to dev, could be adds a notification or a force refresh to avoid outdated code, or is the service worker should do that for us?
If i understand the problem is the previous version here b110 was loaded, and b112 is loading in backend into the service worker, but the page isn't refresh so people still use the previous b110?

**Comment by 4ian** [comment]
Yes there is some issue related to a cached version of the previous beta JS files using the new libGD.js wasm file - but I thought these caching issues were solved. Must have missed something - I agree we should force the update if this happen.

**Comment by Bouh** [comment]
I've watched a [tutorial ](https://grafikart.fr/tutoriels/decouverte-progressive-web-apps-1932)about PWA and service workers.

**Comment by Bouh** [comment]
Hi please update GDevelop to b114, or if you use the web app just reload the webpage.
