### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by willianholtz** [4ian/GDevelop#2829]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at a (file:///tmp/.mount_gdevelpIndDb/resources/app.asar/www/static/js/1.228bcb50.chunk.js:1:29102)
    at o (file:///tmp/.mount_gdevelpIndDb/resources/app.asar/www/static/js/1.228bcb50.chunk.js:1:330187)
    at new n (file:///tmp/.mount_gdevelpIndDb/resources/app.asar/www/static/js/1.228bcb50.chunk.js:1:385628)
    at li (file:///tmp/.mount_gdevelpIndDb/resources/app.asar/www/static/js/60.09ae687b.chunk.js:2:213190)
    at wa (file:///tmp/.mount_gdevelpIndDb/resources/app.asar/www/static/js/60.09ae687b.chunk.js:2:227987)
    at Sa (file:///tmp/.mount_gdevelpIndDb/resources/app.asar/www/static/js/60.09ae687b.chunk.js:2:234502)
    at Uo (file:///tmp/.mount_gdevelpIndDb/resources/app.asar/www/static/js/60.09ae687b.chunk.js:2:258414)
    at Fo (file:///tmp/.mount_gdevelpIndDb/resources/app.asar/www/static/js/60.09ae687b.chunk.js:2:258798)
    at Eu (file:///tmp/.mount_gdevelpIndDb/resources/app.asar/www/static/js/60.09ae687b.chunk.js:2:265834)
    at wu (file:///tmp/.mount_gdevelpIndDb/resources/app.asar/www/static/js/60.09ae687b.chunk.js:2:265214)
    at Iu (file:///tmp/.mount_gdevelpIndDb/resources/app.asar/www/static/js/60.09ae687b.chunk.js:2:266593)
    at In (file:///tmp/.mount_gdevelpIndDb/resources/app.asar/www/static/js/60.09ae687b.chunk.js:2:198280)
    at HTMLDocument.i (file:///tmp/.mount_gdevelpIndDb/resources/app.asar/www/static/js/60.09ae687b.chunk.js:2:306489)
```

## Component stack (don't write anything here)
```

    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in m
    in m
    in m
    in m
    in m
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta113-8174bca3b1e4fbcbdc2b661c08bf564c6dde9527
* Arch: x64,
* Platform Name: linux,
* System Version: 5.12.15-arch1-1,
* User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta113 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by willianholtz** [comment]
Easy to reproduce this bug!

https://www.youtube.com/watch?v=ZGt-BTylcDs

**Comment by Bouh** [comment]
@blurymind  @4ian hello a bit more critical bug on b113.
