### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Matorrc777** [4ian/GDevelop#2837]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at so (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:245452)
    at Po (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:249327)
    at Do (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:252890)
    at https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:266159
    at Object.t.unstable_runWithPriority (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:276926)
    at Ou (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:266093)
    at Eu (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:265869)
    at wu (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:265214)
    at Su (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:266310)
    at Ue (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:177880)
    at jn (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:198538)
    at HTMLDocument.i (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:306489)
```

## Component stack (don't write anything here)
```

    in n
    in p
    in ForwardRef
    in ForwardRef
    in Unknown
    in div
    in o
    in div
    in a
    in div
    in button
    in ForwardRef
    in ForwardRef
    in v
    in div
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in Unknown
    in d
    in div
    in a
    in div
    in o
    in u
    in U
    in div
    in o
    in div
    in ForwardRef
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in O
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in t
    in F
    in div
    in o
    in Unknown
    in div
    in ForwardRef
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in O
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in j
    in n
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in m
    in m
    in m
    in m
    in m
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta113-287a17b6344ba0047f042d07187419e67849975b
* Arch: Unknown architecture (web-app),
* Platform Name: Win32,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36,

**Comment by Bouh** [comment]
Thanks for reporting this.
What you did before is helpful in understanding the cause of the crash.
Can you list out the steps to reproduce the crash?

**Comment by Silver-Streak** [comment]
No response from user after roughly 30 days, closing issue.
