### ISSUE TITLE
Crash while using an editor after clicking preview for a game scene/level

### ISSUE THREAD

**Issue by kingith** [4ian/GDevelop#2865]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
RuntimeError: memory access out of bounds
    at https://editor.gdevelop-app.com/libGD.wasm?cache-buster=5.0.0-beta113-287a17b6344ba0047f042d07187419e67849975b:wasm-function[3018]:0xa0f64
    at https://editor.gdevelop-app.com/libGD.wasm?cache-buster=5.0.0-beta113-287a17b6344ba0047f042d07187419e67849975b:wasm-function[2951]:0x9ca6d
    at https://editor.gdevelop-app.com/libGD.wasm?cache-buster=5.0.0-beta113-287a17b6344ba0047f042d07187419e67849975b:wasm-function[2954]:0x9ccbe
    at https://editor.gdevelop-app.com/libGD.wasm?cache-buster=5.0.0-beta113-287a17b6344ba0047f042d07187419e67849975b:wasm-function[2173]:0x612f2
    at https://editor.gdevelop-app.com/libGD.wasm?cache-buster=5.0.0-beta113-287a17b6344ba0047f042d07187419e67849975b:wasm-function[1202]:0x31a15
    at LayoutEditorCanvasOptions.SerializeTo.LayoutEditorCanvasOptions.SerializeTo [as serializeTo] (https://editor.gdevelop-app.com/libGD.js?cache-buster=5.0.0-beta113-287a17b6344ba0047f042d07187419e67849975b:9:1249774)
    at a (https://editor.gdevelop-app.com/static/js/1.228bcb50.chunk.js:1:29087)
    at n.value (https://editor.gdevelop-app.com/static/js/1.228bcb50.chunk.js:1:407801)
    at xa (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:230848)
    at wa (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:230641)
    at Sa (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:234502)
    at Uo (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:258414)
    at Fo (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:258798)
    at Eu (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:265834)
    at wu (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:265214)
    at yu (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:264235)
    at qo (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:263104)
    at ta (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:223832)
    at https://editor.gdevelop-app.com/static/js/1.228bcb50.chunk.js:1:256652
```

## Component stack (don't write anything here)
```

    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in m
    in m
    in m
    in m
    in m
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta113-287a17b6344ba0047f042d07187419e67849975b
* Arch: Unknown architecture (web-app),
* Platform Name: Win32,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36,

**Comment by 4ian** [comment]
The version seems outdated, close all tabs and re-open it to get the web-app to auto update.

**Comment by Silver-Streak** [comment]
Are you still experiencing this issue on the most recent release?

Since there hasn't been a response for quite some time, if no updates are received by 10/8 we'll go ahead and close this out.
