### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by AcsaMelo** [4ian/GDevelop#2907]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: o.getAssociatedSettings is not a function
    at n.value (https://editor.gdevelop-app.com/static/js/1.532d8d6b.chunk.js:1:408405)
    at xa (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:230848)
    at wa (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:230641)
    at Sa (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:234502)
    at Uo (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:258414)
    at Fo (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:258798)
    at Eu (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:265834)
    at wu (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:265214)
    at yu (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:264235)
    at qo (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:263104)
    at ta (https://editor.gdevelop-app.com/static/js/60.09ae687b.chunk.js:2:223832)
    at https://editor.gdevelop-app.com/static/js/1.532d8d6b.chunk.js:1:996938
    at new Promise (<anonymous>)
    at https://editor.gdevelop-app.com/static/js/1.532d8d6b.chunk.js:1:996901
    at https://editor.gdevelop-app.com/static/js/1.532d8d6b.chunk.js:1:258333
    at https://editor.gdevelop-app.com/static/js/1.532d8d6b.chunk.js:1:261553
    at https://editor.gdevelop-app.com/static/js/1.532d8d6b.chunk.js:1:262599
```

## Component stack (don't write anything here)
```

    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in m
    in m
    in m
    in m
    in m
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta114-26f6e95e4629adcb1428e3342c2ccd73d27554a6
* Arch: Unknown architecture (web-app),
* Platform Name: Win32,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36,

**Comment by Bouh** [comment]
Close all tabs and open again the web-app to have it updated. The error should go away.
