### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Akira2197** [4ian/GDevelop#2998]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at so (https://editor.gdevelop-app.com/static/js/60.7a0a852e.chunk.js:2:245358)
    at Po (https://editor.gdevelop-app.com/static/js/60.7a0a852e.chunk.js:2:249233)
    at Do (https://editor.gdevelop-app.com/static/js/60.7a0a852e.chunk.js:2:252796)
    at https://editor.gdevelop-app.com/static/js/60.7a0a852e.chunk.js:2:266065
    at Object.t.unstable_runWithPriority (https://editor.gdevelop-app.com/static/js/60.7a0a852e.chunk.js:2:276832)
    at Ou (https://editor.gdevelop-app.com/static/js/60.7a0a852e.chunk.js:2:265999)
    at Eu (https://editor.gdevelop-app.com/static/js/60.7a0a852e.chunk.js:2:265775)
    at wu (https://editor.gdevelop-app.com/static/js/60.7a0a852e.chunk.js:2:265120)
    at Iu (https://editor.gdevelop-app.com/static/js/60.7a0a852e.chunk.js:2:266499)
    at In (https://editor.gdevelop-app.com/static/js/60.7a0a852e.chunk.js:2:198186)
    at HTMLDocument.i (https://editor.gdevelop-app.com/static/js/60.7a0a852e.chunk.js:2:306395)
```

## Component stack (don't write anything here)
```

    in text
    in p
    in paragraph
    in span
    in root
    in y
    in l
    in span
    in ForwardRef
    in ForwardRef
    in Unknown
    in div
    in o
    in div
    in a
    in div
    in a
    in u
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in div
    in ne
    in div
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in Unknown
    in d
    in div
    in a
    in div
    in o
    in u
    in se
    in div
    in o
    in div
    in ForwardRef
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in S
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in n
    in div
    in Unknown
    in n
    in m
    in m
    in m
    in m
    in m
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta115-2581021a57df48af950962125443cce990b3cfa9
* Arch: Unknown architecture (web-app),
* Platform Name: MacIntel,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36,

**Comment by Bouh** [comment]
Hello @Akira2197 
Can you give more details about what you trying to achieve before the crash, how it could happen?
Unless more details we'll close out this bug report in 30 days.
Best regard
Bouh
