### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Mixen-me** [4ian/GDevelop#3010]
=> I was inserting my BitMapFont and I was dragging my mouse to select the BitMapFont in the Scene Editor. I released my mouse button but the dragging kept on going. After that, I closed the scene and re-opened it when this error showed up.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at a (file:///C:/Users/Sparkle/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.aea6426a.chunk.js:1:29099)
    at o (file:///C:/Users/Sparkle/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.aea6426a.chunk.js:1:331778)
    at new n (file:///C:/Users/Sparkle/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.aea6426a.chunk.js:1:387399)
    at li (file:///C:/Users/Sparkle/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/60.be227616.chunk.js:2:213096)
    at wa (file:///C:/Users/Sparkle/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/60.be227616.chunk.js:2:227893)
    at Sa (file:///C:/Users/Sparkle/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/60.be227616.chunk.js:2:234408)
    at Uo (file:///C:/Users/Sparkle/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/60.be227616.chunk.js:2:258320)
    at Fo (file:///C:/Users/Sparkle/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/60.be227616.chunk.js:2:258704)
    at Eu (file:///C:/Users/Sparkle/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/60.be227616.chunk.js:2:265740)
    at wu (file:///C:/Users/Sparkle/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/60.be227616.chunk.js:2:265120)
    at Iu (file:///C:/Users/Sparkle/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/60.be227616.chunk.js:2:266499)
    at In (file:///C:/Users/Sparkle/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/60.be227616.chunk.js:2:198186)
    at HTMLDocument.i (file:///C:/Users/Sparkle/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/60.be227616.chunk.js:2:306395)
```

## Component stack (don't write anything here)
```

    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in m
    in m
    in m
    in m
    in m
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta115-e4fc065dc13f86cee1d996de6201ed470a04ea66
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.18362,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta115 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by 4ian** [comment]
Should be fixed in beta 117 - was due to NaN in object width.
