### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by JG2005-CPU** [4ian/GDevelop#3028]
=>I was using the editor and then it kept acting like i was selecting then the me file got corrupted and there is no backups :(

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at a (file:///C:/Users/johna/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.aea6426a.chunk.js:1:29099)
    at o (file:///C:/Users/johna/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.aea6426a.chunk.js:1:331778)
    at new n (file:///C:/Users/johna/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.aea6426a.chunk.js:1:387399)
    at li (file:///C:/Users/johna/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/60.be227616.chunk.js:2:213096)
    at wa (file:///C:/Users/johna/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/60.be227616.chunk.js:2:227893)
    at Sa (file:///C:/Users/johna/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/60.be227616.chunk.js:2:234408)
    at Uo (file:///C:/Users/johna/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/60.be227616.chunk.js:2:258320)
    at Fo (file:///C:/Users/johna/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/60.be227616.chunk.js:2:258704)
    at Eu (file:///C:/Users/johna/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/60.be227616.chunk.js:2:265740)
    at wu (file:///C:/Users/johna/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/60.be227616.chunk.js:2:265120)
    at Iu (file:///C:/Users/johna/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/60.be227616.chunk.js:2:266499)
    at In (file:///C:/Users/johna/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/60.be227616.chunk.js:2:198186)
    at HTMLDocument.i (file:///C:/Users/johna/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/60.be227616.chunk.js:2:306395)
```

## Component stack (don't write anything here)
```

    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in m
    in m
    in m
    in m
    in m
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta115-e4fc065dc13f86cee1d996de6201ed470a04ea66
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19042,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta115 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by JG2005-CPU** [comment]
The App Deleted Itself No Joke. Why??????????

**Comment by Bouh** [comment]
Hi @JG2005-CPU 
This bug has been fixed, please update to b117 with the auto-updater.

**Comment by JG2005-CPU** [comment]
Thanks.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
