### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by cyannugget** [4ian/GDevelop#3055]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
RuntimeError: memory access out of bounds
    at wasm-function[3055]:0xa304a
    at wasm-function[2064]:0x57e33
    at wasm-function[2065]:0x5822a
    at wasm-function[1471]:0x37f4f
    at Function.MetadataProvider.STATIC_GetActionMetadata.MetadataProvider.STATIC_GetActionMetadata [as getActionMetadata] (file:///C:/Users/phxkr/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.0-beta117-2a19ea518262feb7bcc466dc191cc3d292e46913:9:1400375)
    at file:///C:/Users/phxkr/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.bd9ad372.chunk.js:1:723471
    at file:///C:/Users/phxkr/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.bd9ad372.chunk.js:1:326948
    at Bi (file:///C:/Users/phxkr/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:220738)
    at _a (file:///C:/Users/phxkr/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:227578)
    at Sa (file:///C:/Users/phxkr/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:234326)
    at Uo (file:///C:/Users/phxkr/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:258320)
    at Fo (file:///C:/Users/phxkr/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:258704)
    at Eu (file:///C:/Users/phxkr/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:265740)
    at wu (file:///C:/Users/phxkr/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:265120)
    at yu (file:///C:/Users/phxkr/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:264141)
    at qo (file:///C:/Users/phxkr/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:263010)
    at Object.enqueueForceUpdate (file:///C:/Users/phxkr/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:212721)
    at n.w.forceUpdate (file:///C:/Users/phxkr/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:162773)
    at n.value (file:///C:/Users/phxkr/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.bd9ad372.chunk.js:1:718520)
    at file:///C:/Users/phxkr/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.bd9ad372.chunk.js:1:817832
    at i (file:///C:/Users/phxkr/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:306395)
```

## Component stack (don't write anything here)
```

    in Unknown
    in DropTarget(Component)
    in DragSource(DropTarget(Component))
    in Unknown
    in Unknown
    in div
    in Unknown
    in DropTarget(Component)
    in Unknown
    in f
    in div
    in Unknown
    in n
    in div
    in n
    in span
    in div
    in div
    in div
    in div
    in div
    in t
    in DragSource(t)
    in div
    in div
    in t
    in DropTarget(t)
    in div
    in div
    in t
    in t
    in Scrolling(t)
    in div
    in t
    in div
    in t
    in re
    in Unknown
    in L
    in div
    in n
    in div
    in n
    in u
    in a
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in m
    in m
    in m
    in m
    in m
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta117-2a19ea518262feb7bcc466dc191cc3d292e46913
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19042,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta117 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by 4ian** [comment]
Thanks for reporting this - any chance you remember the steps leading to the bug so we can fix it?
