### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by samuel2563** [4ian/GDevelop#3072]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: this.plugins[t].destroy is not a function
    at t.destroy (file:///C:/Users/pc/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.86178056.chunk.js:2:111375)
    at t.destroy (file:///C:/Users/pc/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.86178056.chunk.js:2:521701)
    at n.value (file:///C:/Users/pc/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.bd9ad372.chunk.js:1:475759)
    at ao (file:///C:/Users/pc/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:243507)
    at so (file:///C:/Users/pc/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:245081)
    at Po (file:///C:/Users/pc/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:249233)
    at Do (file:///C:/Users/pc/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:252796)
    at file:///C:/Users/pc/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:266065
    at Object.t.unstable_runWithPriority (file:///C:/Users/pc/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:276832)
    at Ou (file:///C:/Users/pc/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:265999)
    at Eu (file:///C:/Users/pc/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:265775)
    at wu (file:///C:/Users/pc/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:265120)
    at yu (file:///C:/Users/pc/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:264141)
    at qo (file:///C:/Users/pc/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:263010)
    at Object.enqueueSetState (file:///C:/Users/pc/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:212402)
    at s.w.setState (file:///C:/Users/pc/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:162686)
    at file:///C:/Users/pc/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.86178056.chunk.js:2:966794
    at i (file:///C:/Users/pc/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:306395)
```

## Component stack (don't write anything here)
```

    in n
    in div
    in div
    in Unknown
    in Measure
    in i
    in a
    in n
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in u
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in m
    in m
    in m
    in m
    in m
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta117-2a19ea518262feb7bcc466dc191cc3d292e46913
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19042,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta117 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by 4ian** [comment]
Hi! Do you have any way/steps that could reproduce this crash? This would allow us to fix it. Thanks! :)
