### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by marcelomdea** [4ian/GDevelop#3075]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
Error: Failed to execute 'getImageData' on 'OffscreenCanvasRenderingContext2D': The source width is 0.
    at Function.e.measureFont (file:///C:/Users/Marcelo/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.86178056.chunk.js:2:220140)
    at o.updateText (C:\Users\Marcelo\AppData\Local\Programs\gdevelop\resources\GDJS\Runtime\Extensions\BBText\pixi-multistyle-text\dist\pixi-multistyle-text.umd.js:1:5922)
    at o.get (file:///C:/Users/Marcelo/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.86178056.chunk.js:2:226096)
    at RenderedBBTextInstance.update (C:\Users\Marcelo\AppData\Local\Programs\gdevelop\resources\GDJS\Runtime\Extensions\BBText\JsExtension.js:553:50)
    at new RenderedBBTextInstance (C:\Users\Marcelo\AppData\Local\Programs\gdevelop\resources\GDJS\Runtime\Extensions\BBText\JsExtension.js:482:12)
    at Object.createNewInstanceRenderer (file:///C:/Users/Marcelo/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.bd9ad372.chunk.js:1:45821)
    at e.getRendererOfInstance (file:///C:/Users/Marcelo/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.bd9ad372.chunk.js:1:894181)
    at InitialInstanceJSFunctor.instancesRenderer.invoke (file:///C:/Users/Marcelo/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.bd9ad372.chunk.js:1:895616)
    at 8628 (file:///C:/Users/Marcelo/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.0-beta117-2a19ea518262feb7bcc466dc191cc3d292e46913:9:18843)
    at _emscripten_asm_const_iii (file:///C:/Users/Marcelo/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.0-beta117-2a19ea518262feb7bcc466dc191cc3d292e46913:9:28312)
    at wasm-function[1684]:0x428bc
    at wasm-function[78]:0x1e80b
    at wasm-function[2542]:0x7bf8f
    at wasm-function[1135]:0x312d9
    at InitialInstancesContainer.IterateOverInstancesWithZOrdering.InitialInstancesContainer.IterateOverInstancesWithZOrdering [as iterateOverInstancesWithZOrdering] (file:///C:/Users/Marcelo/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.0-beta117-2a19ea518262feb7bcc466dc191cc3d292e46913:9:1237535)
    at e.value (file:///C:/Users/Marcelo/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.bd9ad372.chunk.js:1:897530)
    at e.value (file:///C:/Users/Marcelo/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.bd9ad372.chunk.js:1:441234)
    at n.e._renderScene (file:///C:/Users/Marcelo/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.bd9ad372.chunk.js:1:468061)
    at n.value (file:///C:/Users/Marcelo/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.bd9ad372.chunk.js:1:472151)
    at n.value (file:///C:/Users/Marcelo/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.bd9ad372.chunk.js:1:468613)
    at No (file:///C:/Users/Marcelo/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:250042)
    at Do (file:///C:/Users/Marcelo/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:252965)
    at file:///C:/Users/Marcelo/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:266065
    at Object.t.unstable_runWithPriority (file:///C:/Users/Marcelo/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:276832)
    at Ou (file:///C:/Users/Marcelo/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:265999)
    at Eu (file:///C:/Users/Marcelo/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:265775)
    at wu (file:///C:/Users/Marcelo/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:265120)
    at Iu (file:///C:/Users/Marcelo/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:266499)
    at In (file:///C:/Users/Marcelo/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:198186)
    at HTMLDocument.i (file:///C:/Users/Marcelo/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.f2134e58.chunk.js:2:306395)
```

## Component stack (don't write anything here)
```

    in n
    in div
    in div
    in Unknown
    in Measure
    in i
    in a
    in n
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in u
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in m
    in m
    in m
    in m
    in m
    in s
    in n
    in t
    in n
    in Unknown
    in v
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta117-2a19ea518262feb7bcc466dc191cc3d292e46913
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19043,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.0-beta117 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by 4ian** [comment]
Hi! Do you have any steps about how to reproduce this? This would be help to understand and fix the bug :)
