### ISSUE TITLE
its not letting me in to gdevolp Crash while using an editor

### ISSUE THREAD

**Issue by realvwavay** [4ian/GDevelop#3100]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: o.getAssociatedSettings is not a function
    at n.value (https://editor.gdevelop-app.com/static/js/1.7a5a2acf.chunk.js:1:796435)
    at To (https://editor.gdevelop-app.com/static/js/59.31b0fbbe.chunk.js:2:96462)
    at ko (https://editor.gdevelop-app.com/static/js/59.31b0fbbe.chunk.js:2:96255)
    at Co (https://editor.gdevelop-app.com/static/js/59.31b0fbbe.chunk.js:2:100116)
    at Ua (https://editor.gdevelop-app.com/static/js/59.31b0fbbe.chunk.js:2:124028)
    at Fa (https://editor.gdevelop-app.com/static/js/59.31b0fbbe.chunk.js:2:124412)
    at Tu (https://editor.gdevelop-app.com/static/js/59.31b0fbbe.chunk.js:2:131448)
    at Eu (https://editor.gdevelop-app.com/static/js/59.31b0fbbe.chunk.js:2:130828)
    at Ou (https://editor.gdevelop-app.com/static/js/59.31b0fbbe.chunk.js:2:132207)
    at On (https://editor.gdevelop-app.com/static/js/59.31b0fbbe.chunk.js:2:63894)
```

## Component stack (don't write anything here)
```

    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in s
    in n
    in t
    in n
    in Unknown
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.0-beta100-2a62f71f08153124208e35970c0ba69643a4372d
* Arch: Unknown architecture (web-app),
* Platform Name: Win32,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36,

**Comment by realvwavay** [comment]
thank you
