### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by P-H-V** [4ian/GDevelop#3173]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: Cannot read property 'location' of undefined
    at eval (eval at <anonymous> (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/0.e2322221.chunk.js:1:1), <anonymous>:10:56)
    at e.syncUniforms (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/0.e2322221.chunk.js:2:105635)
    at e.syncUniformGroup (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/0.e2322221.chunk.js:2:105506)
    at eval (eval at <anonymous> (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/0.e2322221.chunk.js:1:1), <anonymous>:10:41)
    at e.syncUniforms (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/0.e2322221.chunk.js:2:105635)
    at e.syncUniformGroup (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/0.e2322221.chunk.js:2:105506)
    at e.bind (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/0.e2322221.chunk.js:2:105153)
    at t.render (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/0.e2322221.chunk.js:2:261332)
    at t._render (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/0.e2322221.chunk.js:2:257476)
    at t.render (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/0.e2322221.chunk.js:2:399843)
    at t.render (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/0.e2322221.chunk.js:2:399914)
    at t.render (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/0.e2322221.chunk.js:2:399914)
    at t.render (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/0.e2322221.chunk.js:2:399914)
    at t.render (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/0.e2322221.chunk.js:2:399914)
    at t.render (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/0.e2322221.chunk.js:2:130125)
    at n.e._renderScene (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.56e0a7ce.chunk.js:1:478102)
    at n.value (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.56e0a7ce.chunk.js:1:485972)
    at fi (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/61.802dcdb4.chunk.js:2:221665)
    at xo (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/61.802dcdb4.chunk.js:2:237686)
    at Co (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/61.802dcdb4.chunk.js:2:242656)
    at Ua (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/61.802dcdb4.chunk.js:2:266568)
    at Fa (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/61.802dcdb4.chunk.js:2:266952)
    at Eu (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/61.802dcdb4.chunk.js:2:273988)
    at wu (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/61.802dcdb4.chunk.js:2:273368)
    at yu (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/61.802dcdb4.chunk.js:2:272389)
    at qa (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/61.802dcdb4.chunk.js:2:271258)
    at Object.enqueueSetState (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/61.802dcdb4.chunk.js:2:220650)
    at s.w.setState (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/61.802dcdb4.chunk.js:2:170934)
    at file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/0.e2322221.chunk.js:2:1014428
    at i (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/61.802dcdb4.chunk.js:2:320861)
```

## Component stack (don't write anything here)
```

    in n
    in div
    in div
    in Unknown
    in Measure
    in i
    in a
    in n
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in u
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in m
    in m
    in m
    in m
    in m
    in s
    in n
    in t
    in pe
    in n
    in Unknown
    in v
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in u
```

## Other details
* IDE version: 5.0.120-44b81f52ea5a1d7ab84a05b62074babc2ff0f872
* Arch: x64,
* Platform Name: darwin,
* System Version: 10.15.7,
* User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.120 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by Bouh** [comment]
Hello @P-H-V 
Thanks for reporting this!
Can you provide the steps to reproduce the crash?
What you did before is helpful in understanding the cause of the crash.
