### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Midhil457** [4ian/GDevelop#3326]
I was updating the slider extension. I have attached two videos as the crash always happened .
I inverted the condition (Not seen in video)
Tried to open the operator parameter, crashs
The crash also happens when I try to open the parameter editor too
It only happens for those two conditions
## Project file

[My project4.zip](https://github.com/4ian/GDevelop/files/7642778/My.project4.zip)

## Videos

https://user-images.githubusercontent.com/73597906/144443529-8571e281-a2fb-4301-af12-fa490d24ea89.mp4

https://user-images.githubusercontent.com/73597906/144444152-24241a02-8220-48d8-a639-c207731e9048.mp4

## Error stack (don't write anything here)
```
TypeError: Cannot read property 'map' of undefined
    at n.value (file:///tmp/.mount_GDevelILbfFV/resources/app.asar/www/static/js/1.b1ec2722.chunk.js:1:775959)
    at Eo (file:///tmp/.mount_GDevelILbfFV/resources/app.asar/www/static/js/61.c1d05205.chunk.js:2:239002)
    at xo (file:///tmp/.mount_GDevelILbfFV/resources/app.asar/www/static/js/61.c1d05205.chunk.js:2:238795)
    at Co (file:///tmp/.mount_GDevelILbfFV/resources/app.asar/www/static/js/61.c1d05205.chunk.js:2:242656)
    at Ua (file:///tmp/.mount_GDevelILbfFV/resources/app.asar/www/static/js/61.c1d05205.chunk.js:2:266568)
    at Fa (file:///tmp/.mount_GDevelILbfFV/resources/app.asar/www/static/js/61.c1d05205.chunk.js:2:266952)
    at Eu (file:///tmp/.mount_GDevelILbfFV/resources/app.asar/www/static/js/61.c1d05205.chunk.js:2:273988)
    at wu (file:///tmp/.mount_GDevelILbfFV/resources/app.asar/www/static/js/61.c1d05205.chunk.js:2:273368)
    at Iu (file:///tmp/.mount_GDevelILbfFV/resources/app.asar/www/static/js/61.c1d05205.chunk.js:2:274747)
    at In (file:///tmp/.mount_GDevelILbfFV/resources/app.asar/www/static/js/61.c1d05205.chunk.js:2:206434)
    at HTMLDocument.i (file:///tmp/.mount_GDevelILbfFV/resources/app.asar/www/static/js/61.c1d05205.chunk.js:2:320861)
```

## Component stack (don't write anything here)
```

    in n
    in div
    in a
    in div
    in o
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in u
    in n
    in div
    in n
    in l
    in n
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in l
    in n
    in div
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in m
    in m
    in m
    in m
    in m
    in s
    in n
    in t
    in de
    in n
    in Unknown
    in v
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.122-3596896b16c1d57431ce60120fecb021ca1af5a7
* Arch: x64,
* Platform Name: linux mint
* System Version: 5.4.0-90-generic,
* User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.122 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by 4ian** [comment]
Thanks for reporting, found the problem I'm on it!

**Comment by 4ian** [comment]
Fixed, we'll release a new version tomorrow!
