### ISSUE TITLE
Editor crashing following an error due to removing a childNode not belonging to its parent

### ISSUE THREAD

**Issue by AlexandreSi** [4ian/GDevelop#3453]
## Describe the bug

Error message: 

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

Many users reported this bug:

- #3444 
- #3443

  > estava tranquilo para empezar en linea y me aparecio si quierescompartirlo a amigos y eso y yo le puse si
luego de poner el correo y eso al volver me aparece que no puedo entrar por un error

- #3440 

  > the bug happens a few seconds after I open Gdevelop, and it happens
even when I log in before the bug happens, a message appears and
nothing else works in the app, thanks for the help

- #3423 
- #3422 
- #3419 
- #3418 
- #3416 
- #3415 
- #3409 
- #3381 
- #3370 

## To Reproduce

Couldn't reproduce the bug so far

## Other details

We can notice that the bug appears only **in the webapp** and on no version prior to v124.

Most of the users that reported the bug are working on Linux but I think that Linux users are more likely to have a GitHub account, that could explain the proportion.

## Complete stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ca (https://editor.gdevelop-app.com/static/js/61.cb175572.chunk.js:2:253606)
    at Pa (https://editor.gdevelop-app.com/static/js/61.cb175572.chunk.js:2:257481)
    at Da (https://editor.gdevelop-app.com/static/js/61.cb175572.chunk.js:2:261044)
    at https://editor.gdevelop-app.com/static/js/61.cb175572.chunk.js:2:274313
    at Object.t.unstable_runWithPriority (https://editor.gdevelop-app.com/static/js/61.cb175572.chunk.js:2:285080)
    at Ou (https://editor.gdevelop-app.com/static/js/61.cb175572.chunk.js:2:274247)
    at Eu (https://editor.gdevelop-app.com/static/js/61.cb175572.chunk.js:2:274023)
    at wu (https://editor.gdevelop-app.com/static/js/61.cb175572.chunk.js:2:273368)
    at yu (https://editor.gdevelop-app.com/static/js/61.cb175572.chunk.js:2:272389)
    at qa (https://editor.gdevelop-app.com/static/js/61.cb175572.chunk.js:2:271258)
    at Object.enqueueSetState (https://editor.gdevelop-app.com/static/js/61.cb175572.chunk.js:2:220650)
    at n.w.setState (https://editor.gdevelop-app.com/static/js/61.cb175572.chunk.js:2:170934)
    at https://editor.gdevelop-app.com/static/js/1.b6cf75a2.chunk.js:1:536005
    at c (https://editor.gdevelop-app.com/static/js/61.cb175572.chunk.js:2:287686)
    at Generator._invoke (https://editor.gdevelop-app.com/static/js/61.cb175572.chunk.js:2:287439)
    at Generator.next (https://editor.gdevelop-app.com/static/js/61.cb175572.chunk.js:2:288045)
    at r (https://editor.gdevelop-app.com/static/js/61.cb175572.chunk.js:2:187)
    at u (https://editor.gdevelop-app.com/static/js/61.cb175572.chunk.js:2:390)
```

## What has been investigated so far

The lines of code at `61.cb175572.chunk.js:2:253606` that throw the error is:

```
8 === o.nodeType ? o.parentNode.removeChild(a) : o.removeChild(a)) : r.removeChild(t.stateNode)
// --------------------------------------------------------------------^
```

I tried to look around these lines to find a more specific code, I found a boolean check `"dangerouslySetInnerHTML" === n` (`dangerouslySetInnerHTML` is a react props) but I couldn't link it to a particular repository using GitHub Search.

I tried to grep the node module for the `removeChild` part, and it seems to come from a library that react uses for DOM handling (`react-dom` for instance).

There is an issue that reports this same error: https://github.com/facebook/react/issues/6802.

My gut feeling is that we incorrectly use/render a react component somewhere. It's hard to find where because the users that encountered the issue couldn't provide lots of context around the bug they experienced.

**Comment by 4ian** [comment]
> My gut feeling is that we incorrectly use/render a react component somewhere. It's hard to find where because the users that encountered the issue couldn't provide lots of context around the bug they experienced.

Yep, same feeling.

**Comment by Bouh** [comment]
Is there a possibility to add some keys or names into the Component stack report? It could help us a lot to identify the component. Currently it is not very interesting 😅

**Comment by AlexandreSi** [comment]
Actually, what we see is not a component hierarchy where we could see component names but the function calls that led to the error.
The problem is that the JS that is executed has been minified, polyfilled (and other things that I don't really know about) and "private" methods has been renamed to be called `Ca` or `Pa` so it's really not understandable.

**Comment by Bouh** [comment]
> Actually, what we see is not a component hierarchy where we could see component names but the function calls that led to the error.

No, I talk about this stack: 
![image](https://user-images.githubusercontent.com/1670670/149122297-567776f8-30d8-406c-967c-7730018e09a0.png)

**Comment by Bouh** [comment]
We what we see with the react dev tools:
![image](https://user-images.githubusercontent.com/1670670/149123442-bfc3ed45-08e8-414a-b992-466cb450a01c.png)

**Comment by AlexandreSi** [comment]
😅 I talked too quickly!
Well, this works in the development environement, so I don't know if, when we build the app, there's a setting that does that on purpose to minify the bundle

**Comment by Bouh** [comment]
Oh so it's due to the minifier. But he doesn't minify the key value, here with the "Start page" tab 
![image](https://user-images.githubusercontent.com/1670670/149124352-934138c9-adec-4495-bbdf-984abd7cc434.png)

**Comment by AlexandreSi** [comment]
The bug starts from here:

https://github.com/4ian/GDevelop/blob/v5.0.124/newIDE/app/src/UI/User/UserChip.js#L29-L37

It generates the following dom when users are not connected.

```html
<div>
  <svg>...</svg>
  <span class="MuiChip-label">Click to connect</span>
  <span class="MuiTouchRipple-root"></span>
</div>
```

Users on the web-app may have Google Translate activated. Google Translate modifies the DOM as such:

```html
<div>
  <svg>...</svg>
  <span class="MuiChip-label">
    <font style="vertical-align: inherit">
      <font style="vertical-align: inherit">Cliquez pour vous connecter</font>
    </font>
    </span>
  <span class="MuiTouchRipple-root"></span>
</div>
```

And it troubles React at the moment when the users logs in/the API call to the user API returns.

The fix that has been merged is a workaround but does not fix the root cause.

We don't want to prevent users to use Google Translate on the IDE (as suggested by https://github.com/facebook/react/issues/11538#issuecomment-359558410).
