### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by RagnarRandom** [4ian/GDevelop#3541]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
RangeError: Invalid array length
    at D (file:///C:/Users/Ryan/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.33e36594.chunk.js:2:372710)
    at t.updateText (file:///C:/Users/Ryan/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.33e36594.chunk.js:2:271798)
    at t.validate (file:///C:/Users/Ryan/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.33e36594.chunk.js:2:274914)
    at t.get (file:///C:/Users/Ryan/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.33e36594.chunk.js:2:276607)
    at RenderedBitmapTextInstance.update (C:\Users\Ryan\AppData\Local\Programs\gdevelop\resources\GDJS\Runtime\Extensions\BitmapText\JsExtension.js:688:51)
    at new RenderedBitmapTextInstance (C:\Users\Ryan\AppData\Local\Programs\gdevelop\resources\GDJS\Runtime\Extensions\BitmapText\JsExtension.js:604:12)
    at Object.createNewInstanceRenderer (file:///C:/Users/Ryan/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.4fcfcc97.chunk.js:1:60241)
    at e.getRendererOfInstance (file:///C:/Users/Ryan/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.4fcfcc97.chunk.js:1:997960)
    at InitialInstanceJSFunctor.instancesRenderer.invoke (file:///C:/Users/Ryan/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.4fcfcc97.chunk.js:1:999395)
    at 3052 (file:///C:/Users/Ryan/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.126-d49d765ec05d0454b365031d793c1702647877d8:9:17964)
    at _emscripten_asm_const_iii (file:///C:/Users/Ryan/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.126-d49d765ec05d0454b365031d793c1702647877d8:9:28312)
    at wasm-function[1551]:0x3a108
    at wasm-function[54]:0x1e5f6
    at wasm-function[2560]:0x7d03f
    at wasm-function[670]:0x2978b
    at InitialInstancesContainer.IterateOverInstancesWithZOrdering.InitialInstancesContainer.IterateOverInstancesWithZOrdering [as iterateOverInstancesWithZOrdering] (file:///C:/Users/Ryan/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.126-d49d765ec05d0454b365031d793c1702647877d8:9:1023057)
    at e.value (file:///C:/Users/Ryan/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.4fcfcc97.chunk.js:1:1001276)
    at e.value (file:///C:/Users/Ryan/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.4fcfcc97.chunk.js:1:509740)
    at n.e._renderScene (file:///C:/Users/Ryan/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.4fcfcc97.chunk.js:1:536873)
    at n.e.restartSceneRendering (file:///C:/Users/Ryan/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.4fcfcc97.chunk.js:1:537297)
    at n.value (file:///C:/Users/Ryan/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.4fcfcc97.chunk.js:1:545872)
    at fi (file:///C:/Users/Ryan/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:221665)
    at xo (file:///C:/Users/Ryan/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:237686)
    at Co (file:///C:/Users/Ryan/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:242656)
    at Ua (file:///C:/Users/Ryan/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:266568)
    at Fa (file:///C:/Users/Ryan/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:266952)
    at Eu (file:///C:/Users/Ryan/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:273988)
    at wu (file:///C:/Users/Ryan/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:273368)
    at Iu (file:///C:/Users/Ryan/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:274747)
    at In (file:///C:/Users/Ryan/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:206434)
    at HTMLDocument.i (file:///C:/Users/Ryan/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:320861)
```

## Component stack (don't write anything here)
```

    in n
    in div
    in div
    in Unknown
    in Measure
    in i
    in a
    in n
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in l
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in u
    in f
    in m
    in m
    in m
    in m
    in s
    in n
    in t
    in de
    in n
    in Unknown
    in v
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.126-d49d765ec05d0454b365031d793c1702647877d8
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19043,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.126 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by Bouh** [comment]
Hi @RagnarRandom 

Thank you for taking the time to report this issue.
We will need more info on this bug to fix it, what was the context before the app crashed?

**Comment by RagnarRandom** [comment]
ok so i was making a a scene to re-assign keyboard controls. i have multiple bitmap text objects in the scene. it's a pixel perfect style so i was manually moving bitmap text objects with the arrows keys 1 pixel at a time. i moved it a bunch one way, didn't like it, so i pressed ctrl+z to undo the movement and the error popped.

**Comment by Bouh** [comment]
>  Now scene only shows the error, even when closing project and reloading. Had to delete scene and start over because I couldn't do any editing to the scene.

If you still have the project file with the resources please send it to us for investigation.

**Comment by RagnarRandom** [comment]
I deleted the error scene and just started remaking it so I don't have it anymore in the project file. i suppose i should have made a backup of the error before reporting crash. probably not much you folks can do at this point.
