### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Dippydo** [4ian/GDevelop#3559]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
RuntimeError: invalid index into function table
    at wasm-function[2560]:0x7d03f
    at wasm-function[670]:0x2978b
    at InitialInstancesContainer.IterateOverInstancesWithZOrdering.InitialInstancesContainer.IterateOverInstancesWithZOrdering [as iterateOverInstancesWithZOrdering] (file:///C:/Users/10127/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.126-d49d765ec05d0454b365031d793c1702647877d8:9:1023057)
    at e.value (file:///C:/Users/10127/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.4fcfcc97.chunk.js:1:1001276)
    at e.value (file:///C:/Users/10127/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.4fcfcc97.chunk.js:1:509740)
    at n.e._renderScene (file:///C:/Users/10127/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.4fcfcc97.chunk.js:1:536873)
    at n.e.restartSceneRendering (file:///C:/Users/10127/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.4fcfcc97.chunk.js:1:537297)
    at n.value (file:///C:/Users/10127/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.4fcfcc97.chunk.js:1:545872)
    at fi (file:///C:/Users/10127/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:221665)
    at xo (file:///C:/Users/10127/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:237686)
    at Co (file:///C:/Users/10127/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:242656)
    at Ua (file:///C:/Users/10127/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:266568)
    at Fa (file:///C:/Users/10127/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:266952)
    at Eu (file:///C:/Users/10127/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:273988)
    at wu (file:///C:/Users/10127/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:273368)
    at Iu (file:///C:/Users/10127/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:274747)
    at In (file:///C:/Users/10127/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:206434)
    at HTMLDocument.i (file:///C:/Users/10127/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/61.abbaebce.chunk.js:2:320861)
```

## Component stack (don't write anything here)
```

    in n
    in div
    in div
    in Unknown
    in Measure
    in i
    in a
    in n
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in l
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in u
    in f
    in m
    in m
    in m
    in m
    in s
    in n
    in t
    in de
    in n
    in Unknown
    in v
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.126-d49d765ec05d0454b365031d793c1702647877d8
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19042,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.126 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by ClementPasteau** [comment]
Hello 👋 

The component stack of this error refers to the Scene editor, and the stack indicates the error happened in C++ https://github.com/4ian/GDevelop/blob/d55392bd749c575fcd2bc8617d442cc5de5ffe8d/Core/GDCore/Project/InitialInstancesContainer.cpp#L44-L61

@Dippydo Could you tell us a big more details about what you were doing when the crash happened?

Thanks!
