### ISSUE TITLE
Crash in the editor

### ISSUE THREAD

**Issue by 4ian** [4ian/GDevelop#3675]
Added from a report on Discord by @TheGemDev 

## Error stack (don't write anything here)
```
RuntimeError: memory access out of bounds
    at wasm-function(258):0x24703
    at Variable.GetType.Variable.GetType (as getType) (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster%3D5.0.127-fff09fdbd030c1876e828d9b2c10c207629b19dc:9:869540)
    at n.value (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.380424b7.chunk.js:1:218802)
    at file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.380424b7.chunk.js:1:220911
    at n (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.380424b7.chunk.js:1:6328)
    at n.value (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.380424b7.chunk.js:1:220842)
    at Eo (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:239002)
    at xo (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:238795)
    at Co (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:242656)
    at Ua (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:266568)
    at Fa (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:266952)
    at Eu (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:273988)
    at wu (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:273368)
    at yu (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:272389)
    at qa (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:271258)
    at Object.enqueueSetState (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:220650)
    at n.w.setState (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:170934)
    at Object.o._onInstancesSelected (as onInstancesSelected) (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.380424b7.chunk.js:1:455523)
    at e._onDownInstance (as onDownInstance) (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.380424b7.chunk.js:1:522341)
    at t.%3Canonymous%3E (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.380424b7.chunk.js:1:1017695)
    at t.c.emit (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.85c37391.chunk.js:2:1092109)
    at t.dispatchEvent (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.85c37391.chunk.js:2:163535)
    at t.processPointerDown (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.85c37391.chunk.js:2:165514)
    at e.recursiveFindHit (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.85c37391.chunk.js:2:155450)
    at e.recursiveFindHit (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.85c37391.chunk.js:2:155234)
    at e.recursiveFindHit (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.85c37391.chunk.js:2:155234)
    at e.recursiveFindHit (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.85c37391.chunk.js:2:155234)
    at e.recursiveFindHit (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.85c37391.chunk.js:2:155234)
    at e.findHit (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.85c37391.chunk.js:2:155509)
    at t.processInteractive (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.85c37391.chunk.js:2:164141)
    at t.onPointerDown (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.85c37391.chunk.js:2:164843)
    at HTMLCanvasElement.i (file:/C:/Users/Unekwu/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:320861)
```

## Component stack (don't write anything here)
```

    in n
    in div
    in o
    in div
    in a
    in div
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in n
    in t
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in r
    in E
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in l
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in u
    in f
    in p
    in p
    in m
    in m
    in s
    in n
    in t
    in de
    in n
    in Unknown
    in v
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.127-fff09fdbd030c1876e828d9b2c10c207629b19dc
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19044,
* User Agent: Mozilla/5.0 (Windows NT 10.0%3B Win64%3B x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.127 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by Bouh** [comment]
Possibly same as these issues:
https://github.com/4ian/GDevelop/issues/2541
https://github.com/4ian/GDevelop/issues/2570

**Comment by 4ian** [comment]
I think we have some issues where the properties of some instances are still read even after the related objects and instances are deleted, or something like this.
