### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by foxytimenoob** [4ian/GDevelop#3687]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
RuntimeError: function signature mismatch
    at wasm-function[88]:0x1efd3
    at Resource.GetName.Resource.GetName [as getName] (file:///C:/Users/uxi/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.127-fff09fdbd030c1876e828d9b2c10c207629b19dc:9:831139)
    at _ (file:///C:/Users/uxi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.380424b7.chunk.js:1:1113745)
    at n.value (file:///C:/Users/uxi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.380424b7.chunk.js:1:205679)
    at file:///C:/Users/uxi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.380424b7.chunk.js:1:207218
    at file:///C:/Users/uxi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.380424b7.chunk.js:1:382327
    at Wi (file:///C:/Users/uxi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:228986)
    at wo (file:///C:/Users/uxi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:235826)
    at Co (file:///C:/Users/uxi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:242574)
    at Ua (file:///C:/Users/uxi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:266568)
    at Fa (file:///C:/Users/uxi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:266952)
    at Eu (file:///C:/Users/uxi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:273988)
    at wu (file:///C:/Users/uxi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:273368)
    at yu (file:///C:/Users/uxi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:272389)
    at qa (file:///C:/Users/uxi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:271258)
    at Object.enqueueSetState (file:///C:/Users/uxi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:220650)
    at n.w.setState (file:///C:/Users/uxi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:170934)
    at n.value (file:///C:/Users/uxi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.380424b7.chunk.js:1:571764)
    at file:///C:/Users/uxi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/local-app.ffcfb5aa.chunk.js:1:3040
    at c (file:///C:/Users/uxi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:287686)
    at Generator._invoke (file:///C:/Users/uxi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:287439)
    at Generator.next (file:///C:/Users/uxi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:288045)
    at r (file:///C:/Users/uxi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:187)
    at u (file:///C:/Users/uxi/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/63.b595d2fd.chunk.js:2:390)
```

## Component stack (don't write anything here)
```

    in Unknown
    in DropTarget(Component)
    in DragSource(DropTarget(Component))
    in Unknown
    in div
    in div
    in div
    in t
    in t
    in a
    in l
    in n
    in t
    in div
    in t
    in div
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in n
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in u
    in f
    in p
    in p
    in m
    in m
    in s
    in n
    in t
    in de
    in n
    in Unknown
    in v
    in t
    in m
    in n
    in n
    in n
    in DragDropContext(n)
    in n
    in s
```

## Other details
* IDE version: 5.0.127-fff09fdbd030c1876e828d9b2c10c207629b19dc
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19044,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.127 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by Bouh** [comment]
Hi @foxytimenoob 

Thank you for taking the time to report this issue.
We will need more info on this bug to fix it, what was the context before the app crashed? What you have tried to achieve?

**Comment by Silver-Streak** [comment]
Hello, there has not been a response to this after a month. @foxytimenoob do you still have this issue? Can you provide the detail Bouh asked for above?

If no response is received in 48 hours, this issue will be closed. Thanks!
