### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by GamerGab02** [4ian/GDevelop#3750]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
RuntimeError: memory access out of bounds
    at wasm-function[4397]:0x192bb3
    at wasm-function[4318]:0x19085c
    at wasm-function[3039]:0xa26df
    at wasm-function[3038]:0xa2642
    at wasm-function[1951]:0x50764
    at wasm-function[1860]:0x49ab4
    at wasm-function[1949]:0x4fb77
    at wasm-function[1892]:0x4c060
    at wasm-function[990]:0x30a6e
    at EventsList.SerializeTo.EventsList.SerializeTo [as serializeTo] (file:///C:/Users/sonia/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.128-60088ebafd094b00260d3ec7f199186160317b02:9:1174501)
    at a (file:///C:/Users/sonia/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.e462b047.chunk.js:1:25980)
    at o (file:///C:/Users/sonia/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.e462b047.chunk.js:1:407356)
    at new n (file:///C:/Users/sonia/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.e462b047.chunk.js:1:237826)
    at li (file:///C:/Users/sonia/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/62.f3ecbb75.chunk.js:2:243735)
    at xo (file:///C:/Users/sonia/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/62.f3ecbb75.chunk.js:2:258532)
    at jo (file:///C:/Users/sonia/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/62.f3ecbb75.chunk.js:2:265047)
    at Ua (file:///C:/Users/sonia/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/62.f3ecbb75.chunk.js:2:288959)
    at Fa (file:///C:/Users/sonia/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/62.f3ecbb75.chunk.js:2:289343)
    at Ou (file:///C:/Users/sonia/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/62.f3ecbb75.chunk.js:2:296379)
    at wu (file:///C:/Users/sonia/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/62.f3ecbb75.chunk.js:2:295759)
    at Cu (file:///C:/Users/sonia/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/62.f3ecbb75.chunk.js:2:297138)
    at Cn (file:///C:/Users/sonia/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/62.f3ecbb75.chunk.js:2:228825)
    at HTMLDocument.i (file:///C:/Users/sonia/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/62.f3ecbb75.chunk.js:2:367989)
```

## Component stack (don't write anything here)
```

    in n
    in ForwardRef
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in u
    in f
    in p
    in p
    in m
    in m
    in s
    in n
    in t
    in pe
    in n
    in Unknown
    in v
    in t
    in m
    in o
    in n
    in n
    in DragDropContext(n)
    in n
    in u
```

## Other details
* IDE version: 5.0.128-60088ebafd094b00260d3ec7f199186160317b02
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.22000,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.128 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by Bouh** [comment]
Hello @GamerGab02 

Can you tell us more about what you were trying to do before the crash?
This could help us to understand where the bug comes from.

**Comment by Silver-Streak** [comment]
Hello @GamerGab02 

Are you still experiencing this error? If so. Can you provide the details Bouh asked for above?

Due to the age of this issue, if no response is received in 48 hours, I'll go ahead and close it out.
