### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Nick8712** [4ian/GDevelop#3797]
Okay....I have absolutely no clue. I was just testing my game and it was unable to calculate 34-3 and then threw up this error.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
Invariant Violation: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at a (file:///C:/Users/nicho/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.22a20b01.chunk.js:2:281055)
    at s (file:///C:/Users/nicho/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.22a20b01.chunk.js:2:281325)
    at vi (file:///C:/Users/nicho/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.22a20b01.chunk.js:2:328226)
    at file:///C:/Users/nicho/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.22a20b01.chunk.js:2:333001
    at go (file:///C:/Users/nicho/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.22a20b01.chunk.js:2:339892)
    at jo (file:///C:/Users/nicho/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.22a20b01.chunk.js:2:348334)
    at Ua (file:///C:/Users/nicho/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.22a20b01.chunk.js:2:371600)
    at Fa (file:///C:/Users/nicho/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.22a20b01.chunk.js:2:371984)
    at _s (file:///C:/Users/nicho/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.22a20b01.chunk.js:2:379020)
    at ws (file:///C:/Users/nicho/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.22a20b01.chunk.js:2:378400)
    at gs (file:///C:/Users/nicho/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.22a20b01.chunk.js:2:377421)
    at qa (file:///C:/Users/nicho/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.22a20b01.chunk.js:2:376290)
    at Object.enqueueSetState (file:///C:/Users/nicho/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.22a20b01.chunk.js:2:325682)
    at t.w.setState (file:///C:/Users/nicho/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.22a20b01.chunk.js:2:275965)
    at HTMLDivElement.n._onResize (file:///C:/Users/nicho/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.0b6c06c2.chunk.js:2:437737)
    at file:///C:/Users/nicho/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.0b6c06c2.chunk.js:2:1031423
    at Array.forEach (<anonymous>)
    at file:///C:/Users/nicho/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.0b6c06c2.chunk.js:2:1031400
    at i (file:///C:/Users/nicho/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.22a20b01.chunk.js:2:502733)
```

## Component stack (don't write anything here)
```

    in div
    in div
    in r
    in div
    in a
    in div
    in t
    in div
    in div
    in t
    in t
    in div
    in t
    in div
    in r
    in div
    in a
    in Be
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in r
    in E
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in n
    in div
    in a
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in u
    in f
    in p
    in p
    in m
    in m
    in s
    in n
    in t
    in pe
    in n
    in Unknown
    in v
    in t
    in m
    in o
    in n
    in n
    in DragDropContext(n)
    in n
    in u
```

## Other details
* IDE version: 5.0.130-0a77e0264df5b53d57006bf308d770a1cfeb3096
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19043,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.130 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by Silver-Streak** [comment]
Hello. I am doing a review of old issues needing responses. Has this crash occurred again?

If you are no longer experiencing this issue, no further action is needed.  This issue will be closed if no response is received by Tuesday, June 21.
