### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by eemmaaa** [4ian/GDevelop#3804]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: e.slice(...).map is not a function
    at we (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.fa82a783.chunk.js:1:1160282)
    at file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.fa82a783.chunk.js:1:1164652
    at t.value (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.acb5c5de.chunk.js:2:423955)
    at _o (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.acb5c5de.chunk.js:2:344034)
    at Oo (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.acb5c5de.chunk.js:2:343827)
    at jo (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.acb5c5de.chunk.js:2:347688)
    at Ua (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.acb5c5de.chunk.js:2:371600)
    at Fa (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.acb5c5de.chunk.js:2:371984)
    at _s (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.acb5c5de.chunk.js:2:379020)
    at ws (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.acb5c5de.chunk.js:2:378400)
    at gs (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.acb5c5de.chunk.js:2:377421)
    at qa (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.acb5c5de.chunk.js:2:376290)
    at to (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.acb5c5de.chunk.js:2:337018)
    at file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.fa82a783.chunk.js:1:163837
    at c (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.acb5c5de.chunk.js:2:392720)
    at Generator._invoke (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.acb5c5de.chunk.js:2:392473)
    at Generator.next (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.acb5c5de.chunk.js:2:393079)
    at r (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.acb5c5de.chunk.js:2:235)
    at s (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.acb5c5de.chunk.js:2:438)
```

## Component stack (don't write anything here)
```

    in t
    in ForwardRef
    in ForwardRef
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in u
    in f
    in p
    in p
    in m
    in m
    in s
    in n
    in t
    in pe
    in n
    in Unknown
    in v
    in t
    in m
    in o
    in n
    in n
    in DragDropContext(n)
    in n
    in u
```

## Other details
* IDE version: 5.0.130-0a77e0264df5b53d57006bf308d770a1cfeb3096
* Arch: x64,
* Platform Name: darwin,
* System Version: 10.16.0,
* User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16_0) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.130 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by 4ian** [comment]
Hi @eemmaaa, do you remember what you were doing before the bug happened? Thanks!

**Comment by ClementPasteau** [comment]
From a quick analysis of the stack trace, it looks like this is happening on the HomePage, when displaying one of the 3 carousels:
- tutorials
- examples
- showcased games

https://github.com/4ian/GDevelop/blob/6cf737ac70077b0a674156fe00d1083faea93e6b/newIDE/app/src/MainFrame/EditorContainers/HomePage/index.js#L101-L111

The only way I was able to reproduce this type of error is if the element being sliced/mapped is not an array (a string for instance) but I can't see how this can happen, because the backend services for those 3 elements always return an array before storing it in their context (or do they?)
