### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by s00ar** [4ian/GDevelop#3816]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
RuntimeError: memory access out of bounds
    at wasm-function[265]:0x25283
    at Variable.GetType.Variable.GetType [as getType] (file:///C:/Users/San/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.130-0a77e0264df5b53d57006bf308d770a1cfeb3096:9:888155)
    at n.value (file:///C:/Users/San/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.259c49c3.chunk.js:1:206881)
    at file:///C:/Users/San/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.259c49c3.chunk.js:1:208990
    at n (file:///C:/Users/San/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.259c49c3.chunk.js:1:624)
    at n.value (file:///C:/Users/San/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.259c49c3.chunk.js:1:208921)
    at _o (file:///C:/Users/San/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.22a20b01.chunk.js:2:344034)
    at Oo (file:///C:/Users/San/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.22a20b01.chunk.js:2:343827)
    at jo (file:///C:/Users/San/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.22a20b01.chunk.js:2:347688)
    at Ua (file:///C:/Users/San/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.22a20b01.chunk.js:2:371600)
    at Fa (file:///C:/Users/San/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.22a20b01.chunk.js:2:371984)
    at _s (file:///C:/Users/San/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.22a20b01.chunk.js:2:379020)
    at ws (file:///C:/Users/San/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.22a20b01.chunk.js:2:378400)
    at Cs (file:///C:/Users/San/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.22a20b01.chunk.js:2:379779)
    at Cn (file:///C:/Users/San/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.22a20b01.chunk.js:2:311466)
    at HTMLDocument.i (file:///C:/Users/San/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.22a20b01.chunk.js:2:502733)
```

## Component stack (don't write anything here)
```

    in n
    in div
    in a
    in div
    in r
    in div
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in n
    in t
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in r
    in E
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in u
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in u
    in f
    in p
    in p
    in m
    in m
    in s
    in n
    in t
    in pe
    in n
    in Unknown
    in v
    in t
    in m
    in o
    in n
    in n
    in DragDropContext(n)
    in n
    in u
```

## Other details
* IDE version: 5.0.130-0a77e0264df5b53d57006bf308d770a1cfeb3096
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19043,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.130 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by Bouh** [comment]
Hello @s00ar 
Do you remember what you were doing before the bug happened?
Thanks!

**Comment by s00ar** [comment]
Hi there. I was actually working on sprites when it happened. I was unnable
to get screenshots but I´ll try to get them next time. Cheers for the
excellent work!
