### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by iozkul** [4ian/GDevelop#3863]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
RuntimeError: memory access out of bounds
    at wasm-function[3116]:0xa7bc1
    at wasm-function[908]:0x2eab0
    at ObjectMetadata.IsUnsupportedBaseObjectCapability.ObjectMetadata.IsUnsupportedBaseObjectCapability [as isUnsupportedBaseObjectCapability] (file:///C:/Users/io/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.131-6cf737ac70077b0a674156fe00d1083faea93e6b:9:1129100)
    at T (file:///C:/Users/io/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.e87253b7.chunk.js:1:1014836)
    at Vi (file:///C:/Users/io/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.396465fc.chunk.js:2:334018)
    at wo (file:///C:/Users/io/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.396465fc.chunk.js:2:340858)
    at jo (file:///C:/Users/io/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.396465fc.chunk.js:2:347606)
    at Ua (file:///C:/Users/io/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.396465fc.chunk.js:2:371600)
    at Fa (file:///C:/Users/io/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.396465fc.chunk.js:2:371984)
    at _s (file:///C:/Users/io/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.396465fc.chunk.js:2:379020)
    at ws (file:///C:/Users/io/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.396465fc.chunk.js:2:378400)
    at Cs (file:///C:/Users/io/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.396465fc.chunk.js:2:379779)
    at Cn (file:///C:/Users/io/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.396465fc.chunk.js:2:311466)
    at HTMLDocument.i (file:///C:/Users/io/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.396465fc.chunk.js:2:502733)
```

## Component stack (don't write anything here)
```

    in T
    in n
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in div
    in Unknown
    in n
    in u
    in f
    in p
    in p
    in m
    in m
    in s
    in n
    in t
    in pe
    in n
    in Unknown
    in v
    in t
    in m
    in o
    in n
    in n
    in DragDropContext(n)
    in n
    in u
```

## Other details
* IDE version: 5.0.131-6cf737ac70077b0a674156fe00d1083faea93e6b
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.22000,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.131 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by Oxey405** [comment]
Hello ! Can you provide the description of this bug and how to reproduce it please ?

**Comment by Silver-Streak** [comment]
Hello. I am doing a review of old issues needing responses from the issue author.  If you are still experiencing this issue, please provide a description of how to reproduce it so we can look further.

If you are no longer experiencing this issue, no further action is needed.  This issue will be closed if no response is received by Tuesday, June 21.
