### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by MasterKurapika** [4ian/GDevelop#3894]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: e.slice(...).map is not a function
    at we (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.77d4a506.chunk.js:1:1216802)
    at file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.77d4a506.chunk.js:1:1221172
    at t.value (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.5456dfd3.chunk.js:2:423955)
    at _o (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.5456dfd3.chunk.js:2:344034)
    at Oo (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.5456dfd3.chunk.js:2:343827)
    at jo (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.5456dfd3.chunk.js:2:347688)
    at Ua (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.5456dfd3.chunk.js:2:371600)
    at Fa (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.5456dfd3.chunk.js:2:371984)
    at _s (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.5456dfd3.chunk.js:2:379020)
    at ws (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.5456dfd3.chunk.js:2:378400)
    at gs (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.5456dfd3.chunk.js:2:377421)
    at qa (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.5456dfd3.chunk.js:2:376290)
    at to (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.5456dfd3.chunk.js:2:337018)
    at file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.77d4a506.chunk.js:1:177265
    at c (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.5456dfd3.chunk.js:2:392720)
    at Generator._invoke (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.5456dfd3.chunk.js:2:392473)
    at Generator.next (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.5456dfd3.chunk.js:2:393079)
    at r (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.5456dfd3.chunk.js:2:235)
    at s (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.5456dfd3.chunk.js:2:438)
```

## Component stack (don't write anything here)
```

    in t
    in ForwardRef
    in ForwardRef
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in n
    in u
    in f
    in p
    in p
    in m
    in m
    in s
    in n
    in t
    in pe
    in n
    in Unknown
    in v
    in t
    in m
    in o
    in n
    in n
    in DragDropContext(n)
    in n
    in u
```

## Other details
* IDE version: 5.0.132-bb3abdb1fa85a2d9e89e5053ae47deef1008299a
* Arch: x64,
* Platform Name: darwin,
* System Version: 10.16.0,
* User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16_0) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.132 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36,

**Comment by Bouh** [comment]
Maybe an issue on the homepage according to the short Component stack.

**Comment by Bouh** [comment]
It seems that there is a similar problem with the same signs.
https://github.com/4ian/GDevelop/issues/3804
