### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by SamrayX** [4ian/GDevelop#4052]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: Cannot read properties of undefined (reading 'name')
    at https://editor.gdevelop.io/static/js/1.f1c85f77.chunk.js:1:1253393
    at Array.map (<anonymous>)
    at Ue (https://editor.gdevelop.io/static/js/1.f1c85f77.chunk.js:1:1253367)
    at Yo (https://editor.gdevelop.io/static/js/64.46cf5bec.chunk.js:2:394056)
    at za (https://editor.gdevelop.io/static/js/64.46cf5bec.chunk.js:2:402948)
    at ks (https://editor.gdevelop.io/static/js/64.46cf5bec.chunk.js:2:441398)
    at mu (https://editor.gdevelop.io/static/js/64.46cf5bec.chunk.js:2:432922)
    at vu (https://editor.gdevelop.io/static/js/64.46cf5bec.chunk.js:2:432847)
    at su (https://editor.gdevelop.io/static/js/64.46cf5bec.chunk.js:2:429856)
    at https://editor.gdevelop.io/static/js/64.46cf5bec.chunk.js:2:381334
    at t.unstable_runWithPriority (https://editor.gdevelop.io/static/js/64.46cf5bec.chunk.js:2:456561)
    at $i (https://editor.gdevelop.io/static/js/64.46cf5bec.chunk.js:2:381043)
    at Qi (https://editor.gdevelop.io/static/js/64.46cf5bec.chunk.js:2:381279)
    at Ji (https://editor.gdevelop.io/static/js/64.46cf5bec.chunk.js:2:381214)
    at nu (https://editor.gdevelop.io/static/js/64.46cf5bec.chunk.js:2:426638)
    at ba (https://editor.gdevelop.io/static/js/64.46cf5bec.chunk.js:2:398429)
    at https://editor.gdevelop.io/static/js/1.f1c85f77.chunk.js:1:1250738
    at l (https://editor.gdevelop.io/static/js/64.46cf5bec.chunk.js:2:458448)
    at Generator._invoke (https://editor.gdevelop.io/static/js/64.46cf5bec.chunk.js:2:458236)
    at Generator.next (https://editor.gdevelop.io/static/js/64.46cf5bec.chunk.js:2:458873)
    at r (https://editor.gdevelop.io/static/js/64.46cf5bec.chunk.js:2:419)
    at s (https://editor.gdevelop.io/static/js/64.46cf5bec.chunk.js:2:630)
```

## Component stack (don't write anything here)
```

    in Ue
    in div
    in r
    in div
    in a
    in c
    in Ze
    in div
    in a
    in div
    in ForwardRef
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in S
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in tt
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in n
    in t
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in r
    in v
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in c
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in n
    in d
    in j
    in b
    in b
    in h
    in g
    in c
    in n
    in t
    in pe
    in n
    in Unknown
    in g
    in t
    in l
    in o
    in n
    in n
    in DragDropContext(n)
    in n
    in c
```

## Other details
* IDE version: 5.0.136-beac19089f02a35e011506b8fca21001931eac3f
* Arch: Unknown architecture (web-app),
* Platform Name: Linux x86_64,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (X11; CrOS x86_64 14695.85.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36,

**Comment by AlexandreSi** [comment]
Thanks for reporting this crash.

Could you provide us more info on what you were trying to do when it happened?

**Comment by ClementPasteau** [comment]
Same issue as #4067 - now fixed
