### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by cathymartin** [4ian/GDevelop#4061]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: Cannot read properties of undefined (reading 'name')
    at file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.b3425a03.chunk.js:1:1255427
    at Array.map (<anonymous>)
    at Ue (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.b3425a03.chunk.js:1:1255401)
    at Yo (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.dcb8022f.chunk.js:2:394056)
    at za (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.dcb8022f.chunk.js:2:402948)
    at ks (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.dcb8022f.chunk.js:2:441398)
    at mu (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.dcb8022f.chunk.js:2:432922)
    at vu (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.dcb8022f.chunk.js:2:432847)
    at su (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.dcb8022f.chunk.js:2:429856)
    at file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.dcb8022f.chunk.js:2:381334
    at t.unstable_runWithPriority (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.dcb8022f.chunk.js:2:456561)
    at $i (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.dcb8022f.chunk.js:2:381043)
    at Qi (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.dcb8022f.chunk.js:2:381279)
    at Ji (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.dcb8022f.chunk.js:2:381214)
    at nu (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.dcb8022f.chunk.js:2:426638)
    at ba (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.dcb8022f.chunk.js:2:398429)
    at file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.b3425a03.chunk.js:1:1252772
    at l (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.dcb8022f.chunk.js:2:458448)
    at Generator._invoke (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.dcb8022f.chunk.js:2:458236)
    at Generator.next (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.dcb8022f.chunk.js:2:458873)
    at r (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.dcb8022f.chunk.js:2:419)
    at s (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.dcb8022f.chunk.js:2:630)
```

## Component stack (don't write anything here)
```

    in Ue
    in div
    in r
    in div
    in a
    in c
    in Ze
    in div
    in a
    in div
    in ForwardRef
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in S
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in tt
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in n
    in t
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in r
    in v
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in c
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in n
    in d
    in j
    in b
    in b
    in h
    in g
    in c
    in n
    in t
    in pe
    in n
    in Unknown
    in g
    in t
    in l
    in o
    in n
    in n
    in DragDropContext(n)
    in n
    in c
```

## Other details
* IDE version: 5.0.138-81ef11163db977d9e3821c16568930651e50c580
* Arch: x64,
* Platform Name: darwin,
* System Version: 12.4.0,
* User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.138 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36,

**Comment by AlexandreSi** [comment]
Thanks for reporting this crash.

Could you provide us more info on what you were trying to do when it happened?

**Comment by ClementPasteau** [comment]
Same issue as #4067 - now fixed
