### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by muyinz** [4ian/GDevelop#4081]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
RuntimeError: null function or function signature mismatch
    at file:///C:/Users/muyinz/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.wasm?cache-buster=5.0.138-81ef11163db977d9e3821c16568930651e50c580:wasm-function[39]:0x1f79f
    at Module._emscripten_bind_InitialInstanceJSFunctor___destroy___0 (file:///C:/Users/muyinz/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.138-81ef11163db977d9e3821c16568930651e50c580:9:365181)
    at InitialInstanceJSFunctor.__destroy__.InitialInstanceJSFunctor.__destroy__ (file:///C:/Users/muyinz/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.138-81ef11163db977d9e3821c16568930651e50c580:9:1066903)
    at Object.destroy (file:///C:/Users/muyinz/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.138-81ef11163db977d9e3821c16568930651e50c580:9:841765)
    at InitialInstanceJSFunctor.proto.delete (file:///C:/Users/muyinz/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.138-81ef11163db977d9e3821c16568930651e50c580:9:1478381)
    at e.value (file:///C:/Users/muyinz/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.f636414a.chunk.js:1:1120239)
    at n.value (file:///C:/Users/muyinz/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.f636414a.chunk.js:1:645356)
    at file:///C:/Users/muyinz/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.a0030cea.chunk.js:2:420658
    at ls (file:///C:/Users/muyinz/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.a0030cea.chunk.js:2:420699)
    at gs (file:///C:/Users/muyinz/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.a0030cea.chunk.js:2:422544)
    at wu (file:///C:/Users/muyinz/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.a0030cea.chunk.js:2:436066)
    at t.unstable_runWithPriority (file:///C:/Users/muyinz/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.a0030cea.chunk.js:2:456561)
    at $i (file:///C:/Users/muyinz/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.a0030cea.chunk.js:2:381043)
    at _u (file:///C:/Users/muyinz/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.a0030cea.chunk.js:2:433924)
    at su (file:///C:/Users/muyinz/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.a0030cea.chunk.js:2:430055)
    at file:///C:/Users/muyinz/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.a0030cea.chunk.js:2:381334
    at t.unstable_runWithPriority (file:///C:/Users/muyinz/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.a0030cea.chunk.js:2:456561)
    at $i (file:///C:/Users/muyinz/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.a0030cea.chunk.js:2:381043)
    at Qi (file:///C:/Users/muyinz/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.a0030cea.chunk.js:2:381279)
    at Ji (file:///C:/Users/muyinz/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.a0030cea.chunk.js:2:381214)
    at M (file:///C:/Users/muyinz/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.a0030cea.chunk.js:2:450326)
    at Qt (file:///C:/Users/muyinz/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.a0030cea.chunk.js:2:358497)
    at HTMLDocument.i (file:///C:/Users/muyinz/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.a0030cea.chunk.js:2:568873)
```

## Component stack (don't write anything here)
```

    in n
    in div
    in div
    in Unknown
    in Measure
    in i
    in o
    in n
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in c
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in n
    in d
    in j
    in b
    in b
    in h
    in g
    in c
    in n
    in t
    in pe
    in n
    in Unknown
    in g
    in t
    in l
    in o
    in n
    in n
    in DragDropContext(n)
    in n
    in c
```

## Other details
* IDE version: 5.0.138-81ef11163db977d9e3821c16568930651e50c580
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19042,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.138 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36,

**Comment by Bouh** [comment]
Hi @muyinz 
Please write a short description of when the error occurred if you have an idea and if possible how to reproduce it, or a project to reproduce it.
Thanks
