### ISSUE TITLE
Deleting object with Physics2 behavior during doStepPreEvents results in uncaught errors

### ISSUE THREAD

**Issue by krunkster** [4ian/GDevelop#4095]
## Describe the bug
If you have an object with Physics2 behavior and another behavior that deletes the object during the doStepPreEvents logic, it will result in uncaught Type errors for physics2runtimebehavior.ts and box2d.js
`physics2runtimebehavior.ts:802 Uncaught TypeError: Cannot read properties of null (reading 'GetPosition')
    at b.doStepPreEvents (physics2runtimebehavior.ts:802:20)
    at b.stepPreEvents (runtimebehavior.ts:103:14)
    at m.stepBehaviorsPreEvents (runtimeobject.ts:1613:28)
    at g._updateObjectsPreEvents (runtimescene.ts:774:35)
    at g.renderAndStep (runtimescene.ts:503:12)
    at a.step (scenestack.ts:38:24)
    at runtimegame.ts:620:32
    at i (runtimegame-pixi-renderer.ts:739:14)
doStepPreEvents @ physics2runtimebehavior.ts:802
stepPreEvents @ runtimebehavior.ts:103
stepBehaviorsPreEvents @ runtimeobject.ts:1613
_updateObjectsPreEvents @ runtimescene.ts:774
renderAndStep @ runtimescene.ts:503
step @ scenestack.ts:38
(anonymous) @ runtimegame.ts:620
i @ runtimegame-pixi-renderer.ts:739
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
requestAnimationFrame (async)
i @ runtimegame-pixi-renderer.ts:735
box2d.js:3 Uncaught TypeError: Cannot read properties of null (reading 'GetPosition')
    at b.doStepPreEvents (physics2runtimebehavior.ts:802:20)
    at b.stepPreEvents (runtimebehavior.ts:103:14)
    at m.stepBehaviorsPreEvents (runtimeobject.ts:1613:28)
    at g._updateObjectsPreEvents (runtimescene.ts:774:35)
    at g.renderAndStep (runtimescene.ts:503:12)
    at a.step (scenestack.ts:38:24)
    at runtimegame.ts:620:32
    at i (runtimegame-pixi-renderer.ts:739:14)`

## To Reproduce
[issue-remove-physics-obj-prestep.zip](https://github.com/4ian/GDevelop/files/9087834/issue-remove-physics-obj-prestep.zip)
1. Load the example provided
2. Run preview
3. open the console (CTRL-SHIFT-I)
4. After a couple of seconds the ball object will be deleted and uncaught exceptions will appear in console

There is an extension included in the zip which is a private extension I wrote to automatically remove objects after a set period of time or accumulation in amount.  I presume this extension is causing a race condition with the other behaviors on the object that are scheduled to run their own doStepPreEvents. However, since I don't see a way to fix the behaviors execution order, or to remove behaviors from the parent object inside of doStepPreEvents then I would consider this a bug.

I'm also suspicious that these uncaught errors could cause a complete simulation hang and crash the application as I saw in the logs I provided in #4060

## Other details
* Windows 
* 1.5.0.138 (test fix build for #4060)

**Comment by krunkster** [comment]
OK, so I just discovered there is a "doStepPostEvents" phase, and moving the logic for the auto remover to that phase, does make this issue go away. However, I'm still worried that if another behavior on the same object also tries to do something during the "doStepPostEvents" phase that it could result in the same set of errors.

**Comment by fannieyan** [comment]
Hello @krunkster 

Thanks a lot for your input!
I could not reproduce the bug (tested on the experimental build for mac I sent and on the branch we worked on). Should it happen every time the preview is launched?

We will add some more test cases though to cover this edge case and see what comes out of it.

**Comment by fannieyan** [comment]
Update:
We found the issue on this one and will push changes on #4074 ! Moving the remove logic in preEvent should become fine again :)

**Comment by fannieyan** [comment]
I am closing this issue as we merged #4074 with a fix.
Thank you for your help! :)
