### ISSUE TITLE
Editor Crash when loading a project with a new tilemap

### ISSUE THREAD

**Issue by Silver-Streak** [4ian/GDevelop#4193]
Note: This issue does not appear to occur on 5.0.138. The same project that has this crash in 139 will load fine in 138, and repeating these steps will have the tilemap render normally on number 6 below in 138. Seems like this may be somehow related to the collision changes, @D8H 

To reproduce:
1. Create a tilemap in Tiled. 
2. Export as json (Tiled 1.9 will require you to fully type out .json, otherwise it'll save as .tmj)
3. Create a new GDevelop project.
4. Create a new Tilemap object.
5. Import the tilemap and atlas file (and tileset as desired. Embedding the tileset does not matter.)
6. The Tilemap *will not display* when you drag it to the scene. Although it will show up in the instances list.
7. Save the project
8. Close the project.
9. Reopen the project. The scene editor will crash.

Video:
https://user-images.githubusercontent.com/24237149/183638131-b7cf85b5-bfa3-47fe-925d-1888b9eaeb15.mp4

Created project, tilemap, and atlas:
[TileMapEditorCrash.zip](https://github.com/4ian/GDevelop/files/9289971/TileMapEditorCrash.zip)

Side note: 
Editor crashes are now too long for the Github Issue creation via URL. I had to copy and decode the URL to get the below error stack, this is probably an important long-term issue:
![image](https://user-images.githubusercontent.com/24237149/183638382-98e04ff7-106b-4762-8bca-1b201fcee44d.png)

You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: Cannot read properties of null (reading 'CompositeRectTileLayer')
    at new RenderedTileMapInstance (C:\Users\silve\AppData\Local\Programs\gdevelop\resources\GDJS\Runtime\Extensions\TileMap\JsExtension.js:797:38)
    at Object.createNewInstanceRenderer (file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.8ef70361.chunk.js:1:58969)
    at e.getRendererOfInstance (file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.8ef70361.chunk.js:1:1160055)
    at InitialInstanceJSFunctor.instancesRenderer.invoke (file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.8ef70361.chunk.js:1:1161878)
    at 3052 (file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.139-0ffc88a4706e4b5f2c96f6d1492d2f59eb2b2a6e:9:17964)
    at _emscripten_asm_const_iii (file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.139-0ffc88a4706e4b5f2c96f6d1492d2f59eb2b2a6e:9:28312)
    at file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.wasm?cache-buster=5.0.139-0ffc88a4706e4b5f2c96f6d1492d2f59eb2b2a6e:wasm-function[1603]:0x3c8dd
    at file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.wasm?cache-buster=5.0.139-0ffc88a4706e4b5f2c96f6d1492d2f59eb2b2a6e:wasm-function[59]:0x1ffe0
    at file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.wasm?cache-buster=5.0.139-0ffc88a4706e4b5f2c96f6d1492d2f59eb2b2a6e:wasm-function[2695]:0x8236c
    at file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.wasm?cache-buster=5.0.139-0ffc88a4706e4b5f2c96f6d1492d2f59eb2b2a6e:wasm-function[696]:0x2b38d
    at InitialInstancesContainer.IterateOverInstancesWithZOrdering.InitialInstancesContainer.IterateOverInstancesWithZOrdering [as iterateOverInstancesWithZOrdering] (file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.139-0ffc88a4706e4b5f2c96f6d1492d2f59eb2b2a6e:9:1063560)
    at e.value (file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.8ef70361.chunk.js:1:1163765)
    at e.value (file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.8ef70361.chunk.js:1:612182)
    at n.e._renderScene (file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.8ef70361.chunk.js:1:639692)
    at n.value (file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.8ef70361.chunk.js:1:647864)
    at xo (file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:386253)
    at Ba (file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:404863)
    at ks (file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:441563)
    at mu (file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:433005)
    at vu (file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:432930)
    at su (file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:429939)
    at file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:381417
    at t.unstable_runWithPriority (file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:456644)
    at $i (file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:381126)
    at Qi (file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:381362)
    at Ji (file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:381297)
    at nu (file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:426721)
    at Object.enqueueSetState (file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:385125)
    at s._.setState (file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:330877)
    at file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/0.33e62b4c.chunk.js:2:640538
    at i (file:///C:/Users/silve/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:568956)
```

## Component stack (don't write anything here)
```

    in n
    in div
    in div
    in Unknown
    in Measure
    in i
    in o
    in n
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in c
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in n
    in d
    in j
    in f
    in j
    in h
    in g
    in c
    in n
    in t
    in be
    in n
    in Unknown
    in g
    in t
    in l
    in o
    in n
    in n
    in DragDropContext(n)
    in n
    in c
```

## Other details
* IDE version: 5.0.139-0ffc88a4706e4b5f2c96f6d1492d2f59eb2b2a6e
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19044,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.139 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36,
        &title=Crash while using an editor

**Comment by D8H** [comment]
Hello Silver, thank you for reporting this.

Some fixes were done since the release that can help to see errors visually or in the console. Please can you try with a nightly?
With a nightly, you should see a red cross icon instead of nothing when adding an instance. If you do, an error should be logged in the console.

I can open the project with the 139 and the tile map object shows. I'm not sure how to reproduce.

![image](https://user-images.githubusercontent.com/2611977/183641247-90fed5c8-36fb-41ed-8c70-9a0de04ede54.png)

**Comment by Silver-Streak** [comment]
Confirmed this is solved in the current nightly.

**Comment by Silver-Streak** [comment]
As this is resolved inthe current nightly, closing out this issue.
