### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Alejandro1965** [4ian/GDevelop#4203]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
RuntimeError: table index is out of bounds
    at file:///C:/Program%20Files/GDevelop/resources/app.asar/www/libGD.wasm?cache-buster=5.0.139-0ffc88a4706e4b5f2c96f6d1492d2f59eb2b2a6e:wasm-function[87]:0x20886
    at ExpressionNode.Visit.ExpressionNode.Visit [as visit] (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.139-0ffc88a4706e4b5f2c96f6d1492d2f59eb2b2a6e:9:1298975)
    at file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/1.8ef70361.chunk.js:1:955828
    at n (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/1.8ef70361.chunk.js:1:1206)
    at A (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/1.8ef70361.chunk.js:1:955342)
    at children (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/1.8ef70361.chunk.js:1:958171)
    at file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/1.8ef70361.chunk.js:1:89107
    at Yo (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:394139)
    at ks (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:440245)
    at mu (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:433005)
    at vu (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:432930)
    at su (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:429939)
    at file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:381417
    at t.unstable_runWithPriority (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:456644)
    at $i (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:381126)
    at Qi (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:381362)
    at Ji (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:381297)
    at nu (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:426721)
    at Object.enqueueSetState (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:385125)
    at t._.setState (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:330877)
    at HTMLDivElement.n._onResize (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/0.33e62b4c.chunk.js:2:445988)
    at file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/0.33e62b4c.chunk.js:2:1236530
    at Array.forEach (<anonymous>)
    at file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/0.33e62b4c.chunk.js:2:1236507
    at i (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/64.e29dea9d.chunk.js:2:568956)
```

## Component stack (don't write anything here)
```

    in Unknown
    in DropTarget(Component)
    in DragSource(DropTarget(Component))
    in Unknown
    in Unknown
    in div
    in Unknown
    in DropTarget(Component)
    in Unknown
    in g
    in div
    in Unknown
    in n
    in div
    in div
    in div
    in n
    in div
    in Unknown
    in DropTarget(Component)
    in DragSource(DropTarget(Component))
    in Unknown
    in span
    in div
    in div
    in div
    in div
    in div
    in t
    in DragSource(t)
    in div
    in div
    in t
    in DropTarget(t)
    in div
    in div
    in t
    in t
    in Scrolling(t)
    in div
    in t
    in div
    in t
    in ce
    in Unknown
    in z
    in div
    in n
    in div
    in n
    in c
    in n
    in ForwardRef(K)
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in n
    in d
    in j
    in f
    in j
    in h
    in g
    in c
    in n
    in t
    in be
    in n
    in Unknown
    in g
    in t
    in l
    in o
    in n
    in n
    in DragDropContext(n)
    in n
    in c
```

## Other details
* IDE version: 5.0.139-0ffc88a4706e4b5f2c96f6d1492d2f59eb2b2a6e
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19044,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.139 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36,

**Comment by Silver-Streak** [comment]
Hello! 

Thank you for reporting this bug. however, as mentioned at the top of the bug submission, in order for the devs and contributors to assist you need to provide what you were doing before the crash, and exact steps to recreate it (if possible).

If you can, please provide that info so folks can better help.

**Comment by Silver-Streak** [comment]
Just doing one more check on the above. If no response is received within 2 days this issue will be closed.
