### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Yggddrassill** [4ian/GDevelop#4210]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
RuntimeError: memory access out of bounds
    at file:///C:/Users/ahhue/AppData/Local/Programs/GDevelop/resources/app.asar/www/libGD.wasm?cache-buster=5.0.140-a47ec5199eab60ac473453c8705686f737abff6a:wasm-function[39]:0x1fa90
    at InitialInstanceJSFunctor.__destroy__.InitialInstanceJSFunctor.__destroy__ (file:///C:/Users/ahhue/AppData/Local/Programs/GDevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.140-a47ec5199eab60ac473453c8705686f737abff6a:9:1071881)
    at Object.destroy (file:///C:/Users/ahhue/AppData/Local/Programs/GDevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.140-a47ec5199eab60ac473453c8705686f737abff6a:9:846371)
    at InitialInstanceJSFunctor.proto.delete (file:///C:/Users/ahhue/AppData/Local/Programs/GDevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.140-a47ec5199eab60ac473453c8705686f737abff6a:9:1486864)
    at n.value (file:///C:/Users/ahhue/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/1.7973603f.chunk.js:1:1197506)
    at file:///C:/Users/ahhue/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:424152
    at ls (file:///C:/Users/ahhue/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:424193)
    at gs (file:///C:/Users/ahhue/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:426038)
    at wu (file:///C:/Users/ahhue/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:439560)
    at t.unstable_runWithPriority (file:///C:/Users/ahhue/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:460055)
    at $i (file:///C:/Users/ahhue/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:384537)
    at _u (file:///C:/Users/ahhue/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:437418)
    at su (file:///C:/Users/ahhue/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:433549)
    at file:///C:/Users/ahhue/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:384828
    at t.unstable_runWithPriority (file:///C:/Users/ahhue/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:460055)
    at $i (file:///C:/Users/ahhue/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:384537)
    at Qi (file:///C:/Users/ahhue/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:384773)
    at Ji (file:///C:/Users/ahhue/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:384708)
    at M (file:///C:/Users/ahhue/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:453820)
    at Qt (file:///C:/Users/ahhue/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:361991)
    at HTMLDocument.i (file:///C:/Users/ahhue/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:572367)
```

## Component stack (don't write anything here)
```

    in n
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in r
    in x
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in c
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in Unknown
    in d
    in j
    in f
    in j
    in j
    in g
    in c
    in Be
    in n
    in t
    in he
    in n
    in Unknown
    in g
    in t
    in l
    in o
    in n
    in n
    in DragDropContext(n)
    in n
    in c
```

## Other details
* IDE version: 5.0.140-a47ec5199eab60ac473453c8705686f737abff6a
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19043,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.140 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36,

**Comment by Bouh** [comment]
Hi @Yggddrassill

Is this crash similar to [this one](https://github.com/4ian/GDevelop/issues/4192)?
In this case we keep only one bug report to avoid duplicates.

Thanks
