### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by GladiosAnimations** [4ian/GDevelop#4211]
=> i typed in the asset serach bar "particle" and scrolled down and chose pixel flame and boom. error

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at i (file:///C:/Users/FRANEK/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:167146)
    at e.value (file:///C:/Users/FRANEK/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.7973603f.chunk.js:1:357692)
    at file:///C:/Users/FRANEK/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.7973603f.chunk.js:1:219203
    at Array.map (<anonymous>)
    at p (file:///C:/Users/FRANEK/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.7973603f.chunk.js:1:219108)
    at file:///C:/Users/FRANEK/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/1.7973603f.chunk.js:1:220979
    at us (file:///C:/Users/FRANEK/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:422882)
    at Ou (file:///C:/Users/FRANEK/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:441771)
    at t.unstable_runWithPriority (file:///C:/Users/FRANEK/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:460055)
    at $i (file:///C:/Users/FRANEK/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:384537)
    at xu (file:///C:/Users/FRANEK/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:441528)
    at file:///C:/Users/FRANEK/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:441439
    at U (file:///C:/Users/FRANEK/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:458993)
    at MessagePort.x.port1.onmessage (file:///C:/Users/FRANEK/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:457749)
```

## Component stack (don't write anything here)
```

    in Le
    in div
    in n
    in div
    in a
    in c
    in Be
    in div
    in a
    in div
    in ForwardRef
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in S
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in Qe
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in n
    in t
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in r
    in x
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in c
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in Unknown
    in d
    in j
    in f
    in j
    in j
    in g
    in c
    in Be
    in n
    in t
    in he
    in n
    in Unknown
    in g
    in t
    in l
    in o
    in n
    in n
    in DragDropContext(n)
    in n
    in c
```

## Other details
* IDE version: 5.0.140-a47ec5199eab60ac473453c8705686f737abff6a
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19043,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.140 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36,

**Comment by tristanbob** [comment]
I can confirm this bug exists.  I tried adding the "basic flame" particle.

![image](https://user-images.githubusercontent.com/8879811/185554785-983cc873-7bc8-4408-b813-7bb8908975df.png)

**Comment by 4ian** [comment]
Should be fixed - or fixed soon - that was an error in the asset store content. Thanks for reporting and thanks @tristanbob for reproducing the issue!

**Comment by Bouh** [comment]
It works now.
