### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by WhyOni** [4ian/GDevelop#4221]
I was using GDevelop on mac then suddenly resource editor crashed

## Error stack (don't write anything here)
```
RuntimeError: memory access out of bounds
    at file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/libGD.wasm?cache-buster=5.0.140-a47ec5199eab60ac473453c8705686f737abff6a:wasm-function[46]:0x1fc24
    at Resource.GetName.Resource.GetName [as getName] (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/libGD.js?cache-buster=5.0.140-a47ec5199eab60ac473453c8705686f737abff6a:9:854341)
    at n.value (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.1a92dbe2.chunk.js:1:1513294)
    at n.value (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.1a92dbe2.chunk.js:1:1513448)
    at Ha (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:409558)
    at Ba (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:409351)
    at ks (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:444974)
    at mu (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:436416)
    at vu (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:436341)
    at su (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:433350)
    at file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:384828
    at t.unstable_runWithPriority (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:460055)
    at $i (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:384537)
    at Qi (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:384773)
    at Ji (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:384708)
    at M (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:453820)
    at Qt (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:361991)
    at HTMLDocument.i (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/64.6dcd5ad3.chunk.js:2:572367)
```

## Component stack (don't write anything here)
```

    in n
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in r
    in x
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in Unknown
    in d
    in j
    in f
    in j
    in j
    in g
    in c
    in Be
    in n
    in t
    in he
    in n
    in Unknown
    in g
    in t
    in l
    in o
    in n
    in n
    in DragDropContext(n)
    in n
    in c
```

## Other details
* IDE version: 5.0.140-a47ec5199eab60ac473453c8705686f737abff6a
* Arch: x64,
* Platform Name: darwin,
* System Version: 11.6.7,
* User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.140 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36,

**Comment by Bouh** [comment]
Hi @WhyOni 

GDevelop has had several corrective updates since the crash.
If you encounter a new one please open a new bug report.
We close this bug report.
