### ISSUE TITLE
Engine Crash (More info needed)

### ISSUE THREAD

**Issue by EternalR** [4ian/GDevelop#4324]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
RuntimeError: abort(Assertion failed: undefined). Build with -s ASSERTIONS=1 for more info.
    at abort (file:///C:/Users/Asus/AppData/Local/Programs/GDevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.140-a47ec5199eab60ac473453c8705686f737abff6a:9:15364)
    at assert (file:///C:/Users/Asus/AppData/Local/Programs/GDevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.140-a47ec5199eab60ac473453c8705686f737abff6a:9:7806)
    at Object.prepare (file:///C:/Users/Asus/AppData/Local/Programs/GDevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.140-a47ec5199eab60ac473453c8705686f737abff6a:9:847089)
    at Project.HasLayoutNamed.Project.HasLayoutNamed [as hasLayoutNamed] (file:///C:/Users/Asus/AppData/Local/Programs/GDevelop/resources/app.asar/www/libGD.js?cache-buster=5.0.140-a47ec5199eab60ac473453c8705686f737abff6a:9:951451)
    at n.value (file:///C:/Users/Asus/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/1.7973603f.chunk.js:1:613448)
    at n.value (file:///C:/Users/Asus/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/1.7973603f.chunk.js:1:613595)
    at Ha (file:///C:/Users/Asus/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:409558)
    at Ba (file:///C:/Users/Asus/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:409351)
    at ks (file:///C:/Users/Asus/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:444974)
    at mu (file:///C:/Users/Asus/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:436416)
    at vu (file:///C:/Users/Asus/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:436341)
    at su (file:///C:/Users/Asus/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:433350)
    at file:///C:/Users/Asus/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:384828
    at t.unstable_runWithPriority (file:///C:/Users/Asus/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:460055)
    at $i (file:///C:/Users/Asus/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:384537)
    at Qi (file:///C:/Users/Asus/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:384773)
    at Ji (file:///C:/Users/Asus/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:384708)
    at M (file:///C:/Users/Asus/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:453820)
    at Qt (file:///C:/Users/Asus/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:361991)
    at HTMLDocument.i (file:///C:/Users/Asus/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/64.9fa65e50.chunk.js:2:572367)
```

## Component stack (don't write anything here)
```

    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in Unknown
    in d
    in j
    in f
    in j
    in j
    in g
    in c
    in Be
    in n
    in t
    in he
    in n
    in Unknown
    in g
    in t
    in l
    in o
    in n
    in n
    in DragDropContext(n)
    in n
    in c
```

## Other details
* IDE version: 5.0.140-a47ec5199eab60ac473453c8705686f737abff6a
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19044,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.140 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36,

**Comment by Silver-Streak** [comment]
Hello! 
As mentioned in the first few lines of the template you submitted, please describe what you are doing before it crashes. Thank you.,
