### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by king007aries** [4ian/GDevelop#4347]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
RuntimeError: table index is out of bounds
    at https://editor.gdevelop.io/libGD.wasm?cache-buster=5.0.144-50465badd777fed3b3c361dfde4002cd13ac9bce:wasm-function[31]:0x1ed64
    at InitialInstanceJSFunctor.__destroy__.InitialInstanceJSFunctor.__destroy__ (https://editor.gdevelop.io/libGD.js?cache-buster=5.0.144-50465badd777fed3b3c361dfde4002cd13ac9bce:9:1364803)
    at Object.destroy (https://editor.gdevelop.io/libGD.js?cache-buster=5.0.144-50465badd777fed3b3c361dfde4002cd13ac9bce:9:825805)
    at proto.delete (https://editor.gdevelop.io/libGD.js?cache-buster=5.0.144-50465badd777fed3b3c361dfde4002cd13ac9bce:9:1451048)
    at e.value (https://editor.gdevelop.io/static/js/1.27327ce8.chunk.js:1:1283770)
    at n.value (https://editor.gdevelop.io/static/js/1.27327ce8.chunk.js:1:718443)
    at https://editor.gdevelop.io/static/js/64.d0527b5b.chunk.js:2:424152
    at ls (https://editor.gdevelop.io/static/js/64.d0527b5b.chunk.js:2:424193)
    at gs (https://editor.gdevelop.io/static/js/64.d0527b5b.chunk.js:2:426038)
    at wu (https://editor.gdevelop.io/static/js/64.d0527b5b.chunk.js:2:439560)
    at t.unstable_runWithPriority (https://editor.gdevelop.io/static/js/64.d0527b5b.chunk.js:2:460055)
    at $i (https://editor.gdevelop.io/static/js/64.d0527b5b.chunk.js:2:384537)
    at _u (https://editor.gdevelop.io/static/js/64.d0527b5b.chunk.js:2:437418)
    at su (https://editor.gdevelop.io/static/js/64.d0527b5b.chunk.js:2:433549)
    at https://editor.gdevelop.io/static/js/64.d0527b5b.chunk.js:2:384828
    at t.unstable_runWithPriority (https://editor.gdevelop.io/static/js/64.d0527b5b.chunk.js:2:460055)
    at $i (https://editor.gdevelop.io/static/js/64.d0527b5b.chunk.js:2:384537)
    at Qi (https://editor.gdevelop.io/static/js/64.d0527b5b.chunk.js:2:384773)
    at Ji (https://editor.gdevelop.io/static/js/64.d0527b5b.chunk.js:2:384708)
    at M (https://editor.gdevelop.io/static/js/64.d0527b5b.chunk.js:2:453820)
    at Qt (https://editor.gdevelop.io/static/js/64.d0527b5b.chunk.js:2:361991)
    at HTMLDocument.i (https://editor.gdevelop.io/static/js/64.d0527b5b.chunk.js:2:572367)
```

## Component stack (don't write anything here)
```

    in n
    in div
    in div
    in Unknown
    in Measure
    in i
    in a
    in n
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in c
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in Unknown
    in j
    in d
    in h
    in f
    in h
    in h
    in g
    in c
    in We
    in n
    in t
    in ge
    in n
    in Unknown
    in g
    in t
    in l
    in o
    in n
    in n
    in DragDropContext(n)
    in n
    in c
```

## Other details
* IDE version: 5.0.144-50465badd777fed3b3c361dfde4002cd13ac9bce
* Arch: Unknown architecture (web-app),
* Platform Name: Win32,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36,

**Comment by Bouh** [comment]
Hi @king007aries

Thanks for reporting this problem.
Can you explain a bit more about how it happened?
A few detailed steps of what you were doing would help greatly find where this problem comes from 👍
