### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by jerikothomas** [4ian/GDevelop#4431]
=> I want see the value of variable using log feature in debugging tab

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B_type%2C%20_bool%2C%20_children%2C%20_childrenArray%2C%20_str%2C%20_undefinedInContainer%2C%20_value%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at To (file:///app/GDevelop/resources/app.asar/www/static/js/64.ba2cfbcf.chunk.js:2:391102)
    at file:///app/GDevelop/resources/app.asar/www/static/js/64.ba2cfbcf.chunk.js:2:395974
    at Ma (file:///app/GDevelop/resources/app.asar/www/static/js/64.ba2cfbcf.chunk.js:2:405455)
    at ks (file:///app/GDevelop/resources/app.asar/www/static/js/64.ba2cfbcf.chunk.js:2:445680)
    at mu (file:///app/GDevelop/resources/app.asar/www/static/js/64.ba2cfbcf.chunk.js:2:436416)
    at vu (file:///app/GDevelop/resources/app.asar/www/static/js/64.ba2cfbcf.chunk.js:2:436341)
    at su (file:///app/GDevelop/resources/app.asar/www/static/js/64.ba2cfbcf.chunk.js:2:433350)
    at file:///app/GDevelop/resources/app.asar/www/static/js/64.ba2cfbcf.chunk.js:2:384828
    at t.unstable_runWithPriority (file:///app/GDevelop/resources/app.asar/www/static/js/64.ba2cfbcf.chunk.js:2:460055)
    at $i (file:///app/GDevelop/resources/app.asar/www/static/js/64.ba2cfbcf.chunk.js:2:384537)
    at Qi (file:///app/GDevelop/resources/app.asar/www/static/js/64.ba2cfbcf.chunk.js:2:384773)
    at Ji (file:///app/GDevelop/resources/app.asar/www/static/js/64.ba2cfbcf.chunk.js:2:384708)
    at nu (file:///app/GDevelop/resources/app.asar/www/static/js/64.ba2cfbcf.chunk.js:2:430132)
    at ba (file:///app/GDevelop/resources/app.asar/www/static/js/64.ba2cfbcf.chunk.js:2:401923)
    at file:///app/GDevelop/resources/app.asar/www/static/js/main.135e4af6.chunk.js:1:18328
    at e (file:///app/GDevelop/resources/app.asar/www/static/js/1.163a659a.chunk.js:1:722686)
    at file:///app/GDevelop/resources/app.asar/www/static/js/1.163a659a.chunk.js:1:721404
    at Set.forEach (<anonymous>)
    at e.value (file:///app/GDevelop/resources/app.asar/www/static/js/1.163a659a.chunk.js:1:721376)
    at i (file:///app/GDevelop/resources/app.asar/www/static/js/64.ba2cfbcf.chunk.js:2:572367)
```

## Component stack (don't write anything here)
```

    in div
    in div
    in n
    in div
    in a
    in div
    in t
    in div
    in div
    in t
    in t
    in div
    in t
    in div
    in n
    in div
    in a
    in Ve
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in r
    in x
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in n
    in div
    in a
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in Unknown
    in j
    in d
    in h
    in f
    in h
    in h
    in v
    in c
    in Ue
    in n
    in t
    in fe
    in n
    in Unknown
    in g
    in t
    in l
    in o
    in n
    in n
    in DragDropContext(n)
    in n
    in c
```

## Other details
* IDE version: 5.0.146-4dbabab052a77849696335b68597e44b21ea9682
* Arch: x64,
* Platform Name: linux,
* System Version: 6.0.2-arch1-1,
* User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.0.146 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36,

**Comment by AlexandreSi** [comment]
Hi @jerikothomas,
Thanks for taking the time to report this crash!
I cannot reproduce it. Would you be able to create a new project with only this bug happening?
Or you can send over your project.
