### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by colaadoon** [4ian/GDevelop#4435]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at gs (https://editor.gdevelop.io/static/js/65.1dc567a1.chunk.js:2:444088)
    at wu (https://editor.gdevelop.io/static/js/65.1dc567a1.chunk.js:2:457327)
    at t.unstable_runWithPriority (https://editor.gdevelop.io/static/js/65.1dc567a1.chunk.js:2:477822)
    at $i (https://editor.gdevelop.io/static/js/65.1dc567a1.chunk.js:2:402304)
    at _u (https://editor.gdevelop.io/static/js/65.1dc567a1.chunk.js:2:455185)
    at su (https://editor.gdevelop.io/static/js/65.1dc567a1.chunk.js:2:451316)
    at https://editor.gdevelop.io/static/js/65.1dc567a1.chunk.js:2:402595
    at t.unstable_runWithPriority (https://editor.gdevelop.io/static/js/65.1dc567a1.chunk.js:2:477822)
    at $i (https://editor.gdevelop.io/static/js/65.1dc567a1.chunk.js:2:402304)
    at Qi (https://editor.gdevelop.io/static/js/65.1dc567a1.chunk.js:2:402540)
    at Ji (https://editor.gdevelop.io/static/js/65.1dc567a1.chunk.js:2:402475)
    at M (https://editor.gdevelop.io/static/js/65.1dc567a1.chunk.js:2:471587)
    at Qt (https://editor.gdevelop.io/static/js/65.1dc567a1.chunk.js:2:379758)
    at HTMLDocument.i (https://editor.gdevelop.io/static/js/65.1dc567a1.chunk.js:2:590540)
```

## Component stack (don't write anything here)
```

    in span
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in div
    in div
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in f
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in m
    in w
    in div
    in ForwardRef
    in div
    in a
    in Unknown
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in div
    in Unknown
    in div
    in ForwardRef
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in S
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in q
    in div
    in a
    in div
    in ForwardRef
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in S
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in P
    in n
    in t
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in Unknown
    in Xe
    in j
    in d
    in h
    in f
    in h
    in h
    in x
    in Unknown
    in c
    in Ve
    in n
    in t
    in ge
    in n
    in Unknown
    in g
    in t
    in u
    in o
    in n
    in n
    in DragDropContext(n)
    in n
    in c
```

## Other details
* IDE version: 5.1.148-386e23b042282413da41c398043f4ccbc1bddaa7
* Arch: Unknown architecture (web-app),
* Platform Name: Win32,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36,

**Comment by AlexandreSi** [comment]
Hi @colaadoon,
Thanks for taking the time to report this crash.
I'm having troubles finding on which screen this could have happened.

Do you have some context on what you were doing at the time of the crash?

**Comment by AlexandreSi** [comment]
This issue should be fixed in the next days thanks to recent work on translation.
