### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by spiderRports** [4ian/GDevelop#4462]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
RuntimeError: memory access out of bounds
    at file:///C:/Program%20Files/GDevelop/resources/app.asar/www/libGD.wasm?cache-buster=5.1.149-c5eb0bcc006c3bcf910d9e8632af2bc15ae7d0b1:wasm-function[49]:0x1f3ad
    at Expression.GetPlainString.Expression.GetPlainString [as getPlainString] (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/libGD.js?cache-buster=5.1.149-c5eb0bcc006c3bcf910d9e8632af2bc15ae7d0b1:9:1082846)
    at n.value (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/1.90cdeb4a.chunk.js:1:1137438)
    at Ha (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:427325)
    at Ba (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:427118)
    at ks (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:462741)
    at mu (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:454183)
    at vu (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:454108)
    at su (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:451117)
    at file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:402595
    at t.unstable_runWithPriority (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:477822)
    at $i (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:402304)
    at Qi (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:402540)
    at Ji (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:402475)
    at M (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:471587)
    at Qt (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:379758)
    at HTMLDocument.i (file:///C:/Program%20Files/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:590540)
```

## Component stack (don't write anything here)
```

    in n
    in div
    in n
    in a
    in n
    in ForwardRef(K)
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in Unknown
    in Xe
    in j
    in d
    in h
    in f
    in h
    in h
    in v
    in Unknown
    in c
    in ze
    in n
    in t
    in ge
    in n
    in Unknown
    in g
    in t
    in u
    in o
    in n
    in n
    in DragDropContext(n)
    in n
    in c
```

## Other details
* IDE version: 5.1.149-c5eb0bcc006c3bcf910d9e8632af2bc15ae7d0b1
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19045,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.1.149 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36,

**Comment by Silver-Streak** [comment]
Yeah, no. You're welcome to report an issue, you're not welcome to flood stream of conscience and curses in the title, sorry. I've updated the title back to something acceptable. 

Separately: 
As mentioned in the template you posted, you need to provide what you were actually doing before the crash so that people can potentially investigate.

Going forward, I would also recommend setting up GIthub desktop to do regular backups of your project, to ensure easy reversion of your code: https://wiki.gdevelop.io/gdevelop5/tutorials/using-github-desktop
