### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by StarryNightWing07** [4ian/GDevelop#4546]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
RuntimeError: memory access out of bounds
    at file:///C:/Users/dcoleman6053/AppData/Local/Programs/GDevelop/resources/app.asar/www/libGD.wasm?cache-buster=5.1.149-c5eb0bcc006c3bcf910d9e8632af2bc15ae7d0b1:wasm-function[49]:0x1f3ad
    at ObjectConfiguration.GetType.ObjectConfiguration.GetType [as getType] (file:///C:/Users/dcoleman6053/AppData/Local/Programs/GDevelop/resources/app.asar/www/libGD.js?cache-buster=5.1.149-c5eb0bcc006c3bcf910d9e8632af2bc15ae7d0b1:9:841727)
    at Object.getThumbnail (file:///C:/Users/dcoleman6053/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/1.90cdeb4a.chunk.js:1:47868)
    at file:///C:/Users/dcoleman6053/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/1.90cdeb4a.chunk.js:1:402917
    at Object.getThumbnail (file:///C:/Users/dcoleman6053/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/1.90cdeb4a.chunk.js:1:181437)
    at Object.children (file:///C:/Users/dcoleman6053/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/1.90cdeb4a.chunk.js:1:180029)
    at children (file:///C:/Users/dcoleman6053/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/1.90cdeb4a.chunk.js:1:39848)
    at ks (file:///C:/Users/dcoleman6053/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:464856)
    at mu (file:///C:/Users/dcoleman6053/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:454183)
    at vu (file:///C:/Users/dcoleman6053/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:454108)
    at su (file:///C:/Users/dcoleman6053/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:451117)
    at file:///C:/Users/dcoleman6053/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:402595
    at t.unstable_runWithPriority (file:///C:/Users/dcoleman6053/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:477822)
    at $i (file:///C:/Users/dcoleman6053/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:402304)
    at Qi (file:///C:/Users/dcoleman6053/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:402540)
    at Ji (file:///C:/Users/dcoleman6053/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:402475)
    at nu (file:///C:/Users/dcoleman6053/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:447899)
    at Object.enqueueSetState (file:///C:/Users/dcoleman6053/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:406303)
    at l._.setState (file:///C:/Users/dcoleman6053/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:352055)
    at r.handleChange (file:///C:/Users/dcoleman6053/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/0.4b2ec088.chunk.js:2:1119913)
    at file:///C:/Users/dcoleman6053/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/0.4b2ec088.chunk.js:2:1366662
    at g (file:///C:/Users/dcoleman6053/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/0.4b2ec088.chunk.js:2:1353799)
    at Object.keys.reduce.n.<computed> [as beginDrag] (file:///C:/Users/dcoleman6053/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/0.4b2ec088.chunk.js:2:1351024)
    at handleTopDragStart (file:///C:/Users/dcoleman6053/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/0.4b2ec088.chunk.js:2:1703756)
    at i (file:///C:/Users/dcoleman6053/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.3d776c43.chunk.js:2:590540)
```

## Component stack (don't write anything here)
```

    in Unknown
    in n
    in div
    in Unknown
    in DropTarget(Component)
    in DragSource(DropTarget(Component))
    in Unknown
    in div
    in div
    in div
    in t
    in t
    in a
    in a
    in n
    in t
    in div
    in t
    in div
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in ForwardRef
    in ForwardRef
    in t
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in r
    in v
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in a
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in Unknown
    in Xe
    in j
    in d
    in h
    in f
    in h
    in h
    in v
    in Unknown
    in c
    in ze
    in n
    in t
    in ge
    in n
    in Unknown
    in g
    in t
    in u
    in o
    in n
    in n
    in DragDropContext(n)
    in n
    in c
```

## Other details
* IDE version: 5.1.149-c5eb0bcc006c3bcf910d9e8632af2bc15ae7d0b1
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19042,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.1.149 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36,

**Comment by StarryNightWing07** [comment]
I was trying to edit a scene and I got this error. (shown below)
![Screenshot 2022-11-14 141603](https://user-images.githubusercontent.com/49001723/201767209-dff26fdb-317f-4869-b563-6a11a270d3f8.png)

**Comment by Bouh** [comment]
Do you remember what you tried to do on the scene just before the crash?
