### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by game890** [4ian/GDevelop#4615]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
RuntimeError: memory access out of bounds
    at https://editor.gdevelop.io/libGD.wasm?cache-buster=5.1.151-044cc5354f5e884a9a9ae0325ff541ef7a8507e2:wasm-function[3427]:0xb551a
    at https://editor.gdevelop.io/libGD.wasm?cache-buster=5.1.151-044cc5354f5e884a9a9ae0325ff541ef7a8507e2:wasm-function[1353]:0x36b78
    at ObjectMetadata.IsUnsupportedBaseObjectCapability.ObjectMetadata.IsUnsupportedBaseObjectCapability [as isUnsupportedBaseObjectCapability] (https://editor.gdevelop.io/libGD.js?cache-buster=5.1.151-044cc5354f5e884a9a9ae0325ff541ef7a8507e2:9:1384734)
    at S (https://editor.gdevelop.io/static/js/1.89984a8b.chunk.js:1:728955)
    at Yo (https://editor.gdevelop.io/static/js/65.5980eba5.chunk.js:2:336787)
    at za (https://editor.gdevelop.io/static/js/65.5980eba5.chunk.js:2:345679)
    at ks (https://editor.gdevelop.io/static/js/65.5980eba5.chunk.js:2:384129)
    at mu (https://editor.gdevelop.io/static/js/65.5980eba5.chunk.js:2:375653)
    at vu (https://editor.gdevelop.io/static/js/65.5980eba5.chunk.js:2:375578)
    at su (https://editor.gdevelop.io/static/js/65.5980eba5.chunk.js:2:372587)
    at https://editor.gdevelop.io/static/js/65.5980eba5.chunk.js:2:324065
    at t.unstable_runWithPriority (https://editor.gdevelop.io/static/js/65.5980eba5.chunk.js:2:399292)
    at Wi (https://editor.gdevelop.io/static/js/65.5980eba5.chunk.js:2:323774)
    at Qi (https://editor.gdevelop.io/static/js/65.5980eba5.chunk.js:2:324010)
    at Ji (https://editor.gdevelop.io/static/js/65.5980eba5.chunk.js:2:323945)
    at nu (https://editor.gdevelop.io/static/js/65.5980eba5.chunk.js:2:369369)
    at Object.enqueueSetState (https://editor.gdevelop.io/static/js/65.5980eba5.chunk.js:2:327773)
    at _.setState (https://editor.gdevelop.io/static/js/65.5980eba5.chunk.js:2:273524)
    at https://editor.gdevelop.io/static/js/1.89984a8b.chunk.js:1:850532
    at l (https://editor.gdevelop.io/static/js/65.5980eba5.chunk.js:2:401179)
    at Generator._invoke (https://editor.gdevelop.io/static/js/65.5980eba5.chunk.js:2:400967)
    at Generator.next (https://editor.gdevelop.io/static/js/65.5980eba5.chunk.js:2:401604)
    at r (https://editor.gdevelop.io/static/js/65.5980eba5.chunk.js:2:372)
    at s (https://editor.gdevelop.io/static/js/65.5980eba5.chunk.js:2:583)
```

## Component stack (don't write anything here)
```

    in S
    in n
    in t
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in Unknown
    in nt
    in j
    in d
    in f
    in h
    in h
    in x
    in c
    in q
    in Ke
    in n
    in t
    in Te
    in n
    in Unknown
    in Unknown
    in m
    in t
    in u
    in t
    in c
    in n
    in DragDropContext(n)
    in n
    in c
```

## Other details
* IDE version: 5.1.151-044cc5354f5e884a9a9ae0325ff541ef7a8507e2
* Arch: Unknown architecture (web-app),
* Platform Name: Linux x86_64,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (X11; CrOS x86_64 15117.111.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36,

**Comment by Silver-Streak** [comment]
Hello! Are you still experiencing this crash?

Also, the top part of the template was left empty. If you are still experiencing the crash, can you provide the steps to reproduce it?


If no response is received by Wednesday. 12/07/22, this issue will be closed out.
