### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by dylan9008** [4ian/GDevelop#4631]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
RuntimeError: memory access out of bounds
    at file:///C:/Users/dylan/AppData/Local/Programs/GDevelop/resources/app.asar/www/libGD.wasm?cache-buster=5.1.151-57ce8dcbbfa08eca1588b132aa98a44d2e59489e:wasm-function[3353]:0xb1ce9
    at file:///C:/Users/dylan/AppData/Local/Programs/GDevelop/resources/app.asar/www/libGD.wasm?cache-buster=5.1.151-57ce8dcbbfa08eca1588b132aa98a44d2e59489e:wasm-function[972]:0x3139d
    at ObjectMetadata.IsUnsupportedBaseObjectCapability.ObjectMetadata.IsUnsupportedBaseObjectCapability [as isUnsupportedBaseObjectCapability] (file:///C:/Users/dylan/AppData/Local/Programs/GDevelop/resources/app.asar/www/libGD.js?cache-buster=5.1.151-57ce8dcbbfa08eca1588b132aa98a44d2e59489e:9:1178104)
    at P (file:///C:/Users/dylan/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/1.c8340943.chunk.js:1:613561)
    at Yo (file:///C:/Users/dylan/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:446010)
    at Ua (file:///C:/Users/dylan/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:454902)
    at _s (file:///C:/Users/dylan/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:493352)
    at gu (file:///C:/Users/dylan/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:484876)
    at vu (file:///C:/Users/dylan/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:484801)
    at su (file:///C:/Users/dylan/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:481810)
    at file:///C:/Users/dylan/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:433288
    at t.unstable_runWithPriority (file:///C:/Users/dylan/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:508515)
    at $i (file:///C:/Users/dylan/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:432997)
    at Qi (file:///C:/Users/dylan/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:433233)
    at Ji (file:///C:/Users/dylan/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:433168)
    at nu (file:///C:/Users/dylan/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:478592)
    at Object.enqueueSetState (file:///C:/Users/dylan/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:436996)
    at n.k.setState (file:///C:/Users/dylan/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:382748)
    at file:///C:/Users/dylan/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/1.c8340943.chunk.js:1:732757
```

## Component stack (don't write anything here)
```

    in P
    in n
    in t
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in Unknown
    in qe
    in j
    in d
    in f
    in h
    in h
    in x
    in Unknown
    in c
    in We
    in n
    in t
    in ge
    in n
    in Unknown
    in m
    in t
    in u
    in o
    in n
    in n
    in DragDropContext(n)
    in n
    in c
```

## Other details
* IDE version: 5.1.151-57ce8dcbbfa08eca1588b132aa98a44d2e59489e
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.22000,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.1.151 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36,

**Comment by Silver-Streak** [comment]
Hello @dylan9008,

I'm sorry you're experiencing a crash. Unfortunately you left the template incomplete, as you did not fill out the top part listing what steps led to the issue. 

If you can reproduce the crash, please list the exact steps that are required to cause it to occur. Thank you!
