### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by cristianvm18** [4ian/GDevelop#4638]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
RuntimeError: null function or function signature mismatch
    at file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/libGD.wasm?cache-buster=5.1.151-57ce8dcbbfa08eca1588b132aa98a44d2e59489e:wasm-function[3003]:0x960dc
    at file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/libGD.wasm?cache-buster=5.1.151-57ce8dcbbfa08eca1588b132aa98a44d2e59489e:wasm-function[440]:0x27d11
    at Project.HasExternalEventsNamed.Project.HasExternalEventsNamed [as hasExternalEventsNamed] (file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/libGD.js?cache-buster=5.1.151-57ce8dcbbfa08eca1588b132aa98a44d2e59489e:9:957352)
    at n.value (file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/static/js/1.c8340943.chunk.js:1:628240)
    at n.value (file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/static/js/1.c8340943.chunk.js:1:628741)
    at Ha (file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:458018)
    at Ba (file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:457811)
    at _s (file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:493434)
    at gu (file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:484876)
    at vu (file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:484801)
    at su (file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:481810)
    at file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:433288
    at t.unstable_runWithPriority (file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:508515)
    at $i (file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:432997)
    at Qi (file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:433233)
    at Ji (file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:433168)
    at nu (file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:478592)
    at ba (file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:450383)
    at file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/static/js/1.c8340943.chunk.js:1:452128
    at l (file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:510402)
    at Generator._invoke (file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:510190)
    at Generator.next (file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:510827)
    at r (file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:419)
    at s (file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:622)
    at file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:681
    at new Promise (<anonymous>)
    at file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/static/js/65.1bffa5d7.chunk.js:2:562
    at EventEmitter.r (file:///C:/Users/usuario/Downloads/GDevelop/resources/app.asar/www/static/js/local-app.feea34db.chunk.js:1:32857)
    at EventEmitter.emit (node:events:390:28)
    at Object.onMessage (node:electron/js2c/renderer_init:69:746)
```

## Component stack (don't write anything here)
```

    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in Unknown
    in qe
    in j
    in d
    in f
    in h
    in h
    in x
    in Unknown
    in c
    in We
    in n
    in t
    in ge
    in n
    in Unknown
    in m
    in t
    in u
    in o
    in n
    in n
    in DragDropContext(n)
    in n
    in c
```

## Other details
* IDE version: 5.1.151-57ce8dcbbfa08eca1588b132aa98a44d2e59489e
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19044,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.1.151 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36,

**Comment by Silver-Streak** [comment]
Hello @cristianvm18,

I'm sorry you're experiencing a crash. Unfortunately you left the template incomplete, as you did not fill out the top part listing what steps led to the issue.

If you can reproduce the crash, please list the exact steps that are required to cause it to occur. Thank you
