### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by RGXPK** [4ian/GDevelop#4864]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at gs (https://editor.gdevelop.io/static/js/66.fdea1ad4.chunk.js:2:370005)
    at wu (https://editor.gdevelop.io/static/js/66.fdea1ad4.chunk.js:2:383244)
    at t.unstable_runWithPriority (https://editor.gdevelop.io/static/js/66.fdea1ad4.chunk.js:2:403739)
    at Vi (https://editor.gdevelop.io/static/js/66.fdea1ad4.chunk.js:2:328221)
    at _u (https://editor.gdevelop.io/static/js/66.fdea1ad4.chunk.js:2:381102)
    at su (https://editor.gdevelop.io/static/js/66.fdea1ad4.chunk.js:2:377233)
    at https://editor.gdevelop.io/static/js/66.fdea1ad4.chunk.js:2:328512
    at t.unstable_runWithPriority (https://editor.gdevelop.io/static/js/66.fdea1ad4.chunk.js:2:403739)
    at Vi (https://editor.gdevelop.io/static/js/66.fdea1ad4.chunk.js:2:328221)
    at Qi (https://editor.gdevelop.io/static/js/66.fdea1ad4.chunk.js:2:328457)
    at Ji (https://editor.gdevelop.io/static/js/66.fdea1ad4.chunk.js:2:328392)
    at M (https://editor.gdevelop.io/static/js/66.fdea1ad4.chunk.js:2:397504)
    at Qt (https://editor.gdevelop.io/static/js/66.fdea1ad4.chunk.js:2:305675)
    at HTMLDocument.i (https://editor.gdevelop.io/static/js/66.fdea1ad4.chunk.js:2:464463)
```

## Component stack (don't write anything here)
```

    in span
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in div
    in div
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in f
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in m
    in S
    in div
    in ForwardRef
    in div
    in i
    in Unknown
    in div
    in ForwardRef
    in div
    in i
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in div
    in Unknown
    in div
    in ForwardRef
    in ForwardRef
    in div
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in T
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in K
    in div
    in i
    in div
    in ForwardRef
    in ForwardRef
    in div
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in T
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in S
    in n
    in t
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in Unknown
    in bt
    in j
    in d
    in f
    in h
    in h
    in w
    in c
    in G
    in it
    in n
    in t
    in Me
    in n
    in Unknown
    in Unknown
    in m
    in t
    in u
    in t
    in l
    in c
    in n
    in DragDropContext(n)
    in Unknown
    in c
```

## Other details
* IDE version: 5.1.156-ba30665811c19d1b3ffe5549a6eeee7dc7d6b6a1
* Arch: Unknown architecture (web-app),
* Platform Name: Linux armv8l,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (Linux; Android 10; SM-J400F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Mobile Safari/537.36,

**Comment by Bouh** [comment]
Hello @RGXPK 
Thanks for taking the time to report this issue.
Can you provide us with some context about how you were using GDevelop when this happened?
