### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by anderbauYT** [4ian/GDevelop#4908]
=> when i am making a extension the editor crashed the proyect and corrupted it

## Error stack
```
RuntimeError: null function or function signature mismatch
    at file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/libGD.wasm?cache-buster=5.1.157-a8177b0e6f727b0a0d1b7514fcc56e0c12e5f568:wasm-function[43]:0x21b66
    at InitialInstanceJSFunctor.__destroy__.InitialInstanceJSFunctor.__destroy__ (file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/libGD.js?cache-buster=5.1.157-a8177b0e6f727b0a0d1b7514fcc56e0c12e5f568:9:1149499)
    at Object.destroy (file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/libGD.js?cache-buster=5.1.157-a8177b0e6f727b0a0d1b7514fcc56e0c12e5f568:9:892973)
    at InitialInstanceJSFunctor.proto.delete (file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/libGD.js?cache-buster=5.1.157-a8177b0e6f727b0a0d1b7514fcc56e0c12e5f568:9:1576193)
    at n.value (file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/1.c4501d39.chunk.js:1:1562590)
    at file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:367836
    at ls (file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:367877)
    at gs (file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:369722)
    at wu (file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:383244)
    at t.unstable_runWithPriority (file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:403739)
    at Vi (file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:328221)
    at _u (file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:381102)
    at su (file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:377233)
    at file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:328512
    at t.unstable_runWithPriority (file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:403739)
    at Vi (file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:328221)
    at Qi (file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:328457)
    at Ji (file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:328392)
    at nu (file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:373816)
    at ba (file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:345607)
    at onClickAway (file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/1.c4501d39.chunk.js:1:402447)
    at file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/0.571a3200.chunk.js:2:2204790
    at HTMLDocument.<anonymous> (file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/0.571a3200.chunk.js:2:590309)
    at HTMLDocument.i (file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:464463)
```

## Component stack (don't write anything here)
```

    in n
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in x
    in t
    in div
    in div
    in t
    in div
    in t
    in Unknown
    in n
    in o
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in Unknown
    in bt
    in j
    in d
    in f
    in h
    in h
    in w
    in c
    in Z
    in it
    in n
    in t
    in _e
    in n
    in Unknown
    in Unknown
    in m
    in t
    in u
    in t
    in l
    in c
    in n
    in DragDropContext(n)
    in Unknown
    in c
```

## Other details
* IDE version: 5.1.157-a8177b0e6f727b0a0d1b7514fcc56e0c12e5f568
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19045,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.1.157 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36,

**Comment by AlexandreSi** [comment]
Hi @anderbauYT and sorry for the inconvenience.
Do you remember what exact action you were doing when it occurred? Renaming something? Drag&dropping an item?
