### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Ninja201224** [4ian/GDevelop#4920]
=> Please write here a short description of when the error occurred and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at gs (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:383794)
    at wu (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:397033)
    at t.unstable_runWithPriority (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:417528)
    at Wi (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:342010)
    at _u (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:394891)
    at su (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:391022)
    at https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:342301
    at t.unstable_runWithPriority (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:417528)
    at Wi (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:342010)
    at Qi (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:342246)
    at Ji (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:342181)
    at nu (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:387605)
    at Object.enqueueSetState (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:346009)
    at _.setState (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:291760)
    at e.showUserSnackbar (https://editor.gdevelop.io/static/js/1.a0c97157.chunk.js:1:901810)
    at onClose (https://editor.gdevelop.io/static/js/1.a0c97157.chunk.js:1:906732)
    at https://editor.gdevelop.io/static/js/0.1ceabc98.chunk.js:2:2375859
    at https://editor.gdevelop.io/static/js/0.1ceabc98.chunk.js:2:590540
    at https://editor.gdevelop.io/static/js/0.1ceabc98.chunk.js:2:2375983
    at i (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:471794)
```

## Component stack (don't write anything here)
```

    in n
    in span
    in div
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in t
    in ForwardRef
    in div
    in Unknown
    in ForwardRef
    in ForwardRef
    in n
    in Unknown
    in t
    in Unknown
    in Unknown
    in m
    in t
    in u
    in t
    in l
    in c
    in n
    in DragDropContext(n)
    in Unknown
    in c
```

## Other details
* IDE version: 5.1.157-a73a92d748af31fdee395f9e55e6c68ca48954b7
* Arch: Unknown architecture (web-app),
* Platform Name: MacIntel,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36,

**Comment by Ninja201224** [comment]
uuu
