### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Ninja201224** [4ian/GDevelop#4922]
=> Please write here a short description of when the error occurred and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
RuntimeError: null function or function signature mismatch
    at https://editor.gdevelop.io/libGD.wasm?cache-buster=5.1.157-a73a92d748af31fdee395f9e55e6c68ca48954b7:wasm-function[32]:0x21911
    at Project.__destroy__.Project.__destroy__ (https://editor.gdevelop.io/libGD.js?cache-buster=5.1.157-a73a92d748af31fdee395f9e55e6c68ca48954b7:9:1029872)
    at Object.destroy (https://editor.gdevelop.io/libGD.js?cache-buster=5.1.157-a73a92d748af31fdee395f9e55e6c68ca48954b7:9:892974)
    at proto.delete (https://editor.gdevelop.io/libGD.js?cache-buster=5.1.157-a73a92d748af31fdee395f9e55e6c68ca48954b7:9:1576194)
    at https://editor.gdevelop.io/static/js/1.a0c97157.chunk.js:1:546596
    at ta (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:355849)
    at na (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:356618)
    at Object.useState (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:360712)
    at t.useState (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:296616)
    at i (https://editor.gdevelop.io/static/js/1.a0c97157.chunk.js:1:1614650)
    at t.a (https://editor.gdevelop.io/static/js/1.a0c97157.chunk.js:1:540275)
    at Yo (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:355023)
    at za (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:363915)
    at ks (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:402365)
    at mu (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:393889)
    at vu (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:393814)
    at su (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:390823)
    at https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:342301
    at t.unstable_runWithPriority (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:417528)
    at Wi (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:342010)
    at Qi (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:342246)
    at Ji (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:342181)
    at nu (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:387605)
    at ba (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:359396)
    at Object.sealUnsavedChanges (https://editor.gdevelop.io/static/js/1.a0c97157.chunk.js:1:291160)
    at https://editor.gdevelop.io/static/js/1.a0c97157.chunk.js:1:546624
    at ta (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:355849)
    at ba (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:359329)
    at https://editor.gdevelop.io/static/js/1.a0c97157.chunk.js:1:1614789
    at new Promise (<anonymous>)
    at https://editor.gdevelop.io/static/js/1.a0c97157.chunk.js:1:1614752
    at https://editor.gdevelop.io/static/js/1.a0c97157.chunk.js:1:546514
    at https://editor.gdevelop.io/static/js/1.a0c97157.chunk.js:1:547238
    at p (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:789)
    at Generator.<anonymous> (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:2136)
    at Generator.next (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:1152)
    at r (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:7032)
    at s (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:7235)
    at https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:7294
    at new Promise (<anonymous>)
    at https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:7175
    at https://editor.gdevelop.io/static/js/1.a0c97157.chunk.js:1:547788
    at https://editor.gdevelop.io/static/js/1.a0c97157.chunk.js:1:548044
    at https://editor.gdevelop.io/static/js/1.a0c97157.chunk.js:1:550566
    at p (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:789)
    at Generator.<anonymous> (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:2136)
    at Generator.next (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:1152)
    at r (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:7032)
    at s (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:7235)
```

## Component stack (don't write anything here)
```

    in Unknown
    in Unknown
    in bt
    in p
    in l
    in h
    in j
    in j
    in k
    in c
    in Z
    in it
    in n
    in t
    in _e
    in n
    in Unknown
    in t
    in Unknown
    in Unknown
    in m
    in t
    in u
    in t
    in l
    in c
    in n
    in DragDropContext(n)
    in Unknown
    in c
```

## Other details
* IDE version: 5.1.157-a73a92d748af31fdee395f9e55e6c68ca48954b7
* Arch: Unknown architecture (web-app),
* Platform Name: MacIntel,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36,

**Comment by Ninja201224** [comment]
help
