### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by t-retgt** [4ian/GDevelop#4944]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
RuntimeError: memory access out of bounds
    at file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.1.157.0_x64__k1pbm4zg68kra/app/resources/app.asar/www/libGD.wasm?cache-buster=5.1.157-a8177b0e6f727b0a0d1b7514fcc56e0c12e5f568:wasm-function[3485]:0xb983a
    at file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.1.157.0_x64__k1pbm4zg68kra/app/resources/app.asar/www/libGD.wasm?cache-buster=5.1.157-a8177b0e6f727b0a0d1b7514fcc56e0c12e5f568:wasm-function[1010]:0x3370b
    at ObjectMetadata.IsUnsupportedBaseObjectCapability.ObjectMetadata.IsUnsupportedBaseObjectCapability [as isUnsupportedBaseObjectCapability] (file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.1.157.0_x64__k1pbm4zg68kra/app/resources/app.asar/www/libGD.js?cache-buster=5.1.157-a8177b0e6f727b0a0d1b7514fcc56e0c12e5f568:9:1244306)
    at A (file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.1.157.0_x64__k1pbm4zg68kra/app/resources/app.asar/www/static/js/1.c4501d39.chunk.js:1:744418)
    at Yo (file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.1.157.0_x64__k1pbm4zg68kra/app/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:341234)
    at za (file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.1.157.0_x64__k1pbm4zg68kra/app/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:350126)
    at ks (file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.1.157.0_x64__k1pbm4zg68kra/app/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:388576)
    at mu (file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.1.157.0_x64__k1pbm4zg68kra/app/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:380100)
    at vu (file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.1.157.0_x64__k1pbm4zg68kra/app/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:380025)
    at su (file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.1.157.0_x64__k1pbm4zg68kra/app/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:377034)
    at file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.1.157.0_x64__k1pbm4zg68kra/app/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:328512
    at t.unstable_runWithPriority (file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.1.157.0_x64__k1pbm4zg68kra/app/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:403739)
    at Vi (file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.1.157.0_x64__k1pbm4zg68kra/app/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:328221)
    at Qi (file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.1.157.0_x64__k1pbm4zg68kra/app/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:328457)
    at Ji (file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.1.157.0_x64__k1pbm4zg68kra/app/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:328392)
    at nu (file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.1.157.0_x64__k1pbm4zg68kra/app/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:373816)
    at Object.enqueueSetState (file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.1.157.0_x64__k1pbm4zg68kra/app/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:332220)
    at n._.setState (file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.1.157.0_x64__k1pbm4zg68kra/app/resources/app.asar/www/static/js/66.3e9b0e4c.chunk.js:2:277971)
    at file:///C:/Program%20Files/WindowsApps/GDevelopgameengine.GDevelop_5.1.157.0_x64__k1pbm4zg68kra/app/resources/app.asar/www/static/js/1.c4501d39.chunk.js:1:899655
```

## Component stack (don't write anything here)
```

    in A
    in n
    in t
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in Unknown
    in bt
    in j
    in d
    in f
    in h
    in h
    in w
    in c
    in Z
    in it
    in n
    in t
    in _e
    in n
    in Unknown
    in Unknown
    in m
    in t
    in u
    in t
    in l
    in c
    in n
    in DragDropContext(n)
    in Unknown
    in c
```

## Other details
* IDE version: 5.1.157-a8177b0e6f727b0a0d1b7514fcc56e0c12e5f568
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19044,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.1.157 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36,

**Comment by t-retgt** [comment]
tt
