### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by t-retgt** [4ian/GDevelop#4946]
=> Please write here a short description of when the error occurred and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at gs (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:383794)
    at wu (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:397033)
    at t.unstable_runWithPriority (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:417528)
    at Wi (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:342010)
    at _u (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:394891)
    at su (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:391022)
    at https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:342301
    at t.unstable_runWithPriority (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:417528)
    at Wi (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:342010)
    at Qi (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:342246)
    at Ji (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:342181)
    at nu (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:387605)
    at ba (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:359396)
    at https://editor.gdevelop.io/static/js/1.db615215.chunk.js:1:15522
    at https://editor.gdevelop.io/static/js/1.db615215.chunk.js:1:586413
    at Set.forEach (<anonymous>)
    at s (https://editor.gdevelop.io/static/js/1.db615215.chunk.js:1:586385)
    at i (https://editor.gdevelop.io/static/js/66.098afa85.chunk.js:2:471794)
```

## Component stack (don't write anything here)
```

    in n
    in span
    in button
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in div
    in o
    in d
    in O
    in span
    in Unknown
    in div
    in Unknown
    in ForwardRef
    in div
    in Unknown
    in Unknown
    in pt
    in p
    in l
    in h
    in j
    in j
    in k
    in c
    in Z
    in st
    in n
    in t
    in Le
    in n
    in Unknown
    in t
    in Unknown
    in Unknown
    in m
    in t
    in u
    in t
    in l
    in c
    in n
    in DragDropContext(n)
    in Unknown
    in c
```

## Other details
* IDE version: 5.1.157-78a1361897006d1a1bd592c56d55e748e4a944f1
* Arch: Unknown architecture (web-app),
* Platform Name: Linux armv7l,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (Linux; Android 12; LM-K420) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Mobile Safari/537.36,

**Comment by t-retgt** [comment]
Tt

**Comment by AlexandreSi** [comment]
Hi @t-retgt,
Do you remember what you were doing at the time of the crash?
Do you remember which screen you were looking at?

**Comment by ClementPasteau** [comment]
This translation issue should be fixed
