### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Efvioto** [4ian/GDevelop#4964]
=> Please write here a short description of when the error occurred and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at vu (https://editor.gdevelop.io/static/js/66.8de7747b.chunk.js:2:362259)
    at pu (https://editor.gdevelop.io/static/js/66.8de7747b.chunk.js:2:361757)
    at ws (https://editor.gdevelop.io/static/js/66.8de7747b.chunk.js:2:375957)
    at t.unstable_runWithPriority (https://editor.gdevelop.io/static/js/66.8de7747b.chunk.js:2:396671)
    at Wi (https://editor.gdevelop.io/static/js/66.8de7747b.chunk.js:2:321153)
    at _s (https://editor.gdevelop.io/static/js/66.8de7747b.chunk.js:2:374034)
    at us (https://editor.gdevelop.io/static/js/66.8de7747b.chunk.js:2:370165)
    at https://editor.gdevelop.io/static/js/66.8de7747b.chunk.js:2:321444
    at t.unstable_runWithPriority (https://editor.gdevelop.io/static/js/66.8de7747b.chunk.js:2:396671)
    at Wi (https://editor.gdevelop.io/static/js/66.8de7747b.chunk.js:2:321153)
```

## Component stack (don't write anything here)
```

    in strong
    in p
    in p
    in v
    in t
    in span
    in b
    in p
    in ForwardRef
    in ForwardRef
    in oe
    in div
    in i
    in div
    in ForwardRef
    in ForwardRef
    in t
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in se
    in t
    in ue
    in t
    in ForwardRef
    in div
    in Unknown
    in Unknown
    in jt
    in j
    in d
    in f
    in h
    in h
    in w
    in c
    in Y
    in ct
    in n
    in t
    in Re
    in n
    in Unknown
    in t
    in Unknown
    in Unknown
    in m
    in t
    in u
    in t
    in l
    in c
    in n
    in DragDropContext(n)
    in Unknown
    in c
```

## Other details
* IDE version: 5.1.157-9120a52a08f3be063beff1660c5ce2ef887740d2
* Arch: Unknown architecture (web-app),
* Platform Name: Linux x86_64,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36,

**Comment by Efvioto** [comment]
nao funciona

**Comment by AlexandreSi** [comment]
Hi @Efvioto,
Thank you for taking the time to report this crash.
Do you remember what you were doing at the time of the crash? On which screen? The event sheet or maybe your profile? or the scene editor?

**Comment by Bouh** [comment]
@AlexandreSi more information on this similar issue:
https://github.com/4ian/GDevelop/issues/4975
