### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by KeremBaris** [4ian/GDevelop#5055]
=> Please write here a short description of when the error occurred and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at gu (https://editor.gdevelop.io/static/js/66.1123c1dd.chunk.js:2:362937)
    at ws (https://editor.gdevelop.io/static/js/66.1123c1dd.chunk.js:2:376176)
    at t.unstable_runWithPriority (https://editor.gdevelop.io/static/js/66.1123c1dd.chunk.js:2:396671)
    at Wi (https://editor.gdevelop.io/static/js/66.1123c1dd.chunk.js:2:321153)
    at _s (https://editor.gdevelop.io/static/js/66.1123c1dd.chunk.js:2:374034)
    at us (https://editor.gdevelop.io/static/js/66.1123c1dd.chunk.js:2:370165)
    at https://editor.gdevelop.io/static/js/66.1123c1dd.chunk.js:2:321444
    at t.unstable_runWithPriority (https://editor.gdevelop.io/static/js/66.1123c1dd.chunk.js:2:396671)
    at Wi (https://editor.gdevelop.io/static/js/66.1123c1dd.chunk.js:2:321153)
    at Ji (https://editor.gdevelop.io/static/js/66.1123c1dd.chunk.js:2:321389)
```

## Component stack (don't write anything here)
```

    in n
    in span
    in button
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in div
    in o
    in d
    in O
    in span
    in Unknown
    in div
    in Unknown
    in ForwardRef
    in div
    in Unknown
    in Unknown
    in st
    in j
    in d
    in f
    in h
    in h
    in w
    in c
    in Y
    in tt
    in n
    in t
    in Me
    in n
    in Unknown
    in t
    in Unknown
    in Unknown
    in m
    in xt
    in t
    in u
    in t
    in l
    in c
    in n
    in DragDropContext(n)
    in Unknown
    in c
```

## Other details
* IDE version: 5.1.158-681636a74a6a6f3cb3c74466fddd15f572e0da53
* Arch: Unknown architecture (web-app),
* Platform Name: Linux aarch64,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36,

**Comment by ClementPasteau** [comment]
This should be fixed now
