### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by kapiwa1** [4ian/GDevelop#5098]
=> Please write here a short description of when the error occurred and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at gu (https://editor.gdevelop.io/static/js/66.a3b51c0b.chunk.js:2:355996)
    at ws (https://editor.gdevelop.io/static/js/66.a3b51c0b.chunk.js:2:369235)
    at t.unstable_runWithPriority (https://editor.gdevelop.io/static/js/66.a3b51c0b.chunk.js:2:389730)
    at qi (https://editor.gdevelop.io/static/js/66.a3b51c0b.chunk.js:2:314212)
    at _s (https://editor.gdevelop.io/static/js/66.a3b51c0b.chunk.js:2:367093)
    at us (https://editor.gdevelop.io/static/js/66.a3b51c0b.chunk.js:2:363224)
    at https://editor.gdevelop.io/static/js/66.a3b51c0b.chunk.js:2:314503
    at t.unstable_runWithPriority (https://editor.gdevelop.io/static/js/66.a3b51c0b.chunk.js:2:389730)
    at qi (https://editor.gdevelop.io/static/js/66.a3b51c0b.chunk.js:2:314212)
    at Ji (https://editor.gdevelop.io/static/js/66.a3b51c0b.chunk.js:2:314448)
```

## Component stack (don't write anything here)
```

    in p
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in div
    in i
    in button
    in ForwardRef
    in ForwardRef
    in div
    in o
    in d
    in b
    in div
    in oe
    in div
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in Unknown
    in b
    in div
    in o
    in div
    in i
    in o
    in le
    in div
    in ForwardRef
    in ForwardRef
    in div
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in T
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in t
    in Unknown
    in div
    in Unknown
    in Unknown
    in st
    in j
    in d
    in f
    in h
    in h
    in w
    in c
    in Y
    in tt
    in n
    in t
    in Me
    in n
    in lt
    in t
    in Unknown
    in Unknown
    in m
    in yt
    in t
    in u
    in t
    in l
    in c
    in n
    in DragDropContext(n)
    in Unknown
    in c
```

## Other details
* IDE version: 5.1.158-089c774ad63afb60fa9c3eb27fed39adaa6eaa0b
* Arch: Unknown architecture (web-app),
* Platform Name: Win32,
* System Version: Unknown system version (web-app),
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 YaBrowser/23.1.4.778 Yowser/2.5 Safari/537.36,

**Comment by ClementPasteau** [comment]
This should be fixed now
