### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Harlan124** [4ian/GDevelop#5145]
=> Please write here a short description of when the error occurred and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: c.filter is not a function
    at Ut (file:///C:/Users/phillhar000/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/1.a9a7463a.chunk.js:1:1761986)
    at Yo (file:///C:/Users/phillhar000/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.15f053b2.chunk.js:2:327225)
    at ku (file:///C:/Users/phillhar000/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.15f053b2.chunk.js:2:373331)
    at ms (file:///C:/Users/phillhar000/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.15f053b2.chunk.js:2:366091)
    at vs (file:///C:/Users/phillhar000/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.15f053b2.chunk.js:2:366016)
    at us (file:///C:/Users/phillhar000/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.15f053b2.chunk.js:2:363025)
    at file:///C:/Users/phillhar000/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.15f053b2.chunk.js:2:314503
    at t.unstable_runWithPriority (file:///C:/Users/phillhar000/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.15f053b2.chunk.js:2:389730)
    at qi (file:///C:/Users/phillhar000/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.15f053b2.chunk.js:2:314212)
    at Ji (file:///C:/Users/phillhar000/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.15f053b2.chunk.js:2:314448)
```

## Component stack (don't write anything here)
```

    in Ut
    in div
    in i
    in div
    in o
    in div
    in i
    in t
    in ForwardRef
    in ForwardRef
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in Unknown
    in st
    in j
    in d
    in f
    in h
    in h
    in w
    in c
    in Y
    in tt
    in n
    in t
    in Me
    in n
    in lt
    in t
    in Unknown
    in Unknown
    in m
    in yt
    in t
    in u
    in t
    in l
    in c
    in n
    in DragDropContext(n)
    in Unknown
    in c
```

## Other details
* IDE version: 5.1.159-e7d213534e688726be2e29563fa2aca6fed02c22
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19044,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.1.159 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36,

**Comment by Harlan124** [comment]
nope just opening it up
