### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by LaserBeamerXX** [4ian/GDevelop#5150]
=> The error occurs as soon as i open the Gdevelop Application
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: Cannot read properties of undefined (reading 'length')
    at w (file:///C:/Users/antkillam/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/1.a9a7463a.chunk.js:1:196839)
    at Yo (file:///C:/Users/antkillam/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.15f053b2.chunk.js:2:327225)
    at za (file:///C:/Users/antkillam/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.15f053b2.chunk.js:2:336117)
    at ku (file:///C:/Users/antkillam/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.15f053b2.chunk.js:2:374567)
    at ms (file:///C:/Users/antkillam/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.15f053b2.chunk.js:2:366091)
    at vs (file:///C:/Users/antkillam/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.15f053b2.chunk.js:2:366016)
    at us (file:///C:/Users/antkillam/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.15f053b2.chunk.js:2:363025)
    at file:///C:/Users/antkillam/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.15f053b2.chunk.js:2:314503
    at t.unstable_runWithPriority (file:///C:/Users/antkillam/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.15f053b2.chunk.js:2:389730)
    at qi (file:///C:/Users/antkillam/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.15f053b2.chunk.js:2:314212)
```

## Component stack (don't write anything here)
```

    in w
    in c
    in Y
    in tt
    in n
    in t
    in Me
    in n
    in lt
    in t
    in Unknown
    in Unknown
    in m
    in yt
    in t
    in u
    in t
    in l
    in c
    in n
    in DragDropContext(n)
    in Unknown
    in c
```

## Other details
* IDE version: 5.1.159-e7d213534e688726be2e29563fa2aca6fed02c22
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.19044,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.1.159 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36,

**Comment by ClementPasteau** [comment]
This should be fixed in the next release
