### ISSUE TITLE
when i opened it it just crashes and tells me to report

### ISSUE THREAD

**Issue by holtonholt** [4ian/GDevelop#5165]
=> Please write here a short description of when the error occurred and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: Cannot read properties of undefined (reading 'length')
    at w (file:///Users/hsharp049/Desktop/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/1.fc20ee0c.chunk.js:1:196839)
    at Yo (file:///Users/hsharp049/Desktop/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/66.9bb383a8.chunk.js:2:327225)
    at za (file:///Users/hsharp049/Desktop/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/66.9bb383a8.chunk.js:2:336117)
    at ku (file:///Users/hsharp049/Desktop/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/66.9bb383a8.chunk.js:2:374567)
    at ms (file:///Users/hsharp049/Desktop/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/66.9bb383a8.chunk.js:2:366091)
    at vs (file:///Users/hsharp049/Desktop/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/66.9bb383a8.chunk.js:2:366016)
    at us (file:///Users/hsharp049/Desktop/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/66.9bb383a8.chunk.js:2:363025)
    at file:///Users/hsharp049/Desktop/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/66.9bb383a8.chunk.js:2:314503
    at t.unstable_runWithPriority (file:///Users/hsharp049/Desktop/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/66.9bb383a8.chunk.js:2:389730)
    at qi (file:///Users/hsharp049/Desktop/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/66.9bb383a8.chunk.js:2:314212)
```

## Component stack (don't write anything here)
```

    in w
    in c
    in Y
    in tt
    in n
    in t
    in Me
    in n
    in lt
    in t
    in Unknown
    in Unknown
    in m
    in yt
    in t
    in u
    in t
    in l
    in c
    in n
    in DragDropContext(n)
    in Unknown
    in c
```

## Other details
* IDE version: 5.1.159-e7d213534e688726be2e29563fa2aca6fed02c22
* Arch: x64,
* Platform Name: darwin,
* System Version: 12.4.0,
* User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.1.159 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36,

**Comment by AlexandreSi** [comment]
Hi @holtonholt
Sorry for the inconvenience.
Could you give more info:
- Were you logged in?
- Were you working on a project and expected GDevelop to open the last project?
- What is your username?

**Comment by Oxey405** [comment]
> => Please write here a short description of when the error occurred and how to reproduce it.
You also may have to create an account on GitHub before posting.

Can you write a short description of what happened please @holtonholt
