### ISSUE TITLE
Crash while using an editor (Installing "Sticker" extension)

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop#5188]
Crash occurred when installing "Sticker" extension. 
Windows 11, GDevelop 5.1.159? (I can't find the version in Help > About)

## Error stack (don't write anything here)
```
RuntimeError: memory access out of bounds
    at file:///C:/Users/trist/AppData/Local/Programs/GDevelop/resources/app.asar/www/libGD.wasm?cache-buster=5.1.159-e7d213534e688726be2e29563fa2aca6fed02c22:wasm-function[3588]:0xbc693
    at file:///C:/Users/trist/AppData/Local/Programs/GDevelop/resources/app.asar/www/libGD.wasm?cache-buster=5.1.159-e7d213534e688726be2e29563fa2aca6fed02c22:wasm-function[1031]:0x34428
    at ObjectMetadata.IsUnsupportedBaseObjectCapability.ObjectMetadata.IsUnsupportedBaseObjectCapability [as isUnsupportedBaseObjectCapability] (file:///C:/Users/trist/AppData/Local/Programs/GDevelop/resources/app.asar/www/libGD.js?cache-buster=5.1.159-e7d213534e688726be2e29563fa2aca6fed02c22:9:1264813)
    at D (file:///C:/Users/trist/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/1.a9a7463a.chunk.js:1:780444)
    at Yo (file:///C:/Users/trist/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.15f053b2.chunk.js:2:327225)
    at za (file:///C:/Users/trist/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.15f053b2.chunk.js:2:336117)
    at ku (file:///C:/Users/trist/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.15f053b2.chunk.js:2:374567)
    at ms (file:///C:/Users/trist/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.15f053b2.chunk.js:2:366091)
    at vs (file:///C:/Users/trist/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.15f053b2.chunk.js:2:366016)
    at us (file:///C:/Users/trist/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/66.15f053b2.chunk.js:2:363025)
```

## Component stack (don't write anything here)
```

    in D
    in n
    in t
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in Unknown
    in st
    in j
    in d
    in f
    in h
    in h
    in w
    in c
    in Y
    in tt
    in n
    in t
    in Me
    in n
    in lt
    in t
    in Unknown
    in Unknown
    in m
    in yt
    in t
    in u
    in t
    in l
    in c
    in n
    in DragDropContext(n)
    in Unknown
    in c
```

## Other details
* IDE version: 5.1.159-e7d213534e688726be2e29563fa2aca6fed02c22
* Arch: x64,
* Platform Name: win32,
* System Version: 10.0.22621,
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.1.159 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36,

**Comment by ClementPasteau** [comment]
Thanks for the report @tristanbob 
I suppose this was a one-off problem or did you manage to reproduce it?

**Comment by tristanbob** [comment]
It only happened once, and I install that extension in every game I make. 

You can close this if you want.

**Comment by ClementPasteau** [comment]
Let's keep it, I think it's a valid issue, just hard to reproduce.
Not the same error as #5211  But maybe a similar root cause
