### ISSUE TITLE
Crash while using an editor.

### ISSUE THREAD

**Issue by DoppelgangerGames1** [4ian/GDevelop#5459]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

Every time I boot up the engine I get this error:
 ![Screenshot_1](https://github.com/4ian/GDevelop/assets/54598863/3918e45e-2770-4587-a6a8-7343b57b4200)

And console tells me this:

-THREE.WebGLRenderer: A WebGL context could not be created. Reason:  Web page caused context loss and was blocked
-THREE.WebGLRenderer: A WebGL context could not be created. Reason:  Failed to create a WebGL2 context.
Error: Error creating WebGL context.
    at new e (three.module.js:27858:13)
    at n.value (index.js:178:29)
    at n.value (index.js:144:12)
    at cs (react-dom.production.min.js:212:132)
    at wu (react-dom.production.min.js:255:229)
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at qi (react-dom.production.min.js:122:325)
    at _u (react-dom.production.min.js:248:370)
    at su (react-dom.production.min.js:239:376)
    at react-dom.production.min.js:123:115
Error caught by Boundary: Error: Error creating WebGL context.
    at new e (three.module.js:27858:13)
    at n.value (index.js:178:29)
    at n.value (index.js:144:12)
    at cs (react-dom.production.min.js:212:132)
    at wu (react-dom.production.min.js:255:229)
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at qi (react-dom.production.min.js:122:325)
    at _u (react-dom.production.min.js:248:370)
    at su (react-dom.production.min.js:239:376)
    at react-dom.production.min.js:123:115 
    in n
    in div
    in div
    in Unknown
    in Measure
    in i
    in Unknown
    in div
    in div
    in t
    in div
    in t
    in n
    in o
    in div
    in n
    in n
    in t
    in Unknown
    in Unknown
    in div
    in n
    in Unknown
    in div
    in Unknown
    in Unknown
    in st
    in p
    in d
    in h
    in f
    in f
    in T
    in c
    in X
    in n
    in t
    in Le
    in n
    in tt
    in ut
    in t
    in Unknown
    in Unknown
    in p
    in yt
    in t
    in l
    in t
    in u
    in c
    in n
    in DragDropContext(n)
    in Unknown
    in c

TypeError: Cannot read properties of undefined (reading 'delete')
    at n.value (index.js:477:29)
    at react-dom.production.min.js:209:318
    at ls (react-dom.production.min.js:214:373)
    at gs (react-dom.production.min.js:220:300)
    at wu (react-dom.production.min.js:253:73)
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at qi (react-dom.production.min.js:122:325)
    at _u (react-dom.production.min.js:248:370)
    at su (react-dom.production.min.js:239:376)
    at react-dom.production.min.js:123:115

### Steps to reproduce

1.Boot up the app
2.Wait for my project to load
3.Editor crashes 

### GDevelop platform

Desktop

### GDevelop version

5.2.166

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>Windows 

*OS Version (e.g. Windows 10, macOS 10.15)*
>Windows 8.1

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>Opera GX

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>
Intel Core i5-4590
Nvidia GeForce GTX 1660 SUPER
16GB RAM

**Comment by AlexandreSi** [comment]
Hi @DoppelgangerGames1 ,
Sorry for the inconvenience. It is still the case today? Does the same happen when opening the online editor (https://editor.gdevelop.io)?
