### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by cfrikke** [4ian/GDevelop#5659]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

As soon as I launch the app it crashes after loading

Probably a user error, but what do I need to do?

### Steps to reproduce

Launch the app

### GDevelop platform

Desktop

### GDevelop version

latest

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by AlexandreSi** [comment]
Hi @cfrikke,
Sorry for the inconvenience and thank you for taking the time to report this crash.
If the window is still open after the crash, you should be able to open the developer tools with Ctrl +Shift + i. Go into the console and check for errors (red messages). If you see any, could you copy paste them here?

**Comment by cfrikke** [comment]
Error caught by Boundary: TypeError: Cannot read properties of undefined (reading 'forEach')
    at AssetStoreContext.js:443:37
    at Object.ba [as useMemo] (react-dom.production.min.js:162:119)
    at Object.t.useMemo (react.production.min.js:25:113)
    at P (AssetStoreContext.js:437:33)
    at ea (react-dom.production.min.js:153:146)
    at Ha (react-dom.production.min.js:175:309)
    at Ss (react-dom.production.min.js:263:406)
    at Eu (react-dom.production.min.js:246:265)
    at wu (react-dom.production.min.js:246:194)
    at gu (react-dom.production.min.js:239:172) 
    in P
    in d
    in q
    in n
    in t
    in Ae
    in n
    in ot
    in ht
    in t
    in Unknown
    in Unknown
    in v
    in wt
    in t
    in r
    in d
    in u
    in l
    in n
    in DragDropContext(n)
    in Tt
    in c

react-dom.production.min.js:209 TypeError: Cannot read properties of undefined (reading 'forEach')
    at AssetStoreContext.js:443:37
    at Object.ba [as useMemo] (react-dom.production.min.js:162:119)
    at Object.t.useMemo (react.production.min.js:25:113)
    at P (AssetStoreContext.js:437:33)
    at ea (react-dom.production.min.js:153:146)
    at Ha (react-dom.production.min.js:175:309)
    at Ss (react-dom.production.min.js:263:406)
    at Eu (react-dom.production.min.js:246:265)
    at wu (react-dom.production.min.js:246:194)
    at gu (react-dom.production.min.js:239:172)

**Comment by cfrikke** [comment]
Any updates?

**Comment by AlexandreSi** [comment]
If you got in the network tab and refresh with Ctrl + R, it should crash again and you should be able to see the network requests the editor does.
You should see a request to the URL: `https://resources.gdevelop-app.com/assets-database/assetPacks.json`.
Click on it and go in the tab **Preview**.
Could you send a screenshot of the content of the tab?

**Comment by cfrikke** [comment]
![image](https://github.com/4ian/GDevelop/assets/143611879/a128dd42-bb33-44b4-8662-2fb8860cb2ac)

**Comment by cfrikke** [comment]
![image](https://github.com/4ian/GDevelop/assets/143611879/7b520937-3e5d-4ec5-a290-361003796b84)

**Comment by AlexandreSi** [comment]
Could you send the content of both Headers and Payload tabs, for both lines?
Sorry, this is a bit cumbersome to do.
We will soon release version 5.2.174. You could try to install it to see if the issue is still there.

**Comment by cfrikke** [comment]
![image](https://github.com/4ian/GDevelop/assets/143611879/76e75157-58b8-4730-b834-3cd129f178f2)
![image](https://github.com/4ian/GDevelop/assets/143611879/d0a20888-f2c7-442f-9fe3-afa41598c381)

**Comment by cfrikke** [comment]
![image](https://github.com/4ian/GDevelop/assets/143611879/f5e54f27-9a07-4bfa-902b-120154ff9d1b)
![image](https://github.com/4ian/GDevelop/assets/143611879/35fe4454-2d32-4f79-b619-7885788e56c8)

**Comment by AlexandreSi** [comment]
And could you send the Response tab content as well? Sorry for all those steps 😅

**Comment by cfrikke** [comment]
![image](https://github.com/4ian/GDevelop/assets/143611879/aaad90aa-4bc7-42be-b051-3631e23ee3ef)
![image](https://github.com/4ian/GDevelop/assets/143611879/e8dbe0c4-2c5f-430a-8f25-4efefe1776e4)

**Comment by AlexandreSi** [comment]
That's weird you're getting a 302 HTTP response code on this API call. In which country are you located?

**Comment by cfrikke** [comment]
United States of America

**Comment by AlexandreSi** [comment]
Reopening the issue, await for next version to confirm the issue is gone.

**Comment by AlexandreSi** [comment]
Hi @cfrikke,
Does this issue still happen?
