### ISSUE TITLE
Hard crash with 5.3.179

### ISSUE THREAD

**Issue by fizzingpop** [4ian/GDevelop#5861]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

A crash or error happened in the game.
If you're using JavaScript, verify your code. Otherwise, this might be an issue with GDevelop - consider reporting a bug. Full error is: Cannot read properties of null (reading 'styleID')

TypeError: Cannot read properties of null (reading 'styleID')
    at Ca.updateText (file:///C:/Users/kiara/AppData/Local/Temp/GDTMP--1/preview/pixi-renderers/pixi.js:677:8455)
    at Ca.get width [as width] (file:///C:/Users/kiara/AppData/Local/Temp/GDTMP--1/preview/pixi-renderers/pixi.js:677:13142)
    at o.getWidth (file:///C:/Users/kiara/AppData/Local/Temp/GDTMP--1/preview/Extensions/TextObject/textruntimeobject-pixi-renderer.js:1:2374)
    at d.getWidth (file:///C:/Users/kiara/AppData/Local/Temp/GDTMP--1/preview/Extensions/TextObject/textruntimeobject.js:1:2533)
    at d.getCenterX (file:///C:/Users/kiara/AppData/Local/Temp/GDTMP--1/preview/runtimeobject.js:1:8929)
    at d.setCenterPositionInScene (file:///C:/Users/kiara/AppData/Local/Temp/GDTMP--1/preview/runtimeobject.js:1:9186)
    at Object.gdjs.GameCode.eventsList110 (file:///C:/Users/kiara/AppData/Local/Temp/GDTMP--1/preview/code1.js:7489:46)
    at Object.gdjs.GameCode.eventsList112 (file:///C:/Users/kiara/AppData/Local/Temp/GDTMP--1/preview/code1.js:7542:15)
    at Object.gdjs.GameCode.eventsList398 (file:///C:/Users/kiara/AppData/Local/Temp/GDTMP--1/preview/code1.js:26348:15)
    at c.gdjs.GameCode.func [as _eventsFunction] (file:///C:/Users/kiara/AppData/Local/Temp/GDTMP--1/preview/code1.js:28269:15)

### Steps to reproduce

Not exactly sure what's causing this but I believe its caused by creating a large tiled image.

### GDevelop platform

Desktop

### GDevelop version

5.3.179

### Platform info

<details>

Windows 11

</details>

**Comment by AlexandreSi** [comment]
Hi @fizzingpop,
Sorry for the inconvenience.
Could it be possible that you send us your project and where the crash happens so that we can directly see in your project what could be the root cause for this?
