### ISSUE TITLE
Crash in 5.3.181

### ISSUE THREAD

**Issue by fizzingpop** [4ian/GDevelop#5939]
### Describe what you were doing when the crash happened

The editor kept crashing when I tried to preview the project after roughly an hour of use until I quit and restarted the editor.

TypeError: Cannot read properties of undefined (reading 'func')
    at Object.gdjs.GameCode.eventsList405 (file:///R:/Temp/GDTMP--1/preview/code1.js:26000:110)
    at c.gdjs.GameCode.func [as _eventsFunction] (file:///R:/Temp/GDTMP--1/preview/code1.js:28409:15)
    at c.renderAndStep (file:///R:/Temp/GDTMP--1/preview/runtimescene.js:1:5067)
    at a.step (file:///R:/Temp/GDTMP--1/preview/scenestack.js:1:409)
    at file:///R:/Temp/GDTMP--1/preview/runtimegame.js:1:7879
    at i (file:///R:/Temp/GDTMP--1/preview/pixi-renderers/runtimegame-pixi-renderer.js:1:9624)

### GDevelop version

5.3.181

### Platform info

Windows Desktop App

**Comment by AlexandreSi** [comment]
Hi @fizzingpop,
Thanks for taking the time to report this issue.

Is the error still happening?
If that's the case, could you send us your project so that we can figure out what is happening?

**Comment by 4ian** [comment]
You can indeed send us the project here or to hello@gdevelop.io

Also, do you know if this happened after starting to use a particular extension in your game?

**Comment by subo12234** [comment]
How To send project? this is what my problem
![image_2023-11-23_095837197](https://github.com/4ian/GDevelop/assets/151867256/ae32bd3e-b770-4e67-8583-f4da7f7cb519)

**Comment by fizzingpop** [comment]
Closing issue b/c it was prob caused my system configuration
