### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Dougravinto12** [4ian/GDevelop#5941]
### GDevelop version

5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd

### Platform info

System Version: 6.1.7601 SP1, Arch: x64, User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.181 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: win32

### Additional error context

uniqueErrorId: 4f0922be-d47f-4a01-9bec-2bd2575a89ff

Error: Error creating WebGL context.
    at new e (file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/9821.f092a247.chunk.js:2:3034531)
    at n.value (file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/250.bfadc12b.chunk.js:1:1380587)
    at n.value (file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/250.bfadc12b.chunk.js:1:1380008)
    at ds (file:///C:/Users/Usuario/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/main.9f9ceb3e.js:2:501156)
    at Fu (file:///...

### Additional component context

    in n
    in t
    in Unknown
    in div
    in div
    in Unknown
    in Measure
    in zk
    in ow
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in dM
    in div
    in n
    in Ga
    in div
    in jO
    in Unknown
    in Ke
    in f
    in u
    in v
    in m
    in j
    in h
    in h
    in Z
    in d
    in X
    in n
    in t
    in ge
    in n
    in We
    in et
    in t
    in Unknown
    in Unknown
    in v
    in pt
    in t
    in r
    in n
    in u
    in l
    in n
    in Dr...

**Comment by subo12234** [comment]
same problem with me
