### ISSUE TITLE
editor encountered problem

### ISSUE THREAD

**Issue by subo12234** [4ian/GDevelop#5945]
### Describe what you were doing when the crash happened

I was in project making new sprite in Editor and it crashed when I Opened gdevelop  again and opened project it says that editor encountered a problem and to fix go to github.

### GDevelop version

5.3.181

### Platform info

windows pc

**Comment by subo12234** [comment]
![image_2023-11-23_094721869](https://github.com/4ian/GDevelop/assets/151867256/c1b9a8d3-dcd5-4ccd-9b83-18ea1d1af08c)

**Comment by subo12234** [comment]
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toString')
    at ObjectJsImplementation.bitmapTextObject.getProperties (C:\Users\LUKACHO\AppData\Local\Programs\GDevelop\resources\GDJS\Runtime\Extensions\BitmapText\JsExtension.js:74:41)
    at 4317 (libGD.js?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:9:21098)
    at _emscripten_asm_const_iii (libGD.js?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:9:28306)
    at libGD.wasm?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:0x262c4
    at libGD.wasm?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:0x26614
    at libGD.wasm?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:0x82027
    at libGD.wasm?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:0x81204
    at libGD.wasm?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:0x811d5
    at libGD.wasm?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:0x83e4a
    at libGD.wasm?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:0x3d2a4
index.js:138 Caching resolved local filename: C:/Users/LUKACHO/Documents/GDevelop projects/My project41/Player14.png
index.js:138 Caching resolved local filename: C:/Users/LUKACHO/Documents/GDevelop projects/My project41/Player15.png
index.js:138 Caching resolved local filename: C:/Users/LUKACHO/Documents/GDevelop projects/My project41/Player16.png
index.js:138 Caching resolved local filename: C:/Users/LUKACHO/Documents/GDevelop projects/My project41/Player17.png
2C:\Users\LUKACHO\AppData\Local\Programs\GDevelop\resources\GDJS\Runtime\Extensions\BitmapText\JsExtension.js:74 Uncaught TypeError: Cannot read properties of undefined (reading 'toString')
    at ObjectJsImplementation.bitmapTextObject.getProperties (C:\Users\LUKACHO\AppData\Local\Programs\GDevelop\resources\GDJS\Runtime\Extensions\BitmapText\JsExtension.js:74:41)
    at 4317 (libGD.js?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:9:21098)
    at _emscripten_asm_const_iii (libGD.js?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:9:28306)
    at libGD.wasm?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:0x262c4
    at libGD.wasm?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:0x27bdb
    at ObjectConfiguration.GetProperties.ObjectConfiguration.GetProperties [as getProperties] (libGD.js?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:9:990013)
    at RenderedBitmapTextInstance.update (C:\Users\LUKACHO\AppData\Local\Programs\GDevelop\resources\GDJS\Runtime\Extensions\BitmapText\JsExtension.js:707:62)
    at new RenderedBitmapTextInstance (C:\Users\LUKACHO\AppData\Local\Programs\GDevelop\resources\GDJS\Runtime\Extensions\BitmapText\JsExtension.js:688:12)
    at Object.createNewInstanceRenderer (ObjectsRenderingService.js:92:14)
    at e.getRendererOfInstance (LayerRenderer.js:370:35)
LocalProjectWriter.js:44 Verified C:\Users\LUKACHO\Documents\GDevelop projects\My project41\zombie defense game.json content in 13ms.
index.js:2451 Project saved in 211.10000000149012ms.
EventsFunctionsExtensionsProvider.js:89 Events functions extensions are ready.
index.js:158 GDJS found in  C:\Users\LUKACHO\AppData\Local\Programs\GDevelop\resources\GDJS
index.js:1596 Error caught while launching preview, this should never happen. TypeError: Cannot read properties of undefined (reading 'toString')
    at ObjectJsImplementation.bitmapTextObject.getProperties (C:\Users\LUKACHO\AppData\Local\Programs\GDevelop\resources\GDJS\Runtime\Extensions\BitmapText\JsExtension.js:74:41)
    at 4317 (libGD.js?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:9:21098)
    at _emscripten_asm_const_iii (libGD.js?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:9:28306)
    at libGD.wasm?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:0x262c4
    at libGD.wasm?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:0x26614
    at libGD.wasm?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:0x81f99
    at libGD.wasm?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:0x81204
    at libGD.wasm?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:0x811d5
    at libGD.wasm?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:0x83e4a
    at libGD.wasm?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:0x8568d
(anonymous) @ index.js:1596
react-dom.production.min.js:209 TypeError: Cannot read properties of undefined (reading 'toString')
    at ObjectJsImplementation.bitmapTextObject.getProperties (C:\Users\LUKACHO\AppData\Local\Programs\GDevelop\resources\GDJS\Runtime\Extensions\BitmapText\JsExtension.js:74:41)
    at 4317 (libGD.js?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:9:21098)
    at _emscripten_asm_const_iii (libGD.js?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:9:28306)
    at libGD.wasm?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:0x262c4
    at libGD.wasm?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:0x27bdb
    at ObjectConfiguration.GetProperties.ObjectConfiguration.GetProperties [as getProperties] (libGD.js?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:9:990013)
    at RenderedBitmapTextInstance.update (C:\Users\LUKACHO\AppData\Local\Programs\GDevelop\resources\GDJS\Runtime\Extensions\BitmapText\JsExtension.js:707:62)
    at new RenderedBitmapTextInstance (C:\Users\LUKACHO\AppData\Local\Programs\GDevelop\resources\GDJS\Runtime\Extensions\BitmapText\JsExtension.js:688:12)
    at Object.createNewInstanceRenderer (ObjectsRenderingService.js:92:14)
    at e.getRendererOfInstance (LayerRenderer.js:370:35)
ss @ react-dom.production.min.js:209
ErrorBoundary.js:140 Error 2c94d4ad-1d7c-489a-ae73-b0a057eb9f96 caught by Boundary: TypeError: Cannot read properties of undefined (reading 'toString')
    at ObjectJsImplementation.bitmapTextObject.getProperties (C:\Users\LUKACHO\AppData\Local\Programs\GDevelop\resources\GDJS\Runtime\Extensions\BitmapText\JsExtension.js:74:41)
    at 4317 (libGD.js?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:9:21098)
    at _emscripten_asm_const_iii (libGD.js?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:9:28306)
    at libGD.wasm?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:0x262c4
    at libGD.wasm?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:0x27bdb
    at ObjectConfiguration.GetProperties.ObjectConfiguration.GetProperties [as getProperties] (libGD.js?cache-buster=5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd:9:990013)
    at RenderedBitmapTextInstance.update (C:\Users\LUKACHO\AppData\Local\Programs\GDevelop\resources\GDJS\Runtime\Extensions\BitmapText\JsExtension.js:707:62)
    at new RenderedBitmapTextInstance (C:\Users\LUKACHO\AppData\Local\Programs\GDevelop\resources\GDJS\Runtime\Extensions\BitmapText\JsExtension.js:688:12)
    at Object.createNewInstanceRenderer (ObjectsRenderingService.js:92:14)
    at e.getRendererOfInstance (LayerRenderer.js:370:35) 
    in n
    in t
    in Unknown
    in div
    in div
    in Unknown
    in Measure
    in zk
    in ow
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in dM
    in div
    in n
    in Ga
    in div
    in jO
    in Unknown
    in Ke
    in f
    in u
    in v
    in m
    in j
    in h
    in h
    in Z
    in d
    in X
    in n
    in t
    in ge
    in n
    in We
    in et
    in t
    in Unknown
    in Unknown
    in v
    in pt
    in t
    in r
    in n
    in u
    in l
    in n
    in DragDropContext(n)
    in ht
    in c

**Comment by ClementPasteau** [comment]
It looks like your project is in a state that GDevelop is not able to fix by itself.
Would you be able to download your project, zip it and either share it here or send it to hello@gdevelop.io ?

We can then take a look at what can have happened

**Comment by ClementPasteau** [comment]
From the error, it looks like one of your bitmapText objects is corrupted and hasn't been saved properly.
Were you adding one when the app crashed?

**Comment by subo12234** [comment]
i arleady created new project. i cant download zip file or anything.
