### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by shawn2093** [4ian/GDevelop#5952]
### GDevelop version

5.3.181-4d8cf5692241dda74b855041be3f6a53c590a832

### Platform info

System Version: Unknown system version (web-app), Arch: Unknown architecture (web-app), User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36, Platform: Win32

### Additional error context

uniqueErrorId: 5f2a66d3-c809-4d1e-a299-867c936acc2b

RuntimeError: null function or function signature mismatch
    at https://editor.gdevelop.io/libGD.wasm?cache-buster=5.3.181-4d8cf5692241dda74b855041be3f6a53c590a832:wasm-function[745]:0x3064e
    at BaseEvent.CanHaveSubEvents.BaseEvent.CanHaveSubEvents [as canHaveSubEvents] (https://editor.gdevelop.io/libGD.js?cache-buster=5.3.181-4d8cf5692241dda74b855041be3f6a53c590a832:9:1433906)
    at https://editor.gdevelop.io/static/js/250.0a39e68f.chunk.js:1:621384
    at Array.filter (<anonymous>)
    at Wl (https://editor.gdevelop.io/static/js/250.0a39e68f.chunk.js:1:621349)
    at r._selectionCanHav...

### Additional component context

    in n
    in ForwardRef(rx)
    in n
    in t
    in Unknown
    in pM
    in div
    in n
    in Ga
    in div
    in CO
    in Unknown
    in Ke
    in f
    in u
    in v
    in m
    in j
    in h
    in h
    in Z
    in d
    in X
    in n
    in t
    in ge
    in n
    in We
    in et
    in t
    in Unknown
    in Unknown
    in v
    in pt
    in t
    in r
    in n
    in u
    in l
    in n
    in DragDropContext(n)
    in ht
    in c...

**Comment by ClementPasteau** [comment]
cryptic wasm error.
Happens in the `SelectionHandler` in `getLastSelectedEventContextWhichCanHaveSubEvents()` when calling `event.canHaveSubEvents()`

https://github.com/4ian/GDevelop/blob/master/newIDE/app/src/EventsSheet/SelectionHandler.js#L86

Unsure about the real underlying error
