### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by denialgrey** [4ian/GDevelop#5954]
### GDevelop version

5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd

### Platform info

System Version: 10.0.19045, Arch: x64, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.181 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: win32

### Additional error context

uniqueErrorId: 6ea48c04-2b54-48cf-abeb-111ee8693325

TypeError: e.removeChild is not a function
    at n.value (file:///C:/Users/user/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/9821.f092a247.chunk.js:2:2079928)
    at n.value (file:///C:/Users/user/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/9821.f092a247.chunk.js:2:2080718)
    at n.value (file:///C:/Users/user/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/9821.f092a247.chunk.js:2:2089815)
    at e.value (file:///C:/Users/user/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/250.bfadc12b.chunk.js:1:1340485)
    at e.v...

### Additional component context

    in n
    in t
    in Unknown
    in div
    in div
    in Unknown
    in Measure
    in zk
    in ow
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in dM
    in div
    in n
    in Ga
    in div
    in jO
    in Unknown
    in Ke
    in f
    in u
    in v
    in m
    in j
    in h
    in h
    in Z
    in d
    in X
    in n
    in t
    in ge
    in n
    in We
    in et
    in t
    in Unknown
    in Unknown
    in v
    in pt
    in t
    in r
    in n
    in u
    in l
    in n
    in Dr...

**Comment by ClementPasteau** [comment]
Seem to be happening when the pixiContainer of the layer is destroyed https://github.com/4ian/GDevelop/blob/master/newIDE/app/src/InstancesEditor/InstancesRenderer/LayerRenderer.js#L775

Pixi's container being destroyed tries to remove all children https://github.com/pixijs/pixijs/blob/c04c09c50874fef9296555af23e25fe58cc808a9/packages/display/src/Container.ts#L363

And when an object is being removed, it tries to remove it from its parent: https://github.com/pixijs/pixijs/blob/c04c09c50874fef9296555af23e25fe58cc808a9/packages/display/src/DisplayObject.ts#L665

This is really confusing, as Pixi has a check on wether the parent exists, so it seems that the parent is there, but does not have a method `removeChild()`
