### ISSUE TITLE
BUG on Creating New Objects

### ISSUE THREAD

**Issue by JAdeRency** [4ian/GDevelop#5958]
### Describe what you were doing when the crash happened

1. I went to add a new object in my game
2. when I clicked new object
3. It shows "An error occurred in the New object dialog"
![BUG](https://github.com/4ian/GDevelop/assets/141286066/cb3648b2-5b8d-4231-aa50-f583e93207c1)

### GDevelop version

5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd

### Platform info

System Version: 10.0.22621, Arch: x64, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.181 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: win32

### Additional error context

uniqueErrorId: 75952a99-4eae-4044-a5be-caae5cfa13c4

TypeError: Cannot read properties of undefined (reading 'startsWith')
    at s (file:///C:/Users/rency/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/250.bfadc12b.chunk.js:1:2246086)
    at ea (file:///C:/Users/rency/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/main.9f9ceb3e.js:2:475626)
    at Ha (file:///C:/Users/rency/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/main.9f9ceb3e.js:2:484516)
    at ja (file:///C:/Users/rency/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/main.9f9ceb3e.js:2:484335)
    at Ma (file:///C:...

### Additional component context

    in s
    in div
    in ForwardRef
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in uC
    in ul
    in ForwardRef
    in ForwardRef
    in qe
    in div
    in ForwardRef
    in fC
    in div
    in ForwardRef
    in ForwardRef
    in div
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in k
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in t
    in xC
    in t
    in Unknown
    in vC
    in div
    in ForwardRef
    i...

**Comment by ClementPasteau** [comment]
Fix has been implemented in #5968 
If it happens again, we'll re-open this issue
