### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by PeterStrudwick** [4ian/GDevelop#5974]
### GDevelop version

5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd

### Platform info

System Version: 13.1.0, Arch: arm64, User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.181 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: darwin

### Additional error context

uniqueErrorId: 7e598808-d6ab-4d77-9e6a-f23082db4786

TypeError: i.filter is not a function
    at DP (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/250.6dc43e30.chunk.js:1:1613518)
    at ea (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/main.dc644a89.js:2:475626)
    at Ss (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/main.dc644a89.js:2:521851)
    at Eu (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/main.dc644a89.js:2:514598)
    at wu (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/sta...

### Additional component context

    in DP
    in div
    in div
    in DI
    in t
    in ForwardRef
    in ForwardRef
    in t
    in Unknown
    in dM
    in div
    in n
    in Ga
    in div
    in jO
    in Unknown
    in Ke
    in f
    in u
    in v
    in m
    in j
    in h
    in h
    in Z
    in d
    in X
    in n
    in t
    in ge
    in n
    in We
    in et
    in t
    in Unknown
    in Unknown
    in v
    in pt
    in t
    in r
    in n
    in u
    in l
    in n
    in DragDropContext(n)
    in ht
    in c...

**Comment by ClementPasteau** [comment]
Crash is coming from the filtering on announcements: https://github.com/4ian/GDevelop/blob/master/newIDE/app/src/AnnouncementsFeed/index.js#L52

Looks like the object returned is not an array (network error? proxy?)

Will add a check on the response format and throw if not what's expected
