### ISSUE TITLE
Editor crash - unexpected response from Project API

### ISSUE THREAD

**Issue by GitHubberKid** [4ian/GDevelop#6013]
### GDevelop version

5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd

### Platform info

System Version: 14.0.0, Arch: arm64, User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.181 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: darwin

### Additional error context

uniqueErrorId: ea5644f5-8d31-4085-bc06-e50e30eac593

TypeError: e.map is not a function
    at ME (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/250.6dc43e30.chunk.js:1:1652937)
    at OE (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/250.6dc43e30.chunk.js:1:1654077)
    at ea (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/main.dc644a89.js:2:475626)
    at Ss (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/static/js/main.dc644a89.js:2:521851)
    at Eu (file:///Applications/GDevelop%205.app/Contents/Resources/app.asar/www/...

### Additional component context

    in OE
    in t
    in Unknown
    in AE
    in div
    in div
    in DI
    in t
    in ForwardRef
    in ForwardRef
    in t
    in Unknown
    in dM
    in div
    in n
    in Ga
    in div
    in jO
    in Unknown
    in Ke
    in f
    in u
    in v
    in m
    in j
    in h
    in h
    in Z
    in d
    in X
    in n
    in t
    in ge
    in n
    in We
    in et
    in t
    in Unknown
    in Unknown
    in v
    in pt
    in t
    in r
    in n
    in u
    in l
    in n
    in DragDropContext(n)
    in ht
    in c...

**Comment by ClementPasteau** [comment]
Error when looping through array of cloud projects.
https://github.com/4ian/GDevelop/blob/master/newIDE/app/src/MainFrame/EditorContainers/HomePage/BuildSection/utils.js#L91
So similar error than the other unexpected response from APIs
