### ISSUE TITLE
whenever scene loads in preview or web version viewer breaks

### ISSUE THREAD

**Issue by colsen14323** [4ian/GDevelop#6038]
### Describe what you were doing when the crash happened

Started a preview and viewer crashes, tried updating didnt help, also breaks on the web browser when playing game see https://gd.games/endercolbypvp/outage

### GDevelop version

5.3.181-ec1ebcbf5b57a4623f3ac4eb39a06a26398dc4bd

### Platform info

System Version: 10.0.19045, Arch: x64, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.181 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: win32

### Additional error context

uniqueErrorId: 1301f49b-e40b-42f7-a2d2-875ddbf1ca47

Error: Error creating WebGL context.
    at new e (file:///C:/Users/colby/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/9821.f092a247.chunk.js:2:3034531)
    at n.value (file:///C:/Users/colby/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/250.bfadc12b.chunk.js:1:1380587)
    at n.value (file:///C:/Users/colby/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/250.bfadc12b.chunk.js:1:1380008)
    at ds (file:///C:/Users/colby/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/main.9f9ceb3e.js:2:501156)
    at Fu (file:///C:/Users...

### Additional component context

    in n
    in t
    in Unknown
    in div
    in div
    in Unknown
    in Measure
    in zk
    in ow
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in dM
    in div
    in n
    in Ga
    in div
    in jO
    in Unknown
    in Ke
    in f
    in u
    in v
    in m
    in j
    in h
    in h
    in Z
    in d
    in X
    in n
    in t
    in ge
    in n
    in We
    in et
    in t
    in Unknown
    in Unknown
    in v
    in pt
    in t
    in r
    in n
    in u
    in l
    in n
    in Dr...

**Comment by ClementPasteau** [comment]
Hi @colsen14323 
Can't see any errors opening your game on the link you provided.
![image](https://github.com/4ian/GDevelop/assets/4895034/d8a9a6c2-e0c5-48b2-ad05-619830c6f266)

What problem do you have when you open your link? Can you share a screenshot?

**Comment by colsen14323** [comment]
Made this in High school, I don't think i have the files or any recollection of what this error could be
