### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by plumtiger** [4ian/GDevelop#6039]
### GDevelop version

5.3.181-4d8cf5692241dda74b855041be3f6a53c590a832

### Platform info

System Version: Unknown system version (web-app), Arch: Unknown architecture (web-app), User Agent: Mozilla/5.0 (X11; CrOS armv7l 13099.110.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.136 Safari/537.36, Platform: Linux armv7l

### Additional error context

uniqueErrorId: 2ef1475f-abf1-4b0c-910d-31fa4c60d5d0

Error: Error creating WebGL context.
    at new e (https://editor.gdevelop.io/static/js/8765.a0edf63a.chunk.js:2:3034531)
    at n.value (https://editor.gdevelop.io/static/js/250.0a39e68f.chunk.js:1:1380587)
    at n.value (https://editor.gdevelop.io/static/js/250.0a39e68f.chunk.js:1:1380008)
    at ds (https://editor.gdevelop.io/static/js/main.d34efb95.js:2:501156)
    at Fu (https://editor.gdevelop.io/static/js/main.d34efb95.js:2:518944)
    at t.unstable_runWithPriority (https://editor.gdevelop.io/static/js/main.d34efb95.js:2:547685)
    at Ko (https://editor.gdevelop.io/static/js/main.d34e...

### Additional component context

    in n
    in t
    in Unknown
    in div
    in div
    in Unknown
    in Measure
    in zk
    in ow
    in div
    in div
    in t
    in div
    in t
    in n
    in ForwardRef
    in div
    in l
    in n
    in n
    in t
    in Unknown
    in pM
    in div
    in n
    in Ga
    in div
    in CO
    in Unknown
    in Ke
    in f
    in u
    in v
    in m
    in j
    in h
    in h
    in Z
    in d
    in X
    in n
    in t
    in ge
    in n
    in We
    in et
    in t
    in Unknown
    in Unknown
    in v
    in pt
    in t
    in r
    in n
    in u
    in l
    in n
    in Dr...

**Comment by plumtiger** [comment]
Hope this can be fixed I went to the asset store while working on a project then g develop crashed i think it has something to do with my computer but if you can back it up that would be great but try not to back it up a lot please Thanks Love Gdevelop -Raleigh Chulka
