### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by Taha6090** [4ian/GDevelop#6085]
### GDevelop version

5.3.184-465e9346053202130bb4942e66d84bca2570cc5b

### Platform info

System Version: 10.0.19045, Arch: x64, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.184 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: win32

### Additional error context

uniqueErrorId: d75c77d9-8c9d-4fc4-a30d-76cffee5fff4

TypeError: Cannot read properties of undefined (reading 'startsWith')
    at s (file:///C:/Users/admin/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/3611.5a70831b.chunk.js:1:2283649)
    at ea (file:///C:/Users/admin/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/main.90fd8646.js:2:476454)
    at Ha (file:///C:/Users/admin/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/main.90fd8646.js:2:485344)
    at ja (file:///C:/Users/admin/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/main.90fd8646.js:2:485163)
    at Ma (file:///C...

### Additional component context

    in s
    in div
    in ForwardRef
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in TC
    in ul
    in ForwardRef
    in ForwardRef
    in qe
    in div
    in ForwardRef
    in EC
    in div
    in ForwardRef
    in ForwardRef
    in div
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in k
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in t
    in AC
    in t
    in Unknown
    in OC
    in div
    in ForwardRef
    i...

**Comment by ClementPasteau** [comment]
This is probably fixed in 5.3.186
