### ISSUE TITLE
firebase crashes when using text input on iOS

### ISSUE THREAD

**Issue by konguele** [4ian/GDevelop#6117]
### Describe what you were doing when the crash happened

Hello,

I have been checking and I see no solution to this problem. When text input connects to Firebase I see that it crashes. I use the UserText.Text() function, it has started to happen since I use text input and it happens on iOS. 

```
A crash or error happened in the game.

If you're using JavaScript, verify your code. Otherwise, this might be an issue with GDevelop - consider reporting a bug. Full error is: Function DocumentReference.update() called with invalid data. Data must be an object, but it was: 0 (found in document DatosUsuarios/1n9XhHk0YWM95iLnngbp)

FirebaseError: Function DocumentReference.update() called with invalid data. Data must be an object, but it was: 0 (found in document DatosUsuarios/1n9XhHk0YWM95iLnngbp)
    at new Br (file:///C:/Users/kol69/AppData/Local/Temp/GDTMP--1/preview/Extensions/Firebase/A_firebasejs/B_firebase-firestore.js:1:52445)
    at Ty (file:///C:/Users/kol69/AppData/Local/Temp/GDTMP--1/preview/Extensions/Firebase/A_firebasejs/B_firebase-firestore.js:1:291463)
    at zp.Lc (file:///C:/Users/kol69/AppData/Local/Temp/GDTMP--1/preview/Extensions/Firebase/A_firebasejs/B_firebase-firestore.js:1:284373)
    at vy (file:///C:/Users/kol69/AppData/Local/Temp/GDTMP--1/preview/Extensions/Firebase/A_firebasejs/B_firebase-firestore.js:1:290644)
    at fy (file:///C:/Users/kol69/AppData/Local/Temp/GDTMP--1/preview/Extensions/Firebase/A_firebasejs/B_firebase-firestore.js:1:287706)
    at wg (file:///C:/Users/kol69/AppData/Local/Temp/GDTMP--1/preview/Extensions/Firebase/A_firebasejs/B_firebase-firestore.js:1:307672)
    at Qg.update (file:///C:/Users/kol69/AppData/Local/Temp/GDTMP--1/preview/Extensions/Firebase/A_firebasejs/B_firebase-firestore.js:1:322382)
    at Object.o.updateDocument (file:///C:/Users/kol69/AppData/Local/Temp/GDTMP--1/preview/Extensions/Firebase/B_firebasetools/D_cloudfirestoretools.js:1:1726)
    at Object.gdjs.TiendaCode.eventsList106 (file:///C:/Users/kol69/AppData/Local/Temp/GDTMP--1/preview/code10.js:7498:41)
    at Object.gdjs.TiendaCode.eventsList107 (file:///C:/Users/kol69/AppData/Local/Temp/GDTMP--1/preview/code10.js:7541:17)
```

### GDevelop version

 5.3.186

**Comment by AlexandreSi** [comment]
Hi @konguele,
Thanks for taking the time to report your issue.
Can you send us a project where this issue happens consistently?

**Comment by konguele** [comment]
Hi @AlexandreSi ,

yes, of course. How do I send it to you? 

Thank you!

**Comment by AlexandreSi** [comment]
You can zip the whole project folder and attach it to your message here on GitHub.
If you can keep it to the minimum working project size so that it's clear for us where to look at, it's better!

**Comment by konguele** [comment]
Hello @AlexandreSi ,

In the ZIP file there is only the essential to reproduce the error, which are the Login, create user and shop scenes. 

The problem occurs when you create a user or login. Everything seems to be fine, but when you access the shop as it has the section in the image, the error appears.

At first I thought it was only on iOS, but I have discovered that it also happens on PC and Android.
<img width="1007" alt="Captura de pantalla 2023-12-22 142412" src="https://github.com/4ian/GDevelop/assets/64000046/8edcf767-70ee-4cc6-995f-4d5e174373ee">
[Test.zip](https://github.com/4ian/GDevelop/files/13752770/Test.zip)


If you need more information, don't hesitate to ask me for it.

**Comment by ClementPasteau** [comment]
Without going into the details of the project, are you sure you're using this action right?
The message indicates that the expected variable should be an array and it actually is "0", which usually means that the variable doesn't exist. 
Does your `User` variable exist?

**Comment by konguele** [comment]
Hello,

I have found the problem. The variable was created as String and it must be a Structure, once changed it worked again.

**Comment by AlexandreSi** [comment]
Hi @konguele,
Thanks for checking and getting back to us.
I'm closing this issue since the crash was due to an incorrect use of structure variables.
