### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by SebaNahuel** [4ian/GDevelop#6182]
### GDevelop version

5.3.186-0a6b0dc78508b65a61cf5bcad98827d8998a80e2

### Platform info

System Version: Unknown system version (web-app), Arch: Unknown architecture (web-app), User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36, Platform: Win32

### Additional error context

uniqueErrorId: a6dff62c-a472-4664-ad34-7c1e7b2ea947

RuntimeError: table index is out of bounds
    at https://editor.gdevelop.io/libGD.wasm?cache-buster=5.3.186-0a6b0dc78508b65a61cf5bcad98827d8998a80e2:wasm-function[1424]:0x7fcdc
    at ObjectMetadata.GetName.ObjectMetadata.GetName [as getName] (https://editor.gdevelop.io/libGD.js?cache-buster=5.3.186-0a6b0dc78508b65a61cf5bcad98827d8998a80e2:9:1220901)
    at jd (https://editor.gdevelop.io/static/js/2198.3ca60d5a.chunk.js:1:746004)
    at https://editor.gdevelop.io/static/js/2198.3ca60d5a.chunk.js:1:921753
    at Array.map (<anonymous>)
    at children (https://editor.gdevelop.io/static/js/2198...

### Additional component context

    in t
    in n
    in t
    in div
    in div
    in a
    in Jg
    in div
    in ForwardRef
    in ForwardRef
    in div
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in k
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in dx
    in t
    in Unknown
    in px
    in t
    in div
    in n
    in l
    in n
    in ForwardRef(Em)
    in n
    in t
    in Unknown
    in QM
    in div
    in n
    in oa
    in div
    in vO
    in Unknown
    in Qe
    in f
    in u
    in v
    in x
    in j
    ...

**Comment by ClementPasteau** [comment]
Unsure where this is coming from.
Looks like an object being accessed after being deleted.
What were you doing when the crash happened @SebaNahuel ?
