### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by GeorgeOrf** [4ian/GDevelop#6189]
### Describe what you were doing when the crash happened

I was adding events to my sprite and an error occured.

![Screenshot_5](https://github.com/4ian/GDevelop/assets/156529694/fc649fad-5627-4acc-82d0-3d641cd7eeec)

### GDevelop version

5.3.186-0a6b0dc78508b65a61cf5bcad98827d8998a80e2

### Platform info

System Version: 10.0.22631, Arch: x64, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.186 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: win32

### Additional error context

uniqueErrorId: 42f6606b-8ea7-4cd3-9067-3a70473ff200

Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at fu (file:///C:/Users/giorg/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/main.f3ca4708.js:2:509002)
    at Object.enqueueForceUpdate (file:///C:/Users/giorg/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/main.f3ca4708.js:2:467783)
    at n._.forceUpdate (file:///C:/Users/giorg/AppData/Local/Programs/GDevelop/resources/app.asar/www/static/js/main....

### Additional component context

    in ForwardRef
    in div
    in a
    in div
    in s
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in xh
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in vh
    in Rx
    in div
    in n
    in l
    in n
    in ForwardRef(Em)
    in n
    in t
    in Unknown
    in QM
    in div
    in n
    in oa
    in div
    in vO
    in Unknown
    in Qe
    in f
    in u
    in v
    in x
    in j
    in h
    in h
    in Z
    in d
    in Q
    in n
    in t
    in xe
    in n
    in Ge
    in tt
    in t
    in Unknown
    in Unknown
    in v
    in ft
   ...

**Comment by GeorgeOrf** [comment]
Nope normal settings nothing changed in the download menu etc..
