### ISSUE TITLE
Cannot add a new object

### ISSUE THREAD

**Issue by Slukipikuls** [4ian/GDevelop#6219]
### GDevelop version

5.3.185-64ffad3c0adc031005db7ebed147ed82bb19755b

### Platform info

System Version: 10.0.19045, Arch: x64, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.185 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: win32

### Additional error context

uniqueErrorId: 25762607-d416-4262-b138-f877bb27b0cb

TypeError: Cannot read properties of undefined (reading 'startsWith')
    at s (file:///C:/Users/User/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/3611.38859ce7.chunk.js:1:2283712)
    at ea (file:///C:/Users/User/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.34375dd8.js:2:476454)
    at Ha (file:///C:/Users/User/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.34375dd8.js:2:485344)
    at ja (file:///C:/Users/User/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.34375dd8.js:2:485163)
    at Ma (file:///C:/Us...

### Additional component context

    in s
    in div
    in ForwardRef
    in ForwardRef
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in TC
    in ul
    in ForwardRef
    in ForwardRef
    in qe
    in div
    in ForwardRef
    in EC
    in div
    in ForwardRef
    in ForwardRef
    in div
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in k
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in t
    in AC
    in t
    in Unknown
    in OC
    in div
    in ForwardRef
    i...

**Comment by ClementPasteau** [comment]
Please update to 5.3.186 as this should be fixed
