### ISSUE TITLE
"Tween object scale" action returns error in new version

### ISSUE THREAD

**Issue by LousyMolars** [4ian/GDevelop#6276]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

In 5.3.181 this tween looked like this:
![image](https://github.com/4ian/GDevelop/assets/141857198/391de3f7-2277-40e3-9ad0-0d7861c4d9f6)

In latest (5.3.187) version, X and Y axis were combined to one value:
![image](https://github.com/4ian/GDevelop/assets/141857198/83c02f4d-4b50-4c03-93b3-a0c4c976dfd9)

If I open project from old version, and there is an old action, that works fine. If I create a new one however (or update old), preview returns this error:
```

A crash or error happened in the game.
If you're using JavaScript, verify your code. Otherwise, this might be an issue with GDevelop - consider reporting a bug. Full error is: Right-hand side of 'instanceof' is not an object

TypeError: Right-hand side of 'instanceof' is not an object
    at P.addObjectScaleTween3 (AppData/Local/Temp/GDTMP--1/preview/Extensions/TweenBehavior/tweenruntimebehavior.js:1:4233)
    at Object.gdjs.Untitled_32sceneCode.eventsList0 (AppData/Local/Temp/GDTMP--1/preview/code0.js:50:70)
    at Object.gdjs.Untitled_32sceneCode.eventsList1 (AppData/Local/Temp/GDTMP--1/preview/code0.js:90:100)
    at c.gdjs.Untitled_32sceneCode.func [as _eventsFunction] (AppData/Local/Temp/GDTMP--1/preview/code0.js:159:27)
    at c.renderAndStep (AppData/Local/Temp/GDTMP--1/preview/runtimescene.js:1:5067)
    at r.step (AppData/Local/Temp/GDTMP--1/preview/scenestack.js:1:465)
    at (AppData/Local/Temp/GDTMP--1/preview/runtimegame.js:1:7677)
    at i (AppData/Local/Temp/GDTMP--1/preview/pixi-renderers/runtimegame-pixi-renderer.js:1:9624)
```

Maybe it still looks for Y value? In preview object scales, but only in X axis.

### Steps to reproduce

1. Try to create tween object scale action for any object.
2. Preview this tween.

### GDevelop platform

Desktop

### GDevelop version

5.3.187

### Platform info

<details>

*Win 11

</details>

**Comment by D8H** [comment]
Thank you for reporting this issue. It should be fixed in the next release.

As a workaround, you can add an empty scene with an empty 3D model and it will make this action work in the whole game.

**Comment by AlexandreSi** [comment]
@LousyMolars,
Did you check if this problem still happens with version 5.3.188?

**Comment by LousyMolars** [comment]
> @LousyMolars, Did you check if this problem still happens with version 5.3.188?

I've checked, no error in .188, thank you.
