### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by RebornOfc** [4ian/GDevelop#6297]
### Describe what you were doing when the crash happened

1. Went to my custom object.
2. Tried to add the object itself as a child.
3. Editor bugs.
4. Deleted the entire object.
5. Created another.
6. Tried to add a sprite as child.
7. Results in this error.

### GDevelop version

5.3.187-9eb721662f404d9cc215467ab132bf977fb24121

### Platform info

System Version: 5.4.2-proot-facked, Arch: arm64, User Agent: Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) GDevelop5/5.3.187 Chrome/100.0.4896.143 Electron/18.2.2 Safari/537.36, Platform: linux

### Additional error context

uniqueErrorId: 29dba1de-ae74-4717-a70d-7f5a1392c744

TypeError: Cannot read properties of undefined (reading 'createDisplayName')
    at children (file:///root/Applications/GDevelop53187/resources/app.asar/www/static/js/283.07d4c4f5.chunk.js:1:2156475)
    at t.value (file:///root/Applications/GDevelop53187/resources/app.asar/www/static/js/main.27fe8ae1.js:2:245124)
    at Wa (file:///root/Applications/GDevelop53187/resources/app.asar/www/static/js/main.27fe8ae1.js:2:492130)
    at za (file:///root/Applications/GDevelop53187/resources/app.asar/www/static/js/main.27fe8ae1.js:2:491923)
    at Ss (file:///root/Applications/GDevelop53187/resources/a...

### Additional component context

    in t
    in zt
    in div
    in s
    in div
    in ForwardRef
    in ForwardRef
    in div
    in div
    in ForwardRef
    in ForwardRef
    in div
    in t
    in ForwardRef
    in T
    in div
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Unknown
    in PZ
    in n
    in t
    in Unknown
    in IZ
    in t
    in n
    in div
    in s
    in div
    in ForwardRef
    in ForwardRef
    in Unknown
    in Fh
    in FZ
    in div
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in n
    in k
    in t
    in div
    in div
   ...

**Comment by ClementPasteau** [comment]
This should be fixed in the 5.3.188
