### ISSUE TITLE
Crash when trying to build Gdevelop.js

### ISSUE THREAD

**Issue by mehrabsha** [4ian/GDevelop#7168]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

I faced this error when I was trying to build GDevelop.js 

```
Running "shell:generateFlowTypes" (shell) task
info: Sourcing gdevelopjs-cleaned-bindings-idl0JHegX\Bindings.idl
✅ Properly generated GDevelop.js types.

Running "shell:generateTSTypes" (shell) task
file:///E:/GDevelop/GDevelop.js/scripts/generate-dts.mjs:145
        throw new Error("Never reached character '${thisCharacter}'!");
              ^

Error: Never reached character ' '!
    at Parser.readUntil (file:///E:/GDevelop/GDevelop.js/scripts/generate-dts.mjs:145:15)
    at Parser.readType (file:///E:/GDevelop/GDevelop.js/scripts/generate-dts.mjs:166:21)
    at file:///E:/GDevelop/GDevelop.js/scripts/generate-dts.mjs:253:16
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.12.2
```

### Steps to reproduce

based on [README.md](https://github.com/4ian/GDevelop/blob/master/GDevelop.js/README.md)
1. install all prerequisite tools (node - python - cmake) on windows
2. install and activate emsdk v3.1.21
3. go to GDevelop.js folder with the emscripten environements
4. `npm install` and `npm run build`
5. ERROR

### GDevelop platform

Desktop

### GDevelop version

5.4.218

### Platform info

<details>

Win11

</details>

**Comment by mehrabsha** [comment]
any solution?

**Comment by mehrabsha** [comment]
Any solution?

**Comment by 4ian** [comment]
Not sure why this is happening on Windows but for now you can comment this line to unblock you: https://github.com/4ian/GDevelop/blob/22c72150716ec69f4672625dfcb06f726a30a613/GDevelop.js/Gruntfile.js#L186
