### ISSUE TITLE
Quit action stopped working

### ISSUE THREAD

**Issue by DoppelgangerGames1** [4ian/GDevelop#7216]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/4ian/GDevelop/issues)

### Describe the bug

In my own game I exited to Menu Scene and pressed the "quit" button. It didn't work. Than I created a new projet to test if I messed up something in my events. But no. The quit action didn't work.

Here's what the console showed me:

abstract-debugger-client.ts:205 Could not load @electron/remote from "F:\GDEV\Gdevelop\resources\preview_node_modules\@electron\remote\renderer\index.js". Error is: Error: Cannot find module 'F:\GDEV\Gdevelop\resources\preview_node_modules\@electron\remote\renderer\index.js'
Require stack:
- C:\Users\Doppulus\AppData\Local\Temp\GDTMP--1\preview\index.html
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.i._resolveFilename (node:electron/js2c/renderer_init:33:1095)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.i._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at R.getElectronRemote (runtimegame-pixi-renderer.ts:996:18)
    at R.stopGame (runtimegame-pixi-renderer.ts:917:27)
    at h.step (scenestack.ts:60:43)

https://github.com/user-attachments/assets/2bbaab5b-b59e-4aef-8795-b1a17d4c311d

### Steps to reproduce

1. Open any project
2. Put events: At the beginning of the scene == Quit the game
3. Wait for the game to close...
4. Wait for the game to close...
5. Wait for the game to close...

### GDevelop platform

Desktop

### GDevelop version

5.4.218

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
> Win

*OS Version (e.g. Windows 10, macOS 10.15)*
>Win 10 Pro

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by DoppelgangerGames1** [comment]
> Hi @DoppelgangerGames1 Thanks for reporting this.
> 
> I can't reproduce the issue you're showing in this video, on multiple platforms (Windows/Mac) Could you try re-installing GDevelop to check if it still happens?

Re-installed the program. Works like a charm, thanks!
