### ISSUE TITLE
Online build service is failing for desktop

### ISSUE THREAD

**Issue by Lizard-13** [4ian/GDevelop#753]
## Describe the bug
That, the online build service is failing for desktop builds (Windows, Linux, and Mac), the log:

```
Error: Cannot spawn /usr/local/bin/node: Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:358:11)
    at spawn (child_process.js:533:9)
    at doSpawn (/worker/node_modules/builder-util/src/util.ts:174:12)
    at Promise (/worker/node_modules/builder-util/src/util.ts:208:28)
    at new Promise (<anonymous>)
    at spawn (/worker/node_modules/builder-util/src/util.ts:206:10)
    at installDependencies (/worker/node_modules/electron-builder-lib/src/util/yarn.ts:88:10)
    at /worker/node_modules/electron-builder-lib/src/util/yarn.ts:17:11
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/worker/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/worker/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/worker/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/worker/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/worker/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/worker/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/worker/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/worker/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:121:23)
```

**Comment by 4ian** [comment]
Should be fixed! I wonder if I could restart destroy and recreate regularly the workers (EC2 instances) to avoid this and similar problems in the past months.

**Comment by 4ian** [comment]
Thanks for letting me know :)
